/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

//#line 212 "/usr/lib/gcc/x86_64-linux-gnu/4.6/include/stddef.h"
typedef unsigned long size_t;

unsigned int sum(unsigned int n )
{ unsigned int tmp ;

  {
  if (n) {
    tmp = sum(n - 1U);
    return (n + tmp);
  } else {
    return (0U);
  }
}
}
/*
int main(void)
{ unsigned int tmp ;

  {
  tmp = sum(10U);
  return ((int )tmp);
}
}
*/
