/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 1 "20000715-1.c"
extern void abort(void) ;
#line 2
extern void exit(int  ) ;
#line 4 "20000715-1.c"
void test1(void) 
{ int x ;
  int y ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 7
  x = 3;
#line 7
  y = 2;
#line 9
  if (x < y) {
#line 9
    tmp = x;
#line 9
    x ++;
#line 9
    tmp___1 = tmp;
  } else {
#line 9
    tmp___0 = y;
#line 9
    y ++;
#line 9
    tmp___1 = tmp___0;
  }
#line 9
  if (tmp___1 != 2) {
#line 10
    abort();
  }
#line 12
  if (x != 3) {
#line 13
    abort();
  }
#line 15
  if (y != 3) {
#line 16
    abort();
  }
#line 17
  return;
}
}
#line 19 "20000715-1.c"
void test2(void) 
{ int x ;
  int y ;
  int z ;
  int tmp ;
  int tmp___0 ;

  {
#line 22
  x = 3;
#line 22
  y = 2;
#line 24
  if (x < y) {
#line 24
    tmp = x;
#line 24
    x ++;
#line 24
    z = tmp;
  } else {
#line 24
    tmp___0 = y;
#line 24
    y ++;
#line 24
    z = tmp___0;
  }
#line 25
  if (z != 2) {
#line 26
    abort();
  }
#line 28
  if (x != 3) {
#line 29
    abort();
  }
#line 31
  if (y != 3) {
#line 32
    abort();
  }
#line 33
  return;
}
}
#line 35 "20000715-1.c"
void test3(void) 
{ int x ;
  int y ;
  int xx ;
  int yy ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 38
  x = 3;
#line 38
  y = 2;
#line 39
  xx = 3;
#line 39
  yy = 2;
#line 41
  if (xx < yy) {
#line 41
    tmp = x;
#line 41
    x ++;
#line 41
    tmp___1 = tmp;
  } else {
#line 41
    tmp___0 = y;
#line 41
    y ++;
#line 41
    tmp___1 = tmp___0;
  }
#line 41
  if (tmp___1 != 2) {
#line 42
    abort();
  }
#line 44
  if (x != 3) {
#line 45
    abort();
  }
#line 47
  if (y != 3) {
#line 48
    abort();
  }
#line 49
  return;
}
}
#line 51 "20000715-1.c"
int x  ;
#line 51 "20000715-1.c"
int y  ;
#line 53 "20000715-1.c"
static void init_xy(void) 
{ 

  {
#line 56
  x = 3;
#line 57
  y = 2;
#line 58
  return;
}
}
#line 60 "20000715-1.c"
void test4(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 63
  init_xy();
#line 64
  if (x < y) {
#line 64
    tmp = x;
#line 64
    x ++;
#line 64
    tmp___1 = tmp;
  } else {
#line 64
    tmp___0 = y;
#line 64
    y ++;
#line 64
    tmp___1 = tmp___0;
  }
#line 64
  if (tmp___1 != 2) {
#line 65
    abort();
  }
#line 67
  if (x != 3) {
#line 68
    abort();
  }
#line 70
  if (y != 3) {
#line 71
    abort();
  }
#line 72
  return;
}
}
#line 74 "20000715-1.c"
void test5(void) 
{ int z ;
  int tmp ;
  int tmp___0 ;

  {
#line 79
  init_xy();
#line 80
  if (x < y) {
#line 80
    tmp = x;
#line 80
    x ++;
#line 80
    z = tmp;
  } else {
#line 80
    tmp___0 = y;
#line 80
    y ++;
#line 80
    z = tmp___0;
  }
#line 81
  if (z != 2) {
#line 82
    abort();
  }
#line 84
  if (x != 3) {
#line 85
    abort();
  }
#line 87
  if (y != 3) {
#line 88
    abort();
  }
#line 89
  return;
}
}
#line 91 "20000715-1.c"
void test6(void) 
{ int xx ;
  int yy ;
  int z ;
  int tmp ;
  int tmp___0 ;

  {
#line 94
  xx = 3;
#line 94
  yy = 2;
#line 97
  init_xy();
#line 98
  if (xx < y) {
#line 98
    tmp = x;
#line 98
    x ++;
#line 98
    z = tmp;
  } else {
#line 98
    tmp___0 = y;
#line 98
    y ++;
#line 98
    z = tmp___0;
  }
#line 99
  if (z != 2) {
#line 100
    abort();
  }
#line 102
  if (x != 3) {
#line 103
    abort();
  }
#line 105
  if (y != 3) {
#line 106
    abort();
  }
#line 107
  return;
}
}
#line 109 "20000715-1.c"
int main(void) 
{ 

  {
#line 110
  test1();
#line 111
  test2();
#line 112
  test3();
#line 113
  test4();
#line 114
  test5();
#line 115
  test6();
#line 116
  exit(0);
}
}
