/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20000523-1.c"
int main(void) 
{ long long x ;
  int n ;

  {
#line 7
  if (sizeof(long long ) < 8UL) {
#line 8
    exit(0);
  }
#line 10
  n = 9;
#line 11
  x = ((long long )n << 55) / 255LL;
#line 13
  if (x == 0LL) {
#line 14
    abort();
  }
#line 16
  x = (9LL << 55) / 255LL;
#line 18
  if (x == 0LL) {
#line 19
    abort();
  }
#line 21
  exit(0);
}
}
