/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20000717-2.c"
static void compare(long long foo ) 
{ 

  {
#line 5
  if (foo < 4294967297LL) {
#line 6
    abort();
  }
#line 7
  return;
}
}
#line 8 "20000717-2.c"
int main(void) 
{ 

  {
#line 10
  compare(8589934591LL);
#line 11
  exit(0);
}
}
