/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20000731-1.c"
double foo(void) 
{ 

  {
#line 5
  return (0.0);
}
}
#line 8 "20000731-1.c"
void do_sibcall(void) 
{ 

  {
#line 11
  foo();
#line 12
  return;
}
}
#line 14 "20000731-1.c"
int main(void) 
{ double x ;

  {
#line 18
  x = (double )0;
#line 18
  while (x < (double )20) {
#line 19
    do_sibcall();
#line 18
    x += (double )1;
  }
#line 20
  if (! (x >= (double )10)) {
#line 21
    abort();
  }
#line 22
  exit(0);
}
}
