/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct _RenderInfo;
typedef struct _RenderInfo RenderInfo;
struct _RenderInfo {
   int y ;
   float scaley ;
   int src_y ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
static void bar(void) 
{ 

  {
  return;
}
}
static int render_image_rgb_a(RenderInfo *info ) 
{ int y ;
  int ye ;
  float error ;
  float step ;

  {
  y = info->y;
  ye = 256;
  step = (float )(1.0 / (double )info->scaley);
  error = (float )y * step;
  error -= (float )((int )error) - step;
  while (y < ye) {
    if ((double )error >= 1.0) {
      info->src_y += (int )error;
      error -= (float )((int )error);
      bar();
    }
    error += step;
    y ++;
  }
  return (info->src_y);
}
}
int main(void) 
{ RenderInfo info ;
  int tmp ;

  {
  info.y = 0;
  info.src_y = 0;
  info.scaley = (float )1.0;
  tmp = render_image_rgb_a(& info);
  if (tmp != 256) {
    abort();
  }
  exit(0);
}
}
