/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__)) char *strchr(char const   *__s , int __c )  __attribute__((__pure__,
__nonnull__(1), __leaf__)) ;
char *list[2]  = {      (char *)"*",      (char *)"e"};
static int bar(char const   *fmt ) 
{ char *tmp ;

  {
  tmp = strchr(fmt, '*');
  return ((unsigned long )tmp != (unsigned long )((char *)0));
}
}
static void foo(void) 
{ int i ;
  char const   *fmt ;
  int tmp ;

  {
  i = 0;
  while ((unsigned long )i < sizeof(list) / sizeof(list[0])) {
    fmt = (char const   *)list[i];
    tmp = bar(fmt);
    if (tmp) {
      goto __Cont;
    }
    if (i == 0) {
      abort();
    } else {
      exit(0);
    }
    __Cont: /* CIL Label */ 
    i ++;
  }
  return;
}
}
int main(void) 
{ 

  {
  foo();
  return (0);
}
}
