/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 2 "20000313-1.c"
unsigned int buggy(unsigned int *param ) 
{ unsigned int accu ;
  unsigned int zero ;
  unsigned int borrow ;

  {
#line 4
  zero = 0U;
#line 5
  accu = - *param;
#line 6
  borrow = (unsigned int )(- (accu > zero));
#line 7
  *param += accu;
#line 8
  return (borrow);
}
}
#line 11 "20000313-1.c"
int main(void) 
{ unsigned int param ;
  unsigned int borrow ;
  unsigned int tmp ;

  {
#line 13
  param = 1U;
#line 14
  tmp = buggy(& param);
#line 14
  borrow = tmp;
#line 16
  if (param != 0U) {
#line 17
    abort();
  }
#line 18
  if (borrow + 1U != 0U) {
#line 19
    abort();
  }
#line 20
  return (0);
}
}
