/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20001027-1.c"
int x  ;
#line 2 "20001027-1.c"
int *p  =    & x;
#line 4 "20001027-1.c"
int main(void) 
{ int i ;

  {
#line 6
  i = 0;
#line 7
  x = 1;
#line 8
  *(p + i) = 2;
#line 9
  if (x != 2) {
#line 10
    abort();
  }
#line 11
  exit(0);
}
}
