/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct __anonstruct_x_21 {
   long a ;
   char b[1] ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
static void foo(void) 
{ struct __anonstruct_x_21 x ;

  {
  x.a = 2L;
  x.b[0] = (char)0;
  return;
}
}
int main(void) 
{ int tmp ;

  {
  foo();
  tmp = 1;
  exit(0);
}
}
