/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 7 "fsl-header.h"
extern void exit(int  ) ;
#line 38 "20001229-1.c"
void foo(char *a , char *b ) 
{ 

  {
#line 38
  return;
}
}
#line 40 "20001229-1.c"
void showinfo(void) 
{ char uname[33] ;
  char tty[38] ;

  {
#line 42
  uname[0] = (char )'\000';
#line 42
  tty[0] = (char )'/';
#line 42
  tty[1] = (char )'d';
#line 42
  tty[2] = (char )'e';
#line 42
  tty[3] = (char )'v';
#line 42
  tty[4] = (char )'/';
#line 42
  tty[5] = (char )'\000';
#line 43
  foo(uname, tty);
#line 44
  return;
}
}
#line 46 "20001229-1.c"
int main(void) 
{ 

  {
#line 48
  showinfo();
#line 49
  exit(0);
}
}
