/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct F {
   int i ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
void f1(struct F *x , struct F *y ) 
{ int timeout ;

  {
  timeout = 0;
  while (((struct F  const  *)x)->i < (int const   )y->i) {
    timeout ++;
    if (timeout > 5) {
      abort();
    }
    (x->i) ++;
  }
  return;
}
}
int main(void) 
{ struct F x ;
  struct F y ;

  {
  x.i = 0;
  y.i = 1;
  f1(& x, & y);
  exit(0);
}
}
