/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "20000113-1.c"
struct x {
   unsigned int x1 : 1 ;
   unsigned int x2 : 2 ;
   unsigned int x3 : 3 ;
};
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 8 "20000113-1.c"
void foobar(int x , int y , int z ) 
{ struct x a ;
  struct x b ;
  struct x *c ;

  {
#line 10
  a.x1 = (unsigned int )x;
#line 10
  a.x2 = (unsigned int )y;
#line 10
  a.x3 = (unsigned int )z;
#line 11
  b.x1 = (unsigned int )x;
#line 11
  b.x2 = (unsigned int )y;
#line 11
  b.x3 = (unsigned int )z;
#line 12
  c = & b;
#line 14
  c->x3 += (a.x2 - a.x1) * c->x2;
#line 15
  if (a.x1 != 1U) {
#line 16
    abort();
  } else {
#line 15
    if (c->x3 != 5U) {
#line 16
      abort();
    }
  }
#line 17
  exit(0);
}
}
#line 20 "20000113-1.c"
int main(void) 
{ 

  {
#line 22
  foobar(1, 2, 3);
#line 23
  return (0);
}
}
