/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int main(void) 
{ long long i ;

  {
  i = 1LL;
  i = i * 2LL + 1LL;
  if (i != 3LL) {
    abort();
  }
  exit(0);
}
}
