/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 1 "20001111-1.c"
extern void exit(int status ) ;
#line 2
extern void abort(void) ;
#line 4 "20001111-1.c"
static int next_buffer  =    0;
#line 5
void bar(void) ;
#line 7 "20001111-1.c"
static int u  =    0;
#line 9 "20001111-1.c"
long foo(unsigned int offset ) 
{ unsigned int i ;
  unsigned int buffer ;
  char *data ;

  {
#line 16
  i = (unsigned int )u;
#line 17
  if (i) {
#line 18
    return ((long )(i * 52783U));
  }
#line 20
  buffer = (unsigned int )next_buffer;
#line 21
  data = (char *)(buffer * 52783U);
#line 22
  i = 0U;
#line 22
  while (i < 2U) {
#line 23
    bar();
#line 22
    i ++;
  }
#line 24
  buffer = (unsigned int )next_buffer;
#line 25
  return ((long )(buffer * 52783U + offset));
}
}
#line 29 "20001111-1.c"
void bar(void) 
{ 

  {
#line 32
  return;
}
}
#line 34 "20001111-1.c"
int main(void) 
{ long tmp ;
  long tmp___0 ;

  {
#line 37
  tmp = foo(3U);
#line 37
  if (tmp != 3L) {
#line 38
    abort();
  }
#line 39
  next_buffer = 1;
#line 40
  tmp___0 = foo(2U);
#line 40
  if (tmp___0 != 52785L) {
#line 41
    abort();
  }
#line 42
  exit(0);
}
}
