/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20000225-1.c"
int main(void) 
{ int nResult ;
  int b ;
  int i ;

  {
#line 5
  b = 0;
#line 6
  i = -1;
#line 8
  while (1) {
#line 10
    if (b != 0) {
#line 11
      abort();
#line 12
      nResult = 1;
    } else {
#line 14
      nResult = 0;
    }
#line 16
    i ++;
#line 17
    b = (i + 2) * 4;
#line 8
    if (! (i < 0)) {
#line 8
      break;
    }
  }
#line 19
  exit(0);
}
}
