/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 4 "20000706-5.c"
struct baz {
   int a ;
   int b ;
   int c ;
};
#line 1
extern void abort(void) ;
#line 2
extern void exit(int  ) ;
#line 6 "20000706-5.c"
struct baz *c  ;
#line 8 "20000706-5.c"
void bar(int b ) 
{ 

  {
#line 10
  if (c->a != 1) {
#line 11
    abort();
  } else {
#line 10
    if (c->b != 2) {
#line 11
      abort();
    } else {
#line 10
      if (c->c != 3) {
#line 11
        abort();
      } else {
#line 10
        if (b != 4) {
#line 11
          abort();
        }
      }
    }
  }
#line 12
  return;
}
}
#line 14 "20000706-5.c"
void foo(struct baz a , int b ) 
{ 

  {
#line 16
  c = & a;
#line 17
  bar(b);
#line 18
  return;
}
}
#line 20 "20000706-5.c"
int main(void) 
{ struct baz a ;

  {
#line 23
  a.a = 1;
#line 24
  a.b = 2;
#line 25
  a.c = 3;
#line 26
  foo(a, 4);
#line 27
  exit(0);
}
}
