/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int main(void) 
{ long long x ;
  int n ;

  {
  if (sizeof(long long ) < 8UL) {
    exit(0);
  }
  n = 9;
  x = ((long long )n << 55) / 255LL;
  if (x == 0LL) {
    abort();
  }
  x = (9LL << 55) / 255LL;
  if (x == 0LL) {
    abort();
  }
  exit(0);
}
}
