/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef unsigned long ull;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
void checkit(int a ) ;
int main(void) 
{ ull a ;
  ull b ;
  ull c ;
  ull d ;

  {
  a = (ull )85899345920ULL;
  b = (ull )2147483648ULL;
  c = a / b;
  d = (ull )40ULL;
  checkit((int )c);
  checkit((int )d);
  exit(0);
}
}
void checkit(int a ) 
{ 

  {
  if (a != 40) {
    abort();
  }
  return;
}
}
