/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "20000605-1.c"
struct _RenderInfo;
#line 2 "20000605-1.c"
typedef struct _RenderInfo RenderInfo;
#line 3 "20000605-1.c"
struct _RenderInfo {
   int y ;
   float scaley ;
   int src_y ;
};
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 10 "20000605-1.c"
static void bar(void) 
{ 

  {
#line 10
  return;
}
}
#line 12 "20000605-1.c"
static int render_image_rgb_a(RenderInfo *info ) 
{ int y ;
  int ye ;
  float error ;
  float step ;

  {
#line 19
  y = info->y;
#line 20
  ye = 256;
#line 22
  step = (float )(1.0 / (double )info->scaley);
#line 24
  error = (float )y * step;
#line 25
  error -= (float )((int )error) - step;
#line 27
  while (y < ye) {
#line 28
    if ((double )error >= 1.0) {
#line 29
      info->src_y += (int )error;
#line 30
      error -= (float )((int )error);
#line 31
      bar();
    }
#line 33
    error += step;
#line 27
    y ++;
  }
#line 35
  return (info->src_y);
}
}
#line 38 "20000605-1.c"
int main(void) 
{ RenderInfo info ;
  int tmp ;

  {
#line 42
  info.y = 0;
#line 43
  info.src_y = 0;
#line 44
  info.scaley = (float )1.0;
#line 46
  tmp = render_image_rgb_a(& info);
#line 46
  if (tmp != 256) {
#line 47
    abort();
  }
#line 48
  exit(0);
}
}
