/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern void abort(void) ;
extern void exit(int  ) ;
void test1(void) 
{ int x ;
  int y ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
  x = 3;
  y = 2;
  if (x < y) {
    tmp = x;
    x ++;
    tmp___1 = tmp;
  } else {
    tmp___0 = y;
    y ++;
    tmp___1 = tmp___0;
  }
  if (tmp___1 != 2) {
    abort();
  }
  if (x != 3) {
    abort();
  }
  if (y != 3) {
    abort();
  }
  return;
}
}
void test2(void) 
{ int x ;
  int y ;
  int z ;
  int tmp ;
  int tmp___0 ;

  {
  x = 3;
  y = 2;
  if (x < y) {
    tmp = x;
    x ++;
    z = tmp;
  } else {
    tmp___0 = y;
    y ++;
    z = tmp___0;
  }
  if (z != 2) {
    abort();
  }
  if (x != 3) {
    abort();
  }
  if (y != 3) {
    abort();
  }
  return;
}
}
void test3(void) 
{ int x ;
  int y ;
  int xx ;
  int yy ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
  x = 3;
  y = 2;
  xx = 3;
  yy = 2;
  if (xx < yy) {
    tmp = x;
    x ++;
    tmp___1 = tmp;
  } else {
    tmp___0 = y;
    y ++;
    tmp___1 = tmp___0;
  }
  if (tmp___1 != 2) {
    abort();
  }
  if (x != 3) {
    abort();
  }
  if (y != 3) {
    abort();
  }
  return;
}
}
int x  ;
int y  ;
static void init_xy(void) 
{ 

  {
  x = 3;
  y = 2;
  return;
}
}
void test4(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
  init_xy();
  if (x < y) {
    tmp = x;
    x ++;
    tmp___1 = tmp;
  } else {
    tmp___0 = y;
    y ++;
    tmp___1 = tmp___0;
  }
  if (tmp___1 != 2) {
    abort();
  }
  if (x != 3) {
    abort();
  }
  if (y != 3) {
    abort();
  }
  return;
}
}
void test5(void) 
{ int z ;
  int tmp ;
  int tmp___0 ;

  {
  init_xy();
  if (x < y) {
    tmp = x;
    x ++;
    z = tmp;
  } else {
    tmp___0 = y;
    y ++;
    z = tmp___0;
  }
  if (z != 2) {
    abort();
  }
  if (x != 3) {
    abort();
  }
  if (y != 3) {
    abort();
  }
  return;
}
}
void test6(void) 
{ int xx ;
  int yy ;
  int z ;
  int tmp ;
  int tmp___0 ;

  {
  xx = 3;
  yy = 2;
  init_xy();
  if (xx < y) {
    tmp = x;
    x ++;
    z = tmp;
  } else {
    tmp___0 = y;
    y ++;
    z = tmp___0;
  }
  if (z != 2) {
    abort();
  }
  if (x != 3) {
    abort();
  }
  if (y != 3) {
    abort();
  }
  return;
}
}
int main(void) 
{ 

  {
  test1();
  test2();
  test3();
  test4();
  test5();
  test6();
  exit(0);
}
}
