/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
static unsigned char const   f[3]  = {      (unsigned char const   )'\000',      (unsigned char const   )'\377',      (unsigned char const   )'\000'};
static unsigned char const   g[3]  = {      (unsigned char const   )'\000',      (unsigned char const   )'\377',      (unsigned char const   )'\000'};
int main(void) 
{ 

  {
  if (sizeof(f) != 3UL) {
    abort();
  } else {
    if (sizeof(g) != 3UL) {
      abort();
    }
  }
  if ((int const   )f[0] != (int const   )g[0]) {
    abort();
  }
  if ((int const   )f[1] != (int const   )g[1]) {
    abort();
  }
  if ((int const   )f[2] != (int const   )g[2]) {
    abort();
  }
  return (0);
}
}
