/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20000422-1.c"
int ops[13]  = 
#line 2 "20000422-1.c"
  {      11,      12,      46,      3, 
        2,      2,      3,      2, 
        1,      3,      2,      1, 
        2};
#line 7 "20000422-1.c"
int correct[13]  = 
#line 7
  {      46,      12,      11,      3, 
        3,      3,      2,      2, 
        2,      2,      2,      1, 
        1};
#line 12 "20000422-1.c"
int num  =    13;
#line 14 "20000422-1.c"
int main(void) 
{ int i ;
  int j ;
  int op ;

  {
#line 18
  i = 0;
#line 18
  while (i < num) {
#line 22
    j = num - 1;
#line 22
    while (j > i) {
#line 24
      if (ops[j - 1] < ops[j]) {
#line 26
        op = ops[j];
#line 27
        ops[j] = ops[j - 1];
#line 28
        ops[j - 1] = op;
      }
#line 22
      j --;
    }
#line 18
    i ++;
  }
#line 34
  i = 0;
#line 34
  while (i < num) {
#line 35
    if (ops[i] != correct[i]) {
#line 36
      abort();
    }
#line 34
    i ++;
  }
#line 38
  exit(0);
}
}
