/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int c  =    -1;
int foo(int *p ) 
{ int x ;
  int a ;

  {
  a = *(p + 0);
  x = a + 5;
  a = c;
  *(p + 0) = x - 15;
  return (a);
}
}
int main(void) 
{ int b ;
  int a ;
  int tmp ;

  {
  b = 1;
  tmp = foo(& b);
  a = tmp;
  if (a != -1) {
    abort();
  } else {
    if (b != -9) {
      abort();
    }
  }
  exit(0);
}
}
