/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "20000717-1.c"
struct trio {
   int a ;
   int b ;
   int c ;
};
#line 2 "20000717-1.c"
typedef struct trio trio;
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 4 "20000717-1.c"
int bar(int i , trio t ) 
{ 

  {
#line 7
  if (t.a == t.b) {
#line 8
    abort();
  } else {
#line 7
    if (t.a == t.c) {
#line 8
      abort();
    }
  }
#line 9
  return (0);
}
}
#line 12 "20000717-1.c"
int foo(trio t , int i ) 
{ int tmp ;

  {
#line 15
  tmp = bar(i, t);
#line 15
  return (tmp);
}
}
#line 18 "20000717-1.c"
int main(void) 
{ trio t ;

  {
#line 20
  t.a = 1;
#line 20
  t.b = 2;
#line 20
  t.c = 3;
#line 22
  foo(t, 4);
#line 23
  exit(0);
}
}
