/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
unsigned int buggy(unsigned int *param ) 
{ unsigned int accu ;
  unsigned int zero ;
  unsigned int borrow ;

  {
  zero = 0U;
  accu = - *param;
  borrow = (unsigned int )(- (accu > zero));
  *param += accu;
  return (borrow);
}
}
int main(void) 
{ unsigned int param ;
  unsigned int borrow ;
  unsigned int tmp ;

  {
  param = 1U;
  tmp = buggy(& param);
  borrow = tmp;
  if (param != 0U) {
    abort();
  }
  if (borrow + 1U != 0U) {
    abort();
  }
  return (0);
}
}
