/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern void exit(int status ) ;
extern void abort(void) ;
static char arg0[5]  = {      (char )'a',      (char )'r',      (char )'g',      (char )'0', 
        (char )'\000'};
static char arg1[5]  = {      (char )'a',      (char )'r',      (char )'g',      (char )'1', 
        (char )'\000'};
static void attr_rtx(char *varg0 , char *varg1 ) ;
static char *attr_string(char *str ) ;
static void attr_eq(char *name , char *value ) ;
static void attr_rtx(char *varg0 , char *varg1 ) 
{ 

  {
  if ((unsigned long )varg0 != (unsigned long )(arg0)) {
    abort();
  }
  if ((unsigned long )varg1 != (unsigned long )(arg1)) {
    abort();
  }
  return;
}
}
static void attr_eq(char *name , char *value ) 
{ char *tmp ;
  char *tmp___0 ;

  {
  tmp = attr_string(value);
  tmp___0 = attr_string(name);
  attr_rtx(tmp___0, tmp);
  return;
}
}
static char *attr_string(char *str ) 
{ 

  {
  return (str);
}
}
int main(void) 
{ 

  {
  attr_eq(arg0, arg1);
  exit(0);
}
}
