/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct __anonstruct_lastglob_21 {
   int node ;
   int type ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int main(void) 
{ struct __anonstruct_lastglob_21 lastglob[1] ;

  {
  lastglob[0].node = 0;
  lastglob[0].type = 1;
  if (lastglob[0].node != 0) {
    abort();
  } else {
    if (lastglob[0].type != 1) {
      abort();
    }
  }
  exit(0);
}
}
