/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 4 "20010224-1.c"
typedef short int16_t;
#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 7 "20010224-1.c"
int16_t logadd(int16_t *a , int16_t *b ) ;
#line 8
void ba_compute_psd(int16_t start ) ;
#line 10 "20010224-1.c"
int16_t masktab[6]  = {      (int16_t )1,      (int16_t )2,      (int16_t )3,      (int16_t )4, 
        (int16_t )5,      (short)0};
#line 11 "20010224-1.c"
int16_t psd[6]  = {      (int16_t )50,      (int16_t )40,      (int16_t )30,      (int16_t )20, 
        (int16_t )10,      (short)0};
#line 12 "20010224-1.c"
int16_t bndpsd[6]  = {      (int16_t )1,      (int16_t )2,      (int16_t )3,      (int16_t )4, 
        (int16_t )5,      (short)0};
#line 14 "20010224-1.c"
void ba_compute_psd(int16_t start ) 
{ int i ;
  int j ;
  int k ;
  int16_t lastbin ;

  {
#line 17
  lastbin = (int16_t )4;
#line 19
  j = (int )start;
#line 20
  k = (int )masktab[start];
#line 22
  bndpsd[k] = psd[j];
#line 23
  j ++;
#line 25
  i = j;
#line 25
  while (i < (int )lastbin) {
#line 26
    bndpsd[k] = logadd(& bndpsd[k], & psd[j]);
#line 27
    j ++;
#line 25
    i ++;
  }
#line 29
  return;
}
}
#line 31 "20010224-1.c"
int16_t logadd(int16_t *a , int16_t *b ) 
{ 

  {
#line 33
  return ((short )((int )*a + (int )*b));
}
}
#line 36 "20010224-1.c"
int main(void) 
{ 

  {
#line 40
  ba_compute_psd((short)0);
#line 42
  if ((int )bndpsd[1] != 140) {
#line 42
    abort();
  }
#line 43
  return (0);
}
}
