/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

static char const   *test(char const   *in , char *out ) 
{ char const   *p ;
  char *tmp ;
  char const   *tmp___0 ;

  {
  while (1) {
    if ((int const   )*in == 97) {
      p = in + 1;
      while ((int const   )*p == 120) {
        p ++;
      }
      if ((int const   )*p == 98) {
        return (p);
      }
      while ((unsigned long )in < (unsigned long )p) {
        tmp = out;
        out ++;
        tmp___0 = in;
        in ++;
        *tmp = (char )*tmp___0;
      }
    }
  }
}
}
int main(void) 
{ char out[4] ;

  {
  test("aab", out);
  return (0);
}
}
