/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 7 "fsl-header.h"
extern void exit(int  ) ;
#line 15 "20010119-1.c"
void foo(int a , int b ) 
{ 

  {
#line 17
  return;
}
}
#line 20 "20010119-1.c"
int main(void) 
{ 

  {
#line 22
  foo(10, 100);
#line 23
  exit(0);
}
}
