/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 6 "20010325-1.c"
extern void exit(int  ) ;
#line 7
extern void abort(void) ;
#line 9 "20010325-1.c"
int main(void) 
{ 

  {
#line 11
  if (*(L"ab" + 1) != 98) {
#line 12
    abort();
  }
#line 13
  exit(0);
}
}
