/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int f(int a , int b , int c , _Bool d , _Bool e , _Bool f___0 , char g ) 
{ 

  {
  if ((int )g != 1) {
    abort();
  } else {
    if ((int )d != 1) {
      abort();
    } else {
      if ((int )e != 1) {
        abort();
      } else {
        if ((int )f___0 != 1) {
          abort();
        }
      }
    }
  }
  return ((a + b) + c);
}
}
int main(void) 
{ int tmp ;

  {
  tmp = f(1, 2, -3, (_Bool)1, (_Bool)1, (_Bool)1, (char )'\001');
  if (tmp) {
    abort();
  }
  exit(0);
}
}
