/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20010520-1.c"
static unsigned int expr_hash_table_size  =    1U;
#line 4 "20010520-1.c"
int main(void) 
{ int del ;
  unsigned int i ;

  {
#line 6
  del = 1;
#line 7
  i = 0U;
#line 9
  if (i < expr_hash_table_size) {
#line 9
    if (del) {
#line 10
      exit(0);
    }
  }
#line 11
  abort();
#line 12
  return (0);
}
}
