/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20010206-1.c"
int foo(void) 
{ int i ;

  {
#line 1
  i = 26;
#line 2
  return (i);
}
}
#line 5 "20010206-1.c"
int main(void) 
{ int tmp ;

  {
#line 7
  tmp = foo();
#line 7
  if (tmp != 26) {
#line 8
    abort();
  }
#line 9
  exit(0);
}
}
