/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 4 "20010518-1.c"
int add(int a , int b , int c , int d , int e , int f , int g , int h , int i , int j ,
        int k , int l , int m ) 
{ 

  {
#line 19
  return ((((((((((((a + b) + c) + d) + e) + f) + g) + h) + i) + j) + k) + l) + m);
}
}
#line 22 "20010518-1.c"
int main(void) 
{ int tmp ;

  {
#line 24
  tmp = add(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13);
#line 24
  if (tmp != 91) {
#line 25
    abort();
  }
#line 27
  exit(0);
}
}
