/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20020413-1.c"
void test(long double val , int *eval ) 
{ long double tmp ;
  int i ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 4
  tmp = 1.0l;
#line 5
  i = 0;
#line 7
  if (val < 0.0l) {
#line 8
    val = - val;
  }
#line 10
  if (val >= tmp) {
#line 11
    while (tmp < val) {
#line 13
      tmp *= 2.0l;
#line 14
      tmp___0 = i;
#line 14
      i ++;
#line 14
      if (tmp___0 >= 10) {
#line 15
        abort();
      }
    }
  } else {
#line 17
    if (val != 0.0l) {
#line 18
      while (val < tmp) {
#line 20
        tmp /= 2.0l;
#line 21
        tmp___1 = i;
#line 21
        i ++;
#line 21
        if (tmp___1 >= 10) {
#line 22
          abort();
        }
      }
    }
  }
#line 25
  *eval = i;
#line 26
  return;
}
}
#line 28 "20020413-1.c"
int main(void) 
{ int eval ;

  {
#line 32
  test((long double )3.0, & eval);
#line 33
  test((long double )3.5, & eval);
#line 34
  test((long double )4.0, & eval);
#line 35
  test((long double )5.0, & eval);
#line 36
  exit(0);
}
}
