/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 4 "20020805-1.c"
extern void abort(void) ;
#line 5
extern void exit(int  ) ;
#line 7 "20020805-1.c"
void check(unsigned int m ) 
{ 

  {
#line 9
  if (m != 4294967295U) {
#line 10
    abort();
  }
#line 11
  return;
}
}
#line 13 "20020805-1.c"
unsigned int n  =    1U;
#line 15 "20020805-1.c"
int main(void) 
{ unsigned int m ;

  {
#line 18
  m = (1U | (2U - n)) | - n;
#line 19
  check(m);
#line 20
  exit(0);
}
}
