/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 7 "20020307-1.c"
void f3(long j ) 
{ 

  {
#line 7
  if (((unsigned long )j & ((1UL << 3) - 1UL)) >= (1UL << 2) + 2UL) {
#line 7
    abort();
  }
#line 7
  return;
}
}
#line 8 "20020307-1.c"
void f4(long j ) 
{ 

  {
#line 8
  if (((unsigned long )j & ((1UL << 4) - 1UL)) >= (1UL << 3) + 2UL) {
#line 8
    abort();
  }
#line 8
  return;
}
}
#line 9 "20020307-1.c"
void f5(long j ) 
{ 

  {
#line 9
  if (((unsigned long )j & ((1UL << 5) - 1UL)) >= (1UL << 4) + 2UL) {
#line 9
    abort();
  }
#line 9
  return;
}
}
#line 10 "20020307-1.c"
void f6(long j ) 
{ 

  {
#line 10
  if (((unsigned long )j & ((1UL << 6) - 1UL)) >= (1UL << 5) + 2UL) {
#line 10
    abort();
  }
#line 10
  return;
}
}
#line 11 "20020307-1.c"
void f7(long j ) 
{ 

  {
#line 11
  if (((unsigned long )j & ((1UL << 7) - 1UL)) >= (1UL << 6) + 2UL) {
#line 11
    abort();
  }
#line 11
  return;
}
}
#line 12 "20020307-1.c"
void f8(long j ) 
{ 

  {
#line 12
  if (((unsigned long )j & ((1UL << 8) - 1UL)) >= (1UL << 7) + 2UL) {
#line 12
    abort();
  }
#line 12
  return;
}
}
#line 13 "20020307-1.c"
void f9(long j ) 
{ 

  {
#line 13
  if (((unsigned long )j & ((1UL << 9) - 1UL)) >= (1UL << 8) + 2UL) {
#line 13
    abort();
  }
#line 13
  return;
}
}
#line 14 "20020307-1.c"
void f10(long j ) 
{ 

  {
#line 14
  if (((unsigned long )j & ((1UL << 10) - 1UL)) >= (1UL << 9) + 2UL) {
#line 14
    abort();
  }
#line 14
  return;
}
}
#line 15 "20020307-1.c"
void f11(long j ) 
{ 

  {
#line 15
  if (((unsigned long )j & ((1UL << 11) - 1UL)) >= (1UL << 10) + 2UL) {
#line 15
    abort();
  }
#line 15
  return;
}
}
#line 16 "20020307-1.c"
void f12(long j ) 
{ 

  {
#line 16
  if (((unsigned long )j & ((1UL << 12) - 1UL)) >= (1UL << 11) + 2UL) {
#line 16
    abort();
  }
#line 16
  return;
}
}
#line 17 "20020307-1.c"
void f13(long j ) 
{ 

  {
#line 17
  if (((unsigned long )j & ((1UL << 13) - 1UL)) >= (1UL << 12) + 2UL) {
#line 17
    abort();
  }
#line 17
  return;
}
}
#line 18 "20020307-1.c"
void f14(long j ) 
{ 

  {
#line 18
  if (((unsigned long )j & ((1UL << 14) - 1UL)) >= (1UL << 13) + 2UL) {
#line 18
    abort();
  }
#line 18
  return;
}
}
#line 19 "20020307-1.c"
void f15(long j ) 
{ 

  {
#line 19
  if (((unsigned long )j & ((1UL << 15) - 1UL)) >= (1UL << 14) + 2UL) {
#line 19
    abort();
  }
#line 19
  return;
}
}
#line 20 "20020307-1.c"
void f16(long j ) 
{ 

  {
#line 20
  if (((unsigned long )j & ((1UL << 16) - 1UL)) >= (1UL << 15) + 2UL) {
#line 20
    abort();
  }
#line 20
  return;
}
}
#line 21 "20020307-1.c"
void f17(long j ) 
{ 

  {
#line 21
  if (((unsigned long )j & ((1UL << 17) - 1UL)) >= (1UL << 16) + 2UL) {
#line 21
    abort();
  }
#line 21
  return;
}
}
#line 22 "20020307-1.c"
void f18(long j ) 
{ 

  {
#line 22
  if (((unsigned long )j & ((1UL << 18) - 1UL)) >= (1UL << 17) + 2UL) {
#line 22
    abort();
  }
#line 22
  return;
}
}
#line 23 "20020307-1.c"
void f19(long j ) 
{ 

  {
#line 23
  if (((unsigned long )j & ((1UL << 19) - 1UL)) >= (1UL << 18) + 2UL) {
#line 23
    abort();
  }
#line 23
  return;
}
}
#line 24 "20020307-1.c"
void f20(long j ) 
{ 

  {
#line 24
  if (((unsigned long )j & ((1UL << 20) - 1UL)) >= (1UL << 19) + 2UL) {
#line 24
    abort();
  }
#line 24
  return;
}
}
#line 25 "20020307-1.c"
void f21(long j ) 
{ 

  {
#line 25
  if (((unsigned long )j & ((1UL << 21) - 1UL)) >= (1UL << 20) + 2UL) {
#line 25
    abort();
  }
#line 25
  return;
}
}
#line 26 "20020307-1.c"
void f22(long j ) 
{ 

  {
#line 26
  if (((unsigned long )j & ((1UL << 22) - 1UL)) >= (1UL << 21) + 2UL) {
#line 26
    abort();
  }
#line 26
  return;
}
}
#line 27 "20020307-1.c"
void f23(long j ) 
{ 

  {
#line 27
  if (((unsigned long )j & ((1UL << 23) - 1UL)) >= (1UL << 22) + 2UL) {
#line 27
    abort();
  }
#line 27
  return;
}
}
#line 28 "20020307-1.c"
void f24(long j ) 
{ 

  {
#line 28
  if (((unsigned long )j & ((1UL << 24) - 1UL)) >= (1UL << 23) + 2UL) {
#line 28
    abort();
  }
#line 28
  return;
}
}
#line 29 "20020307-1.c"
void f25(long j ) 
{ 

  {
#line 29
  if (((unsigned long )j & ((1UL << 25) - 1UL)) >= (1UL << 24) + 2UL) {
#line 29
    abort();
  }
#line 29
  return;
}
}
#line 30 "20020307-1.c"
void f26(long j ) 
{ 

  {
#line 30
  if (((unsigned long )j & ((1UL << 26) - 1UL)) >= (1UL << 25) + 2UL) {
#line 30
    abort();
  }
#line 30
  return;
}
}
#line 31 "20020307-1.c"
void f27(long j ) 
{ 

  {
#line 31
  if (((unsigned long )j & ((1UL << 27) - 1UL)) >= (1UL << 26) + 2UL) {
#line 31
    abort();
  }
#line 31
  return;
}
}
#line 32 "20020307-1.c"
void f28(long j ) 
{ 

  {
#line 32
  if (((unsigned long )j & ((1UL << 28) - 1UL)) >= (1UL << 27) + 2UL) {
#line 32
    abort();
  }
#line 32
  return;
}
}
#line 33 "20020307-1.c"
void f29(long j ) 
{ 

  {
#line 33
  if (((unsigned long )j & ((1UL << 29) - 1UL)) >= (1UL << 28) + 2UL) {
#line 33
    abort();
  }
#line 33
  return;
}
}
#line 34 "20020307-1.c"
void f30(long j ) 
{ 

  {
#line 34
  if (((unsigned long )j & ((1UL << 30) - 1UL)) >= (1UL << 29) + 2UL) {
#line 34
    abort();
  }
#line 34
  return;
}
}
#line 35 "20020307-1.c"
void f31(long j ) 
{ 

  {
#line 35
  if (((unsigned long )j & ((1UL << 31) - 1UL)) >= (1UL << 30) + 2UL) {
#line 35
    abort();
  }
#line 35
  return;
}
}
#line 37 "20020307-1.c"
int main(void) 
{ 

  {
#line 39
  f3(0L);
#line 40
  f4(0L);
#line 41
  f5(0L);
#line 42
  f6(0L);
#line 43
  f7(0L);
#line 44
  f8(0L);
#line 45
  f9(0L);
#line 46
  f10(0L);
#line 47
  f11(0L);
#line 48
  f12(0L);
#line 49
  f13(0L);
#line 50
  f14(0L);
#line 51
  f15(0L);
#line 52
  f16(0L);
#line 53
  f17(0L);
#line 54
  f18(0L);
#line 55
  f19(0L);
#line 56
  f20(0L);
#line 57
  f21(0L);
#line 58
  f22(0L);
#line 59
  f23(0L);
#line 60
  f24(0L);
#line 61
  f25(0L);
#line 62
  f26(0L);
#line 63
  f27(0L);
#line 64
  f28(0L);
#line 65
  f29(0L);
#line 66
  f30(0L);
#line 67
  f31(0L);
#line 69
  exit(0);
}
}
