/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 1 "20020716-1.c"
extern void abort(void) ;
#line 2
extern void exit(int  ) ;
#line 4 "20020716-1.c"
int sub1(int val ) 
{ 

  {
#line 6
  return (val);
}
}
#line 9 "20020716-1.c"
int testcond(int val ) 
{ int flag1 ;
  int t1 ;
  int t2 ;
  int tmp ;

  {
#line 14
  t1 = val;
#line 16
  t2 = t1;
#line 18
  tmp = sub1(t2);
#line 18
  flag1 = tmp == 0;
  goto lab1;
  lab1: ;
#line 25
  if (flag1 != 0) {
#line 26
    return (5046272);
  } else {
#line 28
    return (0);
  }
}
}
#line 31 "20020716-1.c"
int main(void) 
{ int tmp ;

  {
#line 33
  tmp = testcond(1);
#line 33
  if (tmp) {
#line 34
    abort();
  }
#line 35
  exit(0);
}
}
