/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 10 "20020406-1.c"
typedef unsigned int FFelem;
#line 18 "20020406-1.c"
struct DUPFFstruct {
   int maxdeg ;
   int deg ;
   FFelem *coeffs ;
};
#line 25 "20020406-1.c"
typedef struct DUPFFstruct *DUPFF;
#line 26 "../../lib/includes/stdio.h"
extern int printf(char const   * __restrict  format  , ...) ;
#line 13 "../../lib/includes/stdlib.h"
extern void *malloc(unsigned int size ) ;
#line 16
extern void *calloc(unsigned int nelem , unsigned int elsize ) ;
#line 21
extern void abort(void) ;
#line 12 "20020406-1.c"
FFelem FFmul(FFelem x , FFelem y ) 
{ 

  {
#line 14
  return (x);
}
}
#line 28 "20020406-1.c"
int DUPFFdeg(DUPFF f ) 
{ 

  {
#line 30
  return (f->deg);
}
}
#line 34 "20020406-1.c"
DUPFF DUPFFnew(int maxdeg ) 
{ DUPFF ans ;
  void *tmp ;
  void *tmp___0 ;

  {
#line 36
  tmp = malloc((unsigned int )sizeof(struct DUPFFstruct ));
#line 36
  ans = (struct DUPFFstruct *)tmp;
#line 37
  ans->coeffs = (FFelem *)0;
#line 38
  if (maxdeg >= 0) {
#line 38
    tmp___0 = calloc((unsigned int )(maxdeg + 1), (unsigned int )sizeof(FFelem ));
#line 38
    ans->coeffs = (FFelem *)tmp___0;
  }
#line 39
  ans->maxdeg = maxdeg;
#line 40
  ans->deg = -1;
#line 41
  return (ans);
}
}
#line 44 "20020406-1.c"
void DUPFFfree(DUPFF x ) 
{ 

  {
#line 46
  return;
}
}
#line 48 "20020406-1.c"
void DUPFFswap(DUPFF x , DUPFF y ) 
{ 

  {
#line 50
  return;
}
}
#line 53 "20020406-1.c"
DUPFF DUPFFcopy(DUPFF x ) 
{ 

  {
#line 55
  return (x);
}
}
#line 59 "20020406-1.c"
void DUPFFshift_add(DUPFF f , DUPFF g , int deg , FFelem coeff ) 
{ 

  {
#line 61
  return;
}
}
#line 64 "20020406-1.c"
DUPFF DUPFFexgcd(DUPFF *fcofac , DUPFF *gcofac , DUPFF f , DUPFF g ) 
{ DUPFF u ;
  DUPFF v ;
  DUPFF uf ;
  DUPFF ug ;
  DUPFF vf ;
  DUPFF vg ;
  FFelem q ;
  FFelem lcu ;
  FFelem lcvrecip ;
  FFelem p ;
  int df ;
  int dg ;
  int du ;
  int dv ;
  int tmp ;
  int tmp___0 ;
  DUPFF tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;

  {
#line 70
  tmp = DUPFFdeg(g);
#line 70
  tmp___0 = DUPFFdeg(f);
#line 70
  printf((char const   * __restrict  )"DUPFFexgcd called on degrees %d and %d\n",
         tmp___0, tmp);
#line 71
  tmp___2 = DUPFFdeg(f);
#line 71
  tmp___3 = DUPFFdeg(g);
#line 71
  if (tmp___2 < tmp___3) {
#line 71
    tmp___1 = DUPFFexgcd(gcofac, fcofac, g, f);
#line 71
    return (tmp___1);
  }
#line 72
  tmp___4 = DUPFFdeg(f);
#line 72
  if (tmp___4 != 2) {
#line 72
    abort();
  } else {
#line 72
    tmp___5 = DUPFFdeg(g);
#line 72
    if (tmp___5 != 1) {
#line 72
      abort();
    }
  }
#line 73
  if (*(f->coeffs + 0) == 0U) {
#line 73
    return (f);
  }
#line 75
  p = 2U;
#line 77
  df = DUPFFdeg(f);
#line 77
  if (df < 0) {
#line 77
    df = 0;
  }
#line 78
  dg = DUPFFdeg(g);
#line 78
  if (dg < 0) {
#line 78
    dg = 0;
  }
#line 79
  u = DUPFFcopy(f);
#line 80
  v = DUPFFcopy(g);
#line 82
  uf = DUPFFnew(dg);
#line 82
  *(uf->coeffs + 0) = 1U;
#line 82
  uf->deg = 0;
#line 83
  ug = DUPFFnew(df);
#line 84
  vf = DUPFFnew(dg);
#line 85
  vg = DUPFFnew(df);
#line 85
  *(vg->coeffs + 0) = 1U;
#line 85
  vg->deg = 0;
#line 87
  while (1) {
#line 87
    tmp___7 = DUPFFdeg(v);
#line 87
    if (! (tmp___7 > 0)) {
#line 87
      break;
    }
#line 89
    dv = DUPFFdeg(v);
#line 90
    lcvrecip = FFmul(1U, *(v->coeffs + dv));
#line 91
    while (1) {
#line 91
      tmp___6 = DUPFFdeg(u);
#line 91
      if (! (tmp___6 >= dv)) {
#line 91
        break;
      }
#line 93
      du = DUPFFdeg(u);
#line 94
      lcu = *(u->coeffs + du);
#line 95
      q = FFmul(lcu, lcvrecip);
#line 96
      DUPFFshift_add(u, v, du - dv, p - q);
#line 97
      DUPFFshift_add(uf, vf, du - dv, p - q);
#line 98
      DUPFFshift_add(ug, vg, du - dv, p - q);
    }
#line 100
    DUPFFswap(u, v);
#line 101
    DUPFFswap(uf, vf);
#line 102
    DUPFFswap(ug, vg);
  }
#line 104
  tmp___8 = DUPFFdeg(v);
#line 104
  if (tmp___8 == 0) {
#line 106
    DUPFFswap(u, v);
#line 107
    DUPFFswap(uf, vf);
#line 108
    DUPFFswap(ug, vg);
  }
#line 110
  DUPFFfree(vf);
#line 111
  DUPFFfree(vg);
#line 112
  DUPFFfree(v);
#line 113
  *fcofac = uf;
#line 114
  *gcofac = ug;
#line 115
  return (u);
}
}
#line 120 "20020406-1.c"
int main(void) 
{ DUPFF f ;
  DUPFF g ;
  DUPFF cf ;
  DUPFF cg ;
  DUPFF h ;
  int tmp ;
  int tmp___0 ;

  {
#line 123
  f = DUPFFnew(1);
#line 123
  *(f->coeffs + 1) = 1U;
#line 123
  f->deg = 1;
#line 124
  g = DUPFFnew(2);
#line 124
  *(g->coeffs + 2) = 1U;
#line 124
  g->deg = 2;
#line 126
  tmp = DUPFFdeg(g);
#line 126
  tmp___0 = DUPFFdeg(f);
#line 126
  printf((char const   * __restrict  )"calling DUPFFexgcd on degrees %d and %d\n",
         tmp___0, tmp);
#line 127
  h = DUPFFexgcd(& cf, & cg, f, g);
#line 128
  return (0);
}
}
