/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern void abort(void) ;
extern void exit(int  ) ;
unsigned char cx  =    (unsigned char)7;
unsigned short sx  =    (unsigned short)14;
unsigned int ix  =    21U;
unsigned long lx  =    28UL;
unsigned long long Lx  =    35ULL;
int main(void) 
{ unsigned char cy ;
  unsigned short sy ;
  unsigned int iy ;
  unsigned long ly ;
  unsigned long long Ly ;

  {
  cy = (unsigned char )((int )cx / 6);
  if ((int )cy != 1) {
    abort();
  }
  cy = (unsigned char )((int )cx % 6);
  if ((int )cy != 1) {
    abort();
  }
  sy = (unsigned short )((int )sx / 6);
  if ((int )sy != 2) {
    abort();
  }
  sy = (unsigned short )((int )sx % 6);
  if ((int )sy != 2) {
    abort();
  }
  iy = ix / 6U;
  if (iy != 3U) {
    abort();
  }
  iy = ix % 6U;
  if (iy != 3U) {
    abort();
  }
  ly = lx / 6UL;
  if (ly != 4UL) {
    abort();
  }
  ly = lx % 6UL;
  if (ly != 4UL) {
    abort();
  }
  Ly = Lx / 6ULL;
  if (Ly != 5ULL) {
    abort();
  }
  Ly = Lx % 6ULL;
  if (Ly != 5ULL) {
    abort();
  }
  exit(0);
}
}
