/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20021120-2.c"
int g1  ;
#line 2 "20021120-2.c"
int g2  ;
#line 4 "20021120-2.c"
void foo(int x ) 
{ int y ;

  {
#line 8
  if (x) {
#line 9
    y = 793;
  } else {
#line 11
    y = 793;
  }
#line 12
  g1 = 7930 / y;
#line 13
  g2 = 7930 / x;
#line 14
  return;
}
}
#line 16 "20021120-2.c"
int main(void) 
{ 

  {
#line 18
  foo(793);
#line 19
  if (g1 != 10) {
#line 20
    abort();
  } else {
#line 19
    if (g2 != 10) {
#line 20
      abort();
    }
  }
#line 21
  exit(0);
}
}
