/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 22 "20020508-1.c"
unsigned char uc  =    (unsigned char)52;
#line 23 "20020508-1.c"
unsigned short us  =    (unsigned short)62004;
#line 24 "20020508-1.c"
unsigned int ui  =    62004U;
#line 25 "20020508-1.c"
unsigned long ul  =    4063516280UL;
#line 26 "20020508-1.c"
unsigned long long ull  =    1090791845765373680ULL;
#line 27 "20020508-1.c"
int shift1  =    4;
#line 28 "20020508-1.c"
int shift2  =    (int )(sizeof(long long ) * 8UL - 4UL);
#line 30 "20020508-1.c"
int main(void) 
{ 

  {
#line 32
  if ((((int )uc >> shift1) | ((int )uc << (sizeof(uc) * 8UL - (unsigned long )shift1))) != ((52 >> 4) | (52 << (sizeof((unsigned char)52) * 8UL - 4UL)))) {
#line 33
    abort();
  }
#line 35
  if ((((int )uc >> 4) | ((int )uc << (sizeof(uc) * 8UL - 4UL))) != ((52 >> 4) | (52 << (sizeof((unsigned char)52) * 8UL - 4UL)))) {
#line 36
    abort();
  }
#line 38
  if ((((int )us >> shift1) | ((int )us << (sizeof(us) * 8UL - (unsigned long )shift1))) != ((62004 >> 4) | (62004 << (sizeof((unsigned short)62004) * 8UL - 4UL)))) {
#line 39
    abort();
  }
#line 41
  if ((((int )us >> 4) | ((int )us << (sizeof(us) * 8UL - 4UL))) != ((62004 >> 4) | (62004 << (sizeof((unsigned short)62004) * 8UL - 4UL)))) {
#line 42
    abort();
  }
#line 44
  if (((ui >> shift1) | (ui << (sizeof(ui) * 8UL - (unsigned long )shift1))) != ((62004U >> 4) | (62004U << (sizeof(62004U) * 8UL - 4UL)))) {
#line 45
    abort();
  }
#line 47
  if (((ui >> 4) | (ui << (sizeof(ui) * 8UL - 4UL))) != ((62004U >> 4) | (62004U << (sizeof(62004U) * 8UL - 4UL)))) {
#line 48
    abort();
  }
#line 50
  if (((ul >> shift1) | (ul << (sizeof(ul) * 8UL - (unsigned long )shift1))) != ((4063516280UL >> 4) | (4063516280UL << (sizeof(4063516280UL) * 8UL - 4UL)))) {
#line 51
    abort();
  }
#line 53
  if (((ul >> 4) | (ul << (sizeof(ul) * 8UL - 4UL))) != ((4063516280UL >> 4) | (4063516280UL << (sizeof(4063516280UL) * 8UL - 4UL)))) {
#line 54
    abort();
  }
#line 56
  if (((ull >> shift1) | (ull << (sizeof(ull) * 8UL - (unsigned long )shift1))) != ((1090791845765373680ULL >> 4) | (1090791845765373680ULL << (sizeof(1090791845765373680ULL) * 8UL - 4UL)))) {
#line 57
    abort();
  }
#line 59
  if (((ull >> 4) | (ull << (sizeof(ull) * 8UL - 4UL))) != ((1090791845765373680ULL >> 4) | (1090791845765373680ULL << (sizeof(1090791845765373680ULL) * 8UL - 4UL)))) {
#line 60
    abort();
  }
#line 62
  if (((ull >> shift2) | (ull << (sizeof(ull) * 8UL - (unsigned long )shift2))) != ((1090791845765373680ULL >> (sizeof(long long ) * 8UL - 4UL)) | (1090791845765373680ULL << (sizeof(1090791845765373680ULL) * 8UL - (sizeof(long long ) * 8UL - 4UL))))) {
#line 63
    abort();
  }
#line 65
  if (((ull >> (sizeof(long long ) * 8UL - 4UL)) | (ull << (sizeof(ull) * 8UL - (sizeof(long long ) * 8UL - 4UL)))) != ((1090791845765373680ULL >> (sizeof(long long ) * 8UL - 4UL)) | (1090791845765373680ULL << (sizeof(1090791845765373680ULL) * 8UL - (sizeof(long long ) * 8UL - 4UL))))) {
#line 66
    abort();
  }
#line 68
  if ((((int )uc << shift1) | ((int )uc >> (sizeof(uc) * 8UL - (unsigned long )shift1))) != ((52 << 4) | (52 >> (sizeof((unsigned char)52) * 8UL - 4UL)))) {
#line 69
    abort();
  }
#line 71
  if ((((int )uc << 4) | ((int )uc >> (sizeof(uc) * 8UL - 4UL))) != ((52 << 4) | (52 >> (sizeof((unsigned char)52) * 8UL - 4UL)))) {
#line 72
    abort();
  }
#line 74
  if ((((int )us << shift1) | ((int )us >> (sizeof(us) * 8UL - (unsigned long )shift1))) != ((62004 << 4) | (62004 >> (sizeof((unsigned short)62004) * 8UL - 4UL)))) {
#line 75
    abort();
  }
#line 77
  if ((((int )us << 4) | ((int )us >> (sizeof(us) * 8UL - 4UL))) != ((62004 << 4) | (62004 >> (sizeof((unsigned short)62004) * 8UL - 4UL)))) {
#line 78
    abort();
  }
#line 80
  if (((ui << shift1) | (ui >> (sizeof(ui) * 8UL - (unsigned long )shift1))) != ((62004U << 4) | (62004U >> (sizeof(62004U) * 8UL - 4UL)))) {
#line 81
    abort();
  }
#line 83
  if (((ui << 4) | (ui >> (sizeof(ui) * 8UL - 4UL))) != ((62004U << 4) | (62004U >> (sizeof(62004U) * 8UL - 4UL)))) {
#line 84
    abort();
  }
#line 86
  if (((ul << shift1) | (ul >> (sizeof(ul) * 8UL - (unsigned long )shift1))) != ((4063516280UL << 4) | (4063516280UL >> (sizeof(4063516280UL) * 8UL - 4UL)))) {
#line 87
    abort();
  }
#line 89
  if (((ul << 4) | (ul >> (sizeof(ul) * 8UL - 4UL))) != ((4063516280UL << 4) | (4063516280UL >> (sizeof(4063516280UL) * 8UL - 4UL)))) {
#line 90
    abort();
  }
#line 92
  if (((ull << shift1) | (ull >> (sizeof(ull) * 8UL - (unsigned long )shift1))) != ((1090791845765373680ULL << 4) | (1090791845765373680ULL >> (sizeof(1090791845765373680ULL) * 8UL - 4UL)))) {
#line 93
    abort();
  }
#line 95
  if (((ull << 4) | (ull >> (sizeof(ull) * 8UL - 4UL))) != ((1090791845765373680ULL << 4) | (1090791845765373680ULL >> (sizeof(1090791845765373680ULL) * 8UL - 4UL)))) {
#line 96
    abort();
  }
#line 98
  if (((ull << shift2) | (ull >> (sizeof(ull) * 8UL - (unsigned long )shift2))) != ((1090791845765373680ULL << (sizeof(long long ) * 8UL - 4UL)) | (1090791845765373680ULL >> (sizeof(1090791845765373680ULL) * 8UL - (sizeof(long long ) * 8UL - 4UL))))) {
#line 99
    abort();
  }
#line 101
  if (((ull << (sizeof(long long ) * 8UL - 4UL)) | (ull >> (sizeof(ull) * 8UL - (sizeof(long long ) * 8UL - 4UL)))) != ((1090791845765373680ULL << (sizeof(long long ) * 8UL - 4UL)) | (1090791845765373680ULL >> (sizeof(1090791845765373680ULL) * 8UL - (sizeof(long long ) * 8UL - 4UL))))) {
#line 102
    abort();
  }
#line 104
  exit(0);
}
}
