/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern void abort() ;
extern void exit(int  ) ;
signed char c  =    (signed char)-1;
int foo(void) 
{ 

  {
  return ((int )((unsigned short )c) ^ -103);
}
}
int main(void) 
{ int tmp ;

  {
  if (sizeof(short ) != 2UL) {
    exit(0);
  } else {
    if (sizeof(int ) != 4UL) {
      exit(0);
    }
  }
  tmp = foo();
  if (tmp != -65434) {
    abort();
  }
  exit(0);
}
}
