/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20020819-1.c"
int foo(void) 
{ 

  {
#line 4
  return (0);
}
}
#line 7 "20020819-1.c"
int main(void) 
{ int i ;
  int j ;
  int k ;
  int ccp_bad ;
  int tmp ;

  {
#line 9
  ccp_bad = 0;
#line 11
  i = 0;
#line 11
  while (i < 10) {
#line 13
    j = 0;
#line 13
    while (j < 10) {
#line 14
      tmp = foo();
#line 14
      if (tmp) {
#line 15
        ccp_bad = 1;
      }
#line 13
      j ++;
    }
#line 17
    k = ccp_bad != 0;
#line 18
    if (k) {
#line 19
      abort();
    }
#line 11
    i ++;
  }
#line 22
  exit(0);
}
}
