/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern void abort() ;
extern void exit(int  ) ;
int main(void) 
{ int listElem[4] ;
  int listSmall[2] ;
  int i ;
  int j ;
  int posGreatest ;
  int greatest ;

  {
  listElem[0] = 30;
  listElem[1] = 2;
  listElem[2] = 10;
  listElem[3] = 5;
  posGreatest = -1;
  greatest = -1;
  i = 0;
  while (i < 2) {
    listSmall[i] = listElem[i];
    if (listElem[i] > greatest) {
      posGreatest = i;
      greatest = listElem[i];
    }
    i ++;
  }
  i = 2;
  while (i < 4) {
    if (listElem[i] < greatest) {
      listSmall[posGreatest] = listElem[i];
      posGreatest = 0;
      greatest = listSmall[0];
      j = 1;
      while (j < 2) {
        if (listSmall[j] > greatest) {
          posGreatest = j;
          greatest = listSmall[j];
        }
        j ++;
      }
    }
    i ++;
  }
  if (listSmall[0] != 5) {
    abort();
  } else {
    if (listSmall[1] != 2) {
      abort();
    }
  }
  exit(0);
}
}
