/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20020328-1.c"
int b  =    0;
#line 4 "20020328-1.c"
void func(void) 
{ 

  {
#line 4
  return;
}
}
#line 6 "20020328-1.c"
void testit(int x ) 
{ 

  {
#line 9
  if (x != 20) {
#line 10
    abort();
  }
#line 11
  return;
}
}
#line 13 "20020328-1.c"
int main(void) 
{ int a ;

  {
#line 16
  a = 0;
#line 18
  if (b) {
#line 19
    func();
  }
#line 23
  testit((int )((unsigned int )(a + 23) & 4294967292U));
#line 24
  exit(0);
}
}
