/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 3 "20021024-1.c"
extern void exit(int  ) ;
#line 4
extern void abort(void) ;
#line 6 "20021024-1.c"
unsigned long long *cp  ;
#line 6 "20021024-1.c"
unsigned long long m  ;
#line 8 "20021024-1.c"
void foo(void) 
{ 

  {
#line 10
  return;
}
}
#line 12 "20021024-1.c"
void bar(unsigned int rop , unsigned long long *r ) 
{ unsigned int rs1 ;
  unsigned int rs2 ;
  unsigned int rd ;

  {
  top: 
#line 17
  rs2 = (rop >> 23) & 511U;
#line 18
  rs1 = (rop >> 9) & 511U;
#line 19
  rd = rop & 511U;
#line 21
  *cp = 1ULL;
#line 22
  m = *(r + rs1) + *(r + rs2);
#line 23
  *cp = 2ULL;
#line 24
  foo();
#line 25
  if (! rd) {
    goto top;
  }
#line 27
  *(r + rd) = 1ULL;
#line 28
  return;
}
}
#line 32 "20021024-1.c"
static unsigned long long r[64]  ;
#line 30 "20021024-1.c"
int main(void) 
{ unsigned long long cr ;

  {
#line 34
  cp = & cr;
#line 36
  r[4] = 47ULL;
#line 37
  r[8] = 11ULL;
#line 38
  bar((unsigned int )(((8 << 23) | (4 << 9)) | 15), r);
#line 40
  if (m != 58ULL) {
#line 41
    abort();
  }
#line 42
  exit(0);
}
}
