/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct A {
   float a1 ;
   int a2 ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int bar(float x ) ;
struct A a  ;
int b  ;
void foo(void) 
{ 

  {
  a.a2 = bar(a.a1);
  if (a.a2 < b - 1) {
    a.a2 = a.a2;
  } else {
    a.a2 = b - 1;
  }
  if (a.a2 >= b - 1) {
    abort();
  }
  return;
}
}
int bar(float x ) 
{ 

  {
  return (2241);
}
}
int main(void) 
{ 

  {
  a.a1 = 1.0f;
  b = 3384;
  foo();
  return (0);
}
}
