/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
void get_addrs(char const   **x , int *y ) 
{ 

  {
  *(x + 0) = "a1111" + (*(y + 0) - 65536) * 2;
  *(x + 1) = "a1112" + (*(y + 1) - 131072) * 2;
  *(x + 2) = "a1113" + (*(y + 2) - 196608) * 2;
  *(x + 3) = "a1114" + (*(y + 3) - 262144) * 2;
  *(x + 4) = "a1115" + (*(y + 4) - 327680) * 2;
  *(x + 5) = "a1116" + (*(y + 5) - 393216) * 2;
  *(x + 6) = "a1117" + (*(y + 6) - 458752) * 2;
  *(x + 7) = "a1118" + (*(y + 7) - 524288) * 2;
  return;
}
}
int main(void) 
{ char const   *x[8] ;
  int y[8] ;
  int i ;

  {
  i = 0;
  while (i < 8) {
    y[i] = 65536 * (i + 1);
    i ++;
  }
  get_addrs(x, y);
  i = 0;
  while (i < 8) {
    if ((int const   )*(x[i]) != 97) {
      abort();
    }
    i ++;
  }
  exit(0);
}
}
