/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "20031211-1.c"
struct a {
   unsigned int bitfield : 1 ;
};
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 4 "20031211-1.c"
unsigned int x  ;
#line 6 "20031211-1.c"
int main(void) 
{ struct a a ;

  {
#line 8
  a.bitfield = 0U;
#line 9
  x = 48879U;
#line 10
  a.bitfield |= x;
#line 11
  if (a.bitfield != 1U) {
#line 12
    abort();
  }
#line 13
  exit(0);
}
}
