/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 7 "20030916-1.c"
void f(unsigned int *x ) 
{ unsigned char i ;
  int j ;

  {
#line 12
  i = (unsigned char)16;
#line 13
  j = 0;
#line 13
  while (j < 16) {
#line 15
    i = (unsigned char )((int )i + 232);
#line 16
    *(x + i) = 0U;
#line 17
    i = (unsigned char )((int )i - 231);
#line 13
    j ++;
  }
#line 19
  return;
}
}
#line 21 "20030916-1.c"
int main(void) 
{ unsigned int x[256] ;
  int i ;
  int tmp ;

  {
#line 26
  i = 0;
#line 26
  while (i < 256) {
#line 27
    x[i] = 1U;
#line 26
    i ++;
  }
#line 28
  f(x);
#line 29
  i = 0;
#line 29
  while (i < 256) {
#line 30
    if (i >= 8) {
#line 30
      if (i < 248) {
#line 30
        tmp = 1;
      } else {
#line 30
        tmp = 0;
      }
    } else {
#line 30
      tmp = 0;
    }
#line 30
    if (x[i] != (unsigned int )tmp) {
#line 31
      abort();
    }
#line 29
    i ++;
  }
#line 32
  exit(0);
}
}
