/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
double ( __attribute__((__noinline__)) sin)(double a ) ;
double ( __attribute__((__noinline__)) floor)(double a ) ;
float t(float a ) 
{ double tmp ;

  {
  tmp = sin((double )a);
  return ((float )tmp);
}
}
float q(float a ) 
{ double tmp ;

  {
  tmp = floor((double )a);
  return ((float )tmp);
}
}
double q1(float a ) 
{ double tmp ;

  {
  tmp = floor((double )a);
  return (tmp);
}
}
int main(void) 
{ 

  {
  return (0);
}
}
double ( __attribute__((__noinline__)) floor)(double a ) 
{ 

  {
  abort();
}
}
float ( __attribute__((__noinline__)) floorf)(float a ) 
{ 

  {
  return (a);
}
}
double ( __attribute__((__noinline__)) sin)(double a ) 
{ 

  {
  abort();
}
}
float ( __attribute__((__noinline__)) sinf)(float a ) 
{ 

  {
  return (a);
}
}
