/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct A {
   unsigned long p ;
   unsigned long q ;
   unsigned long r ;
   unsigned long s ;
};
struct A x  =    {13UL, 14UL, 15UL, 16UL};
extern void abort(void) ;
extern void exit(int  ) ;
__inline static struct A *bar(void) 
{ struct A *r ;

  {
  switch (8) {
  case 2: 
  abort();
  break;
  case 8: 
  r = & x;
  break;
  default: 
  abort();
  break;
  }
  return (r);
}
}
void foo(unsigned long *x___0 , int y ) 
{ 

  {
  if (y != 12) {
    abort();
  }
  if (*(x___0 + 0) != 1UL) {
    abort();
  } else {
    if (*(x___0 + 1) != 11UL) {
      abort();
    }
  }
  if (*(x___0 + 2) != 2UL) {
    abort();
  } else {
    if (*(x___0 + 3) != 12UL) {
      abort();
    }
  }
  if (*(x___0 + 4) != 3UL) {
    abort();
  } else {
    if (*(x___0 + 5) != 13UL) {
      abort();
    }
  }
  if (*(x___0 + 6) != 4UL) {
    abort();
  } else {
    if (*(x___0 + 7) != 14UL) {
      abort();
    }
  }
  if (*(x___0 + 8) != 5UL) {
    abort();
  } else {
    if (*(x___0 + 9) != 15UL) {
      abort();
    }
  }
  if (*(x___0 + 10) != 6UL) {
    abort();
  } else {
    if (*(x___0 + 11) != 16UL) {
      abort();
    }
  }
  return;
}
}
int main(void) 
{ unsigned long a[40] ;
  int b ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  struct A *tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  struct A *tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;
  struct A *tmp___11 ;
  int tmp___12 ;
  int tmp___13 ;
  struct A *tmp___14 ;

  {
  b = 0;
  tmp = b;
  b ++;
  a[tmp] = 1UL;
  tmp___0 = b;
  b ++;
  a[tmp___0] = 11UL;
  tmp___1 = b;
  b ++;
  a[tmp___1] = 2UL;
  tmp___2 = b;
  b ++;
  a[tmp___2] = 12UL;
  tmp___3 = b;
  b ++;
  a[tmp___3] = 3UL;
  tmp___4 = b;
  b ++;
  tmp___5 = bar();
  a[tmp___4] = tmp___5->p;
  tmp___6 = b;
  b ++;
  a[tmp___6] = 4UL;
  tmp___7 = b;
  b ++;
  tmp___8 = bar();
  a[tmp___7] = tmp___8->q;
  tmp___9 = b;
  b ++;
  a[tmp___9] = 5UL;
  tmp___10 = b;
  b ++;
  tmp___11 = bar();
  a[tmp___10] = tmp___11->r;
  tmp___12 = b;
  b ++;
  a[tmp___12] = 6UL;
  tmp___13 = b;
  b ++;
  tmp___14 = bar();
  a[tmp___13] = tmp___14->s;
  foo(a, b);
  exit(0);
}
}
