/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct a {
   unsigned int bitfield : 1 ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
unsigned int x  ;
int main(void) 
{ struct a a ;

  {
  a.bitfield = 0U;
  x = 48879U;
  a.bitfield |= x;
  if (a.bitfield != 1U) {
    abort();
  }
  exit(0);
}
}
