/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
void ( __attribute__((__noinline__)) foo)(long x ) 
{ 

  {
  if (x >= 1024L) {
    abort();
  }
  return;
}
}
int main(void) 
{ 

  {
  foo((-0x7FFFFFFFFFFFFFFF-1));
  foo(-9223372036854765808L);
  return (0);
}
}
