/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern void abort() ;
extern void exit(int  ) ;
short *q  ;
long foo(short *p ) 
{ long b ;

  {
  b = (long )*p;
  q = p + 1;
  return (b);
}
}
int main(void) 
{ short a ;
  long tmp ;

  {
  a = (short)-256;
  tmp = foo(& a);
  if (tmp != -256L) {
    abort();
  }
  exit(0);
}
}
