/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "20031010-1.c"
long ( __attribute__((__noinline__)) foo)(long ct , long cf , _Bool p1 , _Bool p2 ,
                                          _Bool p3 ) 
{ long diff ;
  long tmp ;

  {
#line 9
  diff = ct - cf;
#line 11
  if (p1) {
#line 13
    if (p2) {
#line 15
      if (p3) {
#line 17
        tmp = ct;
#line 18
        ct = cf;
#line 19
        cf = tmp;
      }
#line 21
      diff = ct - cf;
    }
#line 24
    return (diff);
  }
#line 27
  abort();
#line 28
  return (0L);
}
}
#line 30 "20031010-1.c"
int main(void) 
{ long tmp ;

  {
#line 32
  tmp = foo(2L, 3L, (_Bool)1, (_Bool)1, (_Bool)1);
#line 32
  if (tmp == 0L) {
#line 33
    abort();
  }
#line 34
  return (0);
}
}
