/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern int strcmp(char const   * , char const   * ) ;
int ap_standalone  ;
char const   *ap_check_cmd_context(void *a , int b ) 
{ 

  {
  return ((char const   *)0);
}
}
char const   *server_type(void *a , void *b , char *arg ) 
{ char const   *err ;
  char const   *tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
  tmp = ap_check_cmd_context(a, 31);
  err = tmp;
  if (err) {
    return (err);
  }
  tmp___1 = strcmp((char const   *)arg, "inetd");
  if (tmp___1) {
    tmp___0 = strcmp((char const   *)arg, "standalone");
    if (tmp___0) {
      return ("ServerType must be either \'inetd\' or \'standalone\'");
    } else {
      ap_standalone = 1;
    }
  } else {
    ap_standalone = 0;
  }
  return ((char const   *)0);
}
}
int main(void) 
{ 

  {
  server_type((void *)0, (void *)0, (char *)"standalone");
  return (0);
}
}
