/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int foo(int x ) 
{ 

  {
  if ((int )((unsigned int )x & 2164260863U) != -2147418114) {
    abort();
  }
  return (0);
}
}
int main(void) 
{ int tmp ;

  {
  tmp = foo(-2147418114);
  return (tmp);
}
}
