/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 6 "20030120-2.c"
int foo(int status ) 
{ int s ;

  {
#line 8
  s = 0;
#line 9
  if (status == 1) {
#line 9
    s = 1;
  }
#line 10
  if (status == 3) {
#line 10
    s = 3;
  }
#line 11
  if (status == 4) {
#line 11
    s = 4;
  }
#line 12
  return (s);
}
}
#line 15 "20030120-2.c"
int main(void) 
{ int tmp ;

  {
#line 17
  tmp = foo(3);
#line 17
  if (tmp != 3) {
#line 18
    abort();
  }
#line 19
  return (0);
}
}
