/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 9 "20031011-1.c"
int main(void) 
{ int ll_bitsize ;
  int ll_bitpos ;
  int rl_bitsize ;
  int rl_bitpos ;
  int end_bit ;

  {
#line 15
  ll_bitpos = 32;
#line 15
  ll_bitsize = 32;
#line 16
  rl_bitpos = 0;
#line 16
  rl_bitsize = 32;
#line 18
  if (ll_bitpos + ll_bitsize > rl_bitpos + rl_bitsize) {
#line 18
    end_bit = ll_bitpos + ll_bitsize;
  } else {
#line 18
    end_bit = rl_bitpos + rl_bitsize;
  }
#line 19
  if (end_bit != 64) {
#line 20
    abort();
  }
#line 21
  if (rl_bitpos + rl_bitsize > ll_bitpos + ll_bitsize) {
#line 21
    end_bit = rl_bitpos + rl_bitsize;
  } else {
#line 21
    end_bit = ll_bitpos + ll_bitsize;
  }
#line 22
  if (end_bit != 64) {
#line 23
    abort();
  }
#line 24
  if (ll_bitpos + ll_bitsize < rl_bitpos + rl_bitsize) {
#line 24
    end_bit = ll_bitpos + ll_bitsize;
  } else {
#line 24
    end_bit = rl_bitpos + rl_bitsize;
  }
#line 25
  if (end_bit != 32) {
#line 26
    abort();
  }
#line 27
  if (rl_bitpos + rl_bitsize < ll_bitpos + ll_bitsize) {
#line 27
    end_bit = rl_bitpos + rl_bitsize;
  } else {
#line 27
    end_bit = ll_bitpos + ll_bitsize;
  }
#line 28
  if (end_bit != 32) {
#line 29
    abort();
  }
#line 30
  return (0);
}
}
