/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 6 "20041210-1.c"
int x[4]  = {      -1073741824,      2147483647,      2,      4};
#line 8 "20041210-1.c"
int main(void) 
{ 

  {
#line 10
  if (x[0] < x[1]) {
#line 11
    if ((x[2] & x[3]) < 0) {
#line 12
      abort();
    }
  }
#line 13
  exit(0);
}
}
