/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef unsigned long long ull;
extern void exit(int status ) ;
extern void abort(void) ;
int volatile   gvol[32]  ;
ull gull  ;
ull ( __attribute__((__noinline__)) t1)(int n , ull x ) 
{ int x1 ;
  int x2 ;
  int x3 ;
  int x4 ;
  int x5 ;
  int x6 ;
  int x7 ;
  int x8 ;
  int x9 ;
  int x10 ;
  int x11 ;
  int x12 ;
  int x13 ;
  int x14 ;
  int x15 ;
  int x16 ;
  int x17 ;
  int x18 ;
  int x19 ;
  int x20 ;
  int x21 ;
  int x22 ;
  int x23 ;
  int x24 ;
  int x25 ;
  int x26 ;
  int x27 ;
  int x28 ;
  int x29 ;
  int x30 ;
  int tmp ;

  {
  while (1) {
    tmp = n;
    n --;
    if (! tmp) {
      break;
    }
    x1 = (int )gvol[1];
    x2 = (int )gvol[2];
    x3 = (int )gvol[3];
    x4 = (int )gvol[4];
    x5 = (int )gvol[5];
    x6 = (int )gvol[6];
    x7 = (int )gvol[7];
    x8 = (int )gvol[8];
    x9 = (int )gvol[9];
    x10 = (int )gvol[10];
    x11 = (int )gvol[11];
    x12 = (int )gvol[12];
    x13 = (int )gvol[13];
    x14 = (int )gvol[14];
    x15 = (int )gvol[15];
    x16 = (int )gvol[16];
    x17 = (int )gvol[17];
    x18 = (int )gvol[18];
    x19 = (int )gvol[19];
    x20 = (int )gvol[20];
    x21 = (int )gvol[21];
    x22 = (int )gvol[22];
    x23 = (int )gvol[23];
    x24 = (int )gvol[24];
    x25 = (int )gvol[25];
    x26 = (int )gvol[26];
    x27 = (int )gvol[27];
    x28 = (int )gvol[28];
    x29 = (int )gvol[29];
    x30 = (int )gvol[30];
    gvol[1] = (int volatile   )x1;
    gvol[2] = (int volatile   )x2;
    gvol[3] = (int volatile   )x3;
    gvol[4] = (int volatile   )x4;
    gvol[5] = (int volatile   )x5;
    gvol[6] = (int volatile   )x6;
    gvol[7] = (int volatile   )x7;
    gvol[8] = (int volatile   )x8;
    gvol[9] = (int volatile   )x9;
    gvol[10] = (int volatile   )x10;
    gvol[11] = (int volatile   )x11;
    gvol[12] = (int volatile   )x12;
    gvol[13] = (int volatile   )x13;
    gvol[14] = (int volatile   )x14;
    gvol[15] = (int volatile   )x15;
    gvol[16] = (int volatile   )x16;
    gvol[17] = (int volatile   )x17;
    gvol[18] = (int volatile   )x18;
    gvol[19] = (int volatile   )x19;
    gvol[20] = (int volatile   )x20;
    gvol[21] = (int volatile   )x21;
    gvol[22] = (int volatile   )x22;
    gvol[23] = (int volatile   )x23;
    gvol[24] = (int volatile   )x24;
    gvol[25] = (int volatile   )x25;
    gvol[26] = (int volatile   )x26;
    gvol[27] = (int volatile   )x27;
    gvol[28] = (int volatile   )x28;
    gvol[29] = (int volatile   )x29;
    gvol[30] = (int volatile   )x30;
    x += 0xfffffffffffff800ULL;
  }
  return (x);
}
}
ull ( __attribute__((__noinline__)) t2)(int n , ull x ) 
{ int x1 ;
  int x2 ;
  int x3 ;
  int x4 ;
  int x5 ;
  int x6 ;
  int x7 ;
  int x8 ;
  int x9 ;
  int x10 ;
  int x11 ;
  int x12 ;
  int x13 ;
  int x14 ;
  int x15 ;
  int x16 ;
  int x17 ;
  int x18 ;
  int x19 ;
  int x20 ;
  int x21 ;
  int x22 ;
  int x23 ;
  int x24 ;
  int x25 ;
  int x26 ;
  int x27 ;
  int x28 ;
  int x29 ;
  int x30 ;
  int tmp ;

  {
  while (1) {
    tmp = n;
    n --;
    if (! tmp) {
      break;
    }
    x1 = (int )gvol[1];
    x2 = (int )gvol[2];
    x3 = (int )gvol[3];
    x4 = (int )gvol[4];
    x5 = (int )gvol[5];
    x6 = (int )gvol[6];
    x7 = (int )gvol[7];
    x8 = (int )gvol[8];
    x9 = (int )gvol[9];
    x10 = (int )gvol[10];
    x11 = (int )gvol[11];
    x12 = (int )gvol[12];
    x13 = (int )gvol[13];
    x14 = (int )gvol[14];
    x15 = (int )gvol[15];
    x16 = (int )gvol[16];
    x17 = (int )gvol[17];
    x18 = (int )gvol[18];
    x19 = (int )gvol[19];
    x20 = (int )gvol[20];
    x21 = (int )gvol[21];
    x22 = (int )gvol[22];
    x23 = (int )gvol[23];
    x24 = (int )gvol[24];
    x25 = (int )gvol[25];
    x26 = (int )gvol[26];
    x27 = (int )gvol[27];
    x28 = (int )gvol[28];
    x29 = (int )gvol[29];
    x30 = (int )gvol[30];
    gvol[1] = (int volatile   )x1;
    gvol[2] = (int volatile   )x2;
    gvol[3] = (int volatile   )x3;
    gvol[4] = (int volatile   )x4;
    gvol[5] = (int volatile   )x5;
    gvol[6] = (int volatile   )x6;
    gvol[7] = (int volatile   )x7;
    gvol[8] = (int volatile   )x8;
    gvol[9] = (int volatile   )x9;
    gvol[10] = (int volatile   )x10;
    gvol[11] = (int volatile   )x11;
    gvol[12] = (int volatile   )x12;
    gvol[13] = (int volatile   )x13;
    gvol[14] = (int volatile   )x14;
    gvol[15] = (int volatile   )x15;
    gvol[16] = (int volatile   )x16;
    gvol[17] = (int volatile   )x17;
    gvol[18] = (int volatile   )x18;
    gvol[19] = (int volatile   )x19;
    gvol[20] = (int volatile   )x20;
    gvol[21] = (int volatile   )x21;
    gvol[22] = (int volatile   )x22;
    gvol[23] = (int volatile   )x23;
    gvol[24] = (int volatile   )x24;
    gvol[25] = (int volatile   )x25;
    gvol[26] = (int volatile   )x26;
    gvol[27] = (int volatile   )x27;
    gvol[28] = (int volatile   )x28;
    gvol[29] = (int volatile   )x29;
    gvol[30] = (int volatile   )x30;
    x += 0xfffffffffffffdffULL;
  }
  return (x);
}
}
ull ( __attribute__((__noinline__)) t3)(int n , ull x ) 
{ int x1 ;
  int x2 ;
  int x3 ;
  int x4 ;
  int x5 ;
  int x6 ;
  int x7 ;
  int x8 ;
  int x9 ;
  int x10 ;
  int x11 ;
  int x12 ;
  int x13 ;
  int x14 ;
  int x15 ;
  int x16 ;
  int x17 ;
  int x18 ;
  int x19 ;
  int x20 ;
  int x21 ;
  int x22 ;
  int x23 ;
  int x24 ;
  int x25 ;
  int x26 ;
  int x27 ;
  int x28 ;
  int x29 ;
  int x30 ;
  int tmp ;

  {
  while (1) {
    tmp = n;
    n --;
    if (! tmp) {
      break;
    }
    x1 = (int )gvol[1];
    x2 = (int )gvol[2];
    x3 = (int )gvol[3];
    x4 = (int )gvol[4];
    x5 = (int )gvol[5];
    x6 = (int )gvol[6];
    x7 = (int )gvol[7];
    x8 = (int )gvol[8];
    x9 = (int )gvol[9];
    x10 = (int )gvol[10];
    x11 = (int )gvol[11];
    x12 = (int )gvol[12];
    x13 = (int )gvol[13];
    x14 = (int )gvol[14];
    x15 = (int )gvol[15];
    x16 = (int )gvol[16];
    x17 = (int )gvol[17];
    x18 = (int )gvol[18];
    x19 = (int )gvol[19];
    x20 = (int )gvol[20];
    x21 = (int )gvol[21];
    x22 = (int )gvol[22];
    x23 = (int )gvol[23];
    x24 = (int )gvol[24];
    x25 = (int )gvol[25];
    x26 = (int )gvol[26];
    x27 = (int )gvol[27];
    x28 = (int )gvol[28];
    x29 = (int )gvol[29];
    x30 = (int )gvol[30];
    gvol[1] = (int volatile   )x1;
    gvol[2] = (int volatile   )x2;
    gvol[3] = (int volatile   )x3;
    gvol[4] = (int volatile   )x4;
    gvol[5] = (int volatile   )x5;
    gvol[6] = (int volatile   )x6;
    gvol[7] = (int volatile   )x7;
    gvol[8] = (int volatile   )x8;
    gvol[9] = (int volatile   )x9;
    gvol[10] = (int volatile   )x10;
    gvol[11] = (int volatile   )x11;
    gvol[12] = (int volatile   )x12;
    gvol[13] = (int volatile   )x13;
    gvol[14] = (int volatile   )x14;
    gvol[15] = (int volatile   )x15;
    gvol[16] = (int volatile   )x16;
    gvol[17] = (int volatile   )x17;
    gvol[18] = (int volatile   )x18;
    gvol[19] = (int volatile   )x19;
    gvol[20] = (int volatile   )x20;
    gvol[21] = (int volatile   )x21;
    gvol[22] = (int volatile   )x22;
    gvol[23] = (int volatile   )x23;
    gvol[24] = (int volatile   )x24;
    gvol[25] = (int volatile   )x25;
    gvol[26] = (int volatile   )x26;
    gvol[27] = (int volatile   )x27;
    gvol[28] = (int volatile   )x28;
    gvol[29] = (int volatile   )x29;
    gvol[30] = (int volatile   )x30;
    x += 0xfffffffffffffe00ULL;
  }
  return (x);
}
}
ull ( __attribute__((__noinline__)) t4)(int n , ull x ) 
{ int x1 ;
  int x2 ;
  int x3 ;
  int x4 ;
  int x5 ;
  int x6 ;
  int x7 ;
  int x8 ;
  int x9 ;
  int x10 ;
  int x11 ;
  int x12 ;
  int x13 ;
  int x14 ;
  int x15 ;
  int x16 ;
  int x17 ;
  int x18 ;
  int x19 ;
  int x20 ;
  int x21 ;
  int x22 ;
  int x23 ;
  int x24 ;
  int x25 ;
  int x26 ;
  int x27 ;
  int x28 ;
  int x29 ;
  int x30 ;
  int tmp ;

  {
  while (1) {
    tmp = n;
    n --;
    if (! tmp) {
      break;
    }
    x1 = (int )gvol[1];
    x2 = (int )gvol[2];
    x3 = (int )gvol[3];
    x4 = (int )gvol[4];
    x5 = (int )gvol[5];
    x6 = (int )gvol[6];
    x7 = (int )gvol[7];
    x8 = (int )gvol[8];
    x9 = (int )gvol[9];
    x10 = (int )gvol[10];
    x11 = (int )gvol[11];
    x12 = (int )gvol[12];
    x13 = (int )gvol[13];
    x14 = (int )gvol[14];
    x15 = (int )gvol[15];
    x16 = (int )gvol[16];
    x17 = (int )gvol[17];
    x18 = (int )gvol[18];
    x19 = (int )gvol[19];
    x20 = (int )gvol[20];
    x21 = (int )gvol[21];
    x22 = (int )gvol[22];
    x23 = (int )gvol[23];
    x24 = (int )gvol[24];
    x25 = (int )gvol[25];
    x26 = (int )gvol[26];
    x27 = (int )gvol[27];
    x28 = (int )gvol[28];
    x29 = (int )gvol[29];
    x30 = (int )gvol[30];
    gvol[1] = (int volatile   )x1;
    gvol[2] = (int volatile   )x2;
    gvol[3] = (int volatile   )x3;
    gvol[4] = (int volatile   )x4;
    gvol[5] = (int volatile   )x5;
    gvol[6] = (int volatile   )x6;
    gvol[7] = (int volatile   )x7;
    gvol[8] = (int volatile   )x8;
    gvol[9] = (int volatile   )x9;
    gvol[10] = (int volatile   )x10;
    gvol[11] = (int volatile   )x11;
    gvol[12] = (int volatile   )x12;
    gvol[13] = (int volatile   )x13;
    gvol[14] = (int volatile   )x14;
    gvol[15] = (int volatile   )x15;
    gvol[16] = (int volatile   )x16;
    gvol[17] = (int volatile   )x17;
    gvol[18] = (int volatile   )x18;
    gvol[19] = (int volatile   )x19;
    gvol[20] = (int volatile   )x20;
    gvol[21] = (int volatile   )x21;
    gvol[22] = (int volatile   )x22;
    gvol[23] = (int volatile   )x23;
    gvol[24] = (int volatile   )x24;
    gvol[25] = (int volatile   )x25;
    gvol[26] = (int volatile   )x26;
    gvol[27] = (int volatile   )x27;
    gvol[28] = (int volatile   )x28;
    gvol[29] = (int volatile   )x29;
    gvol[30] = (int volatile   )x30;
    x += 0xfffffffffffffe01ULL;
  }
  return (x);
}
}
ull ( __attribute__((__noinline__)) t5)(int n , ull x ) 
{ int x1 ;
  int x2 ;
  int x3 ;
  int x4 ;
  int x5 ;
  int x6 ;
  int x7 ;
  int x8 ;
  int x9 ;
  int x10 ;
  int x11 ;
  int x12 ;
  int x13 ;
  int x14 ;
  int x15 ;
  int x16 ;
  int x17 ;
  int x18 ;
  int x19 ;
  int x20 ;
  int x21 ;
  int x22 ;
  int x23 ;
  int x24 ;
  int x25 ;
  int x26 ;
  int x27 ;
  int x28 ;
  int x29 ;
  int x30 ;
  int tmp ;

  {
  while (1) {
    tmp = n;
    n --;
    if (! tmp) {
      break;
    }
    x1 = (int )gvol[1];
    x2 = (int )gvol[2];
    x3 = (int )gvol[3];
    x4 = (int )gvol[4];
    x5 = (int )gvol[5];
    x6 = (int )gvol[6];
    x7 = (int )gvol[7];
    x8 = (int )gvol[8];
    x9 = (int )gvol[9];
    x10 = (int )gvol[10];
    x11 = (int )gvol[11];
    x12 = (int )gvol[12];
    x13 = (int )gvol[13];
    x14 = (int )gvol[14];
    x15 = (int )gvol[15];
    x16 = (int )gvol[16];
    x17 = (int )gvol[17];
    x18 = (int )gvol[18];
    x19 = (int )gvol[19];
    x20 = (int )gvol[20];
    x21 = (int )gvol[21];
    x22 = (int )gvol[22];
    x23 = (int )gvol[23];
    x24 = (int )gvol[24];
    x25 = (int )gvol[25];
    x26 = (int )gvol[26];
    x27 = (int )gvol[27];
    x28 = (int )gvol[28];
    x29 = (int )gvol[29];
    x30 = (int )gvol[30];
    gvol[1] = (int volatile   )x1;
    gvol[2] = (int volatile   )x2;
    gvol[3] = (int volatile   )x3;
    gvol[4] = (int volatile   )x4;
    gvol[5] = (int volatile   )x5;
    gvol[6] = (int volatile   )x6;
    gvol[7] = (int volatile   )x7;
    gvol[8] = (int volatile   )x8;
    gvol[9] = (int volatile   )x9;
    gvol[10] = (int volatile   )x10;
    gvol[11] = (int volatile   )x11;
    gvol[12] = (int volatile   )x12;
    gvol[13] = (int volatile   )x13;
    gvol[14] = (int volatile   )x14;
    gvol[15] = (int volatile   )x15;
    gvol[16] = (int volatile   )x16;
    gvol[17] = (int volatile   )x17;
    gvol[18] = (int volatile   )x18;
    gvol[19] = (int volatile   )x19;
    gvol[20] = (int volatile   )x20;
    gvol[21] = (int volatile   )x21;
    gvol[22] = (int volatile   )x22;
    gvol[23] = (int volatile   )x23;
    gvol[24] = (int volatile   )x24;
    gvol[25] = (int volatile   )x25;
    gvol[26] = (int volatile   )x26;
    gvol[27] = (int volatile   )x27;
    gvol[28] = (int volatile   )x28;
    gvol[29] = (int volatile   )x29;
    gvol[30] = (int volatile   )x30;
    x --;
  }
  return (x);
}
}
ull ( __attribute__((__noinline__)) t6)(int n , ull x ) 
{ int x1 ;
  int x2 ;
  int x3 ;
  int x4 ;
  int x5 ;
  int x6 ;
  int x7 ;
  int x8 ;
  int x9 ;
  int x10 ;
  int x11 ;
  int x12 ;
  int x13 ;
  int x14 ;
  int x15 ;
  int x16 ;
  int x17 ;
  int x18 ;
  int x19 ;
  int x20 ;
  int x21 ;
  int x22 ;
  int x23 ;
  int x24 ;
  int x25 ;
  int x26 ;
  int x27 ;
  int x28 ;
  int x29 ;
  int x30 ;
  int tmp ;

  {
  while (1) {
    tmp = n;
    n --;
    if (! tmp) {
      break;
    }
    x1 = (int )gvol[1];
    x2 = (int )gvol[2];
    x3 = (int )gvol[3];
    x4 = (int )gvol[4];
    x5 = (int )gvol[5];
    x6 = (int )gvol[6];
    x7 = (int )gvol[7];
    x8 = (int )gvol[8];
    x9 = (int )gvol[9];
    x10 = (int )gvol[10];
    x11 = (int )gvol[11];
    x12 = (int )gvol[12];
    x13 = (int )gvol[13];
    x14 = (int )gvol[14];
    x15 = (int )gvol[15];
    x16 = (int )gvol[16];
    x17 = (int )gvol[17];
    x18 = (int )gvol[18];
    x19 = (int )gvol[19];
    x20 = (int )gvol[20];
    x21 = (int )gvol[21];
    x22 = (int )gvol[22];
    x23 = (int )gvol[23];
    x24 = (int )gvol[24];
    x25 = (int )gvol[25];
    x26 = (int )gvol[26];
    x27 = (int )gvol[27];
    x28 = (int )gvol[28];
    x29 = (int )gvol[29];
    x30 = (int )gvol[30];
    gvol[1] = (int volatile   )x1;
    gvol[2] = (int volatile   )x2;
    gvol[3] = (int volatile   )x3;
    gvol[4] = (int volatile   )x4;
    gvol[5] = (int volatile   )x5;
    gvol[6] = (int volatile   )x6;
    gvol[7] = (int volatile   )x7;
    gvol[8] = (int volatile   )x8;
    gvol[9] = (int volatile   )x9;
    gvol[10] = (int volatile   )x10;
    gvol[11] = (int volatile   )x11;
    gvol[12] = (int volatile   )x12;
    gvol[13] = (int volatile   )x13;
    gvol[14] = (int volatile   )x14;
    gvol[15] = (int volatile   )x15;
    gvol[16] = (int volatile   )x16;
    gvol[17] = (int volatile   )x17;
    gvol[18] = (int volatile   )x18;
    gvol[19] = (int volatile   )x19;
    gvol[20] = (int volatile   )x20;
    gvol[21] = (int volatile   )x21;
    gvol[22] = (int volatile   )x22;
    gvol[23] = (int volatile   )x23;
    gvol[24] = (int volatile   )x24;
    gvol[25] = (int volatile   )x25;
    gvol[26] = (int volatile   )x26;
    gvol[27] = (int volatile   )x27;
    gvol[28] = (int volatile   )x28;
    gvol[29] = (int volatile   )x29;
    gvol[30] = (int volatile   )x30;
    x ++;
  }
  return (x);
}
}
ull ( __attribute__((__noinline__)) t7)(int n , ull x ) 
{ int x1 ;
  int x2 ;
  int x3 ;
  int x4 ;
  int x5 ;
  int x6 ;
  int x7 ;
  int x8 ;
  int x9 ;
  int x10 ;
  int x11 ;
  int x12 ;
  int x13 ;
  int x14 ;
  int x15 ;
  int x16 ;
  int x17 ;
  int x18 ;
  int x19 ;
  int x20 ;
  int x21 ;
  int x22 ;
  int x23 ;
  int x24 ;
  int x25 ;
  int x26 ;
  int x27 ;
  int x28 ;
  int x29 ;
  int x30 ;
  int tmp ;

  {
  while (1) {
    tmp = n;
    n --;
    if (! tmp) {
      break;
    }
    x1 = (int )gvol[1];
    x2 = (int )gvol[2];
    x3 = (int )gvol[3];
    x4 = (int )gvol[4];
    x5 = (int )gvol[5];
    x6 = (int )gvol[6];
    x7 = (int )gvol[7];
    x8 = (int )gvol[8];
    x9 = (int )gvol[9];
    x10 = (int )gvol[10];
    x11 = (int )gvol[11];
    x12 = (int )gvol[12];
    x13 = (int )gvol[13];
    x14 = (int )gvol[14];
    x15 = (int )gvol[15];
    x16 = (int )gvol[16];
    x17 = (int )gvol[17];
    x18 = (int )gvol[18];
    x19 = (int )gvol[19];
    x20 = (int )gvol[20];
    x21 = (int )gvol[21];
    x22 = (int )gvol[22];
    x23 = (int )gvol[23];
    x24 = (int )gvol[24];
    x25 = (int )gvol[25];
    x26 = (int )gvol[26];
    x27 = (int )gvol[27];
    x28 = (int )gvol[28];
    x29 = (int )gvol[29];
    x30 = (int )gvol[30];
    gvol[1] = (int volatile   )x1;
    gvol[2] = (int volatile   )x2;
    gvol[3] = (int volatile   )x3;
    gvol[4] = (int volatile   )x4;
    gvol[5] = (int volatile   )x5;
    gvol[6] = (int volatile   )x6;
    gvol[7] = (int volatile   )x7;
    gvol[8] = (int volatile   )x8;
    gvol[9] = (int volatile   )x9;
    gvol[10] = (int volatile   )x10;
    gvol[11] = (int volatile   )x11;
    gvol[12] = (int volatile   )x12;
    gvol[13] = (int volatile   )x13;
    gvol[14] = (int volatile   )x14;
    gvol[15] = (int volatile   )x15;
    gvol[16] = (int volatile   )x16;
    gvol[17] = (int volatile   )x17;
    gvol[18] = (int volatile   )x18;
    gvol[19] = (int volatile   )x19;
    gvol[20] = (int volatile   )x20;
    gvol[21] = (int volatile   )x21;
    gvol[22] = (int volatile   )x22;
    gvol[23] = (int volatile   )x23;
    gvol[24] = (int volatile   )x24;
    gvol[25] = (int volatile   )x25;
    gvol[26] = (int volatile   )x26;
    gvol[27] = (int volatile   )x27;
    gvol[28] = (int volatile   )x28;
    gvol[29] = (int volatile   )x29;
    gvol[30] = (int volatile   )x30;
    x += 511ULL;
  }
  return (x);
}
}
ull ( __attribute__((__noinline__)) t8)(int n , ull x ) 
{ int x1 ;
  int x2 ;
  int x3 ;
  int x4 ;
  int x5 ;
  int x6 ;
  int x7 ;
  int x8 ;
  int x9 ;
  int x10 ;
  int x11 ;
  int x12 ;
  int x13 ;
  int x14 ;
  int x15 ;
  int x16 ;
  int x17 ;
  int x18 ;
  int x19 ;
  int x20 ;
  int x21 ;
  int x22 ;
  int x23 ;
  int x24 ;
  int x25 ;
  int x26 ;
  int x27 ;
  int x28 ;
  int x29 ;
  int x30 ;
  int tmp ;

  {
  while (1) {
    tmp = n;
    n --;
    if (! tmp) {
      break;
    }
    x1 = (int )gvol[1];
    x2 = (int )gvol[2];
    x3 = (int )gvol[3];
    x4 = (int )gvol[4];
    x5 = (int )gvol[5];
    x6 = (int )gvol[6];
    x7 = (int )gvol[7];
    x8 = (int )gvol[8];
    x9 = (int )gvol[9];
    x10 = (int )gvol[10];
    x11 = (int )gvol[11];
    x12 = (int )gvol[12];
    x13 = (int )gvol[13];
    x14 = (int )gvol[14];
    x15 = (int )gvol[15];
    x16 = (int )gvol[16];
    x17 = (int )gvol[17];
    x18 = (int )gvol[18];
    x19 = (int )gvol[19];
    x20 = (int )gvol[20];
    x21 = (int )gvol[21];
    x22 = (int )gvol[22];
    x23 = (int )gvol[23];
    x24 = (int )gvol[24];
    x25 = (int )gvol[25];
    x26 = (int )gvol[26];
    x27 = (int )gvol[27];
    x28 = (int )gvol[28];
    x29 = (int )gvol[29];
    x30 = (int )gvol[30];
    gvol[1] = (int volatile   )x1;
    gvol[2] = (int volatile   )x2;
    gvol[3] = (int volatile   )x3;
    gvol[4] = (int volatile   )x4;
    gvol[5] = (int volatile   )x5;
    gvol[6] = (int volatile   )x6;
    gvol[7] = (int volatile   )x7;
    gvol[8] = (int volatile   )x8;
    gvol[9] = (int volatile   )x9;
    gvol[10] = (int volatile   )x10;
    gvol[11] = (int volatile   )x11;
    gvol[12] = (int volatile   )x12;
    gvol[13] = (int volatile   )x13;
    gvol[14] = (int volatile   )x14;
    gvol[15] = (int volatile   )x15;
    gvol[16] = (int volatile   )x16;
    gvol[17] = (int volatile   )x17;
    gvol[18] = (int volatile   )x18;
    gvol[19] = (int volatile   )x19;
    gvol[20] = (int volatile   )x20;
    gvol[21] = (int volatile   )x21;
    gvol[22] = (int volatile   )x22;
    gvol[23] = (int volatile   )x23;
    gvol[24] = (int volatile   )x24;
    gvol[25] = (int volatile   )x25;
    gvol[26] = (int volatile   )x26;
    gvol[27] = (int volatile   )x27;
    gvol[28] = (int volatile   )x28;
    gvol[29] = (int volatile   )x29;
    gvol[30] = (int volatile   )x30;
    x += 512ULL;
  }
  return (x);
}
}
ull ( __attribute__((__noinline__)) t9)(int n , ull x ) 
{ int x1 ;
  int x2 ;
  int x3 ;
  int x4 ;
  int x5 ;
  int x6 ;
  int x7 ;
  int x8 ;
  int x9 ;
  int x10 ;
  int x11 ;
  int x12 ;
  int x13 ;
  int x14 ;
  int x15 ;
  int x16 ;
  int x17 ;
  int x18 ;
  int x19 ;
  int x20 ;
  int x21 ;
  int x22 ;
  int x23 ;
  int x24 ;
  int x25 ;
  int x26 ;
  int x27 ;
  int x28 ;
  int x29 ;
  int x30 ;
  int tmp ;

  {
  while (1) {
    tmp = n;
    n --;
    if (! tmp) {
      break;
    }
    x1 = (int )gvol[1];
    x2 = (int )gvol[2];
    x3 = (int )gvol[3];
    x4 = (int )gvol[4];
    x5 = (int )gvol[5];
    x6 = (int )gvol[6];
    x7 = (int )gvol[7];
    x8 = (int )gvol[8];
    x9 = (int )gvol[9];
    x10 = (int )gvol[10];
    x11 = (int )gvol[11];
    x12 = (int )gvol[12];
    x13 = (int )gvol[13];
    x14 = (int )gvol[14];
    x15 = (int )gvol[15];
    x16 = (int )gvol[16];
    x17 = (int )gvol[17];
    x18 = (int )gvol[18];
    x19 = (int )gvol[19];
    x20 = (int )gvol[20];
    x21 = (int )gvol[21];
    x22 = (int )gvol[22];
    x23 = (int )gvol[23];
    x24 = (int )gvol[24];
    x25 = (int )gvol[25];
    x26 = (int )gvol[26];
    x27 = (int )gvol[27];
    x28 = (int )gvol[28];
    x29 = (int )gvol[29];
    x30 = (int )gvol[30];
    gvol[1] = (int volatile   )x1;
    gvol[2] = (int volatile   )x2;
    gvol[3] = (int volatile   )x3;
    gvol[4] = (int volatile   )x4;
    gvol[5] = (int volatile   )x5;
    gvol[6] = (int volatile   )x6;
    gvol[7] = (int volatile   )x7;
    gvol[8] = (int volatile   )x8;
    gvol[9] = (int volatile   )x9;
    gvol[10] = (int volatile   )x10;
    gvol[11] = (int volatile   )x11;
    gvol[12] = (int volatile   )x12;
    gvol[13] = (int volatile   )x13;
    gvol[14] = (int volatile   )x14;
    gvol[15] = (int volatile   )x15;
    gvol[16] = (int volatile   )x16;
    gvol[17] = (int volatile   )x17;
    gvol[18] = (int volatile   )x18;
    gvol[19] = (int volatile   )x19;
    gvol[20] = (int volatile   )x20;
    gvol[21] = (int volatile   )x21;
    gvol[22] = (int volatile   )x22;
    gvol[23] = (int volatile   )x23;
    gvol[24] = (int volatile   )x24;
    gvol[25] = (int volatile   )x25;
    gvol[26] = (int volatile   )x26;
    gvol[27] = (int volatile   )x27;
    gvol[28] = (int volatile   )x28;
    gvol[29] = (int volatile   )x29;
    gvol[30] = (int volatile   )x30;
    x += 513ULL;
  }
  return (x);
}
}
ull ( __attribute__((__noinline__)) t10)(int n , ull x ) 
{ int x1 ;
  int x2 ;
  int x3 ;
  int x4 ;
  int x5 ;
  int x6 ;
  int x7 ;
  int x8 ;
  int x9 ;
  int x10 ;
  int x11 ;
  int x12 ;
  int x13 ;
  int x14 ;
  int x15 ;
  int x16 ;
  int x17 ;
  int x18 ;
  int x19 ;
  int x20 ;
  int x21 ;
  int x22 ;
  int x23 ;
  int x24 ;
  int x25 ;
  int x26 ;
  int x27 ;
  int x28 ;
  int x29 ;
  int x30 ;
  int tmp ;

  {
  while (1) {
    tmp = n;
    n --;
    if (! tmp) {
      break;
    }
    x1 = (int )gvol[1];
    x2 = (int )gvol[2];
    x3 = (int )gvol[3];
    x4 = (int )gvol[4];
    x5 = (int )gvol[5];
    x6 = (int )gvol[6];
    x7 = (int )gvol[7];
    x8 = (int )gvol[8];
    x9 = (int )gvol[9];
    x10 = (int )gvol[10];
    x11 = (int )gvol[11];
    x12 = (int )gvol[12];
    x13 = (int )gvol[13];
    x14 = (int )gvol[14];
    x15 = (int )gvol[15];
    x16 = (int )gvol[16];
    x17 = (int )gvol[17];
    x18 = (int )gvol[18];
    x19 = (int )gvol[19];
    x20 = (int )gvol[20];
    x21 = (int )gvol[21];
    x22 = (int )gvol[22];
    x23 = (int )gvol[23];
    x24 = (int )gvol[24];
    x25 = (int )gvol[25];
    x26 = (int )gvol[26];
    x27 = (int )gvol[27];
    x28 = (int )gvol[28];
    x29 = (int )gvol[29];
    x30 = (int )gvol[30];
    gvol[1] = (int volatile   )x1;
    gvol[2] = (int volatile   )x2;
    gvol[3] = (int volatile   )x3;
    gvol[4] = (int volatile   )x4;
    gvol[5] = (int volatile   )x5;
    gvol[6] = (int volatile   )x6;
    gvol[7] = (int volatile   )x7;
    gvol[8] = (int volatile   )x8;
    gvol[9] = (int volatile   )x9;
    gvol[10] = (int volatile   )x10;
    gvol[11] = (int volatile   )x11;
    gvol[12] = (int volatile   )x12;
    gvol[13] = (int volatile   )x13;
    gvol[14] = (int volatile   )x14;
    gvol[15] = (int volatile   )x15;
    gvol[16] = (int volatile   )x16;
    gvol[17] = (int volatile   )x17;
    gvol[18] = (int volatile   )x18;
    gvol[19] = (int volatile   )x19;
    gvol[20] = (int volatile   )x20;
    gvol[21] = (int volatile   )x21;
    gvol[22] = (int volatile   )x22;
    gvol[23] = (int volatile   )x23;
    gvol[24] = (int volatile   )x24;
    gvol[25] = (int volatile   )x25;
    gvol[26] = (int volatile   )x26;
    gvol[27] = (int volatile   )x27;
    gvol[28] = (int volatile   )x28;
    gvol[29] = (int volatile   )x29;
    gvol[30] = (int volatile   )x30;
    x += gull;
  }
  return (x);
}
}
ull ( __attribute__((__noinline__)) t11)(int n , ull x ) 
{ int x1 ;
  int x2 ;
  int x3 ;
  int x4 ;
  int x5 ;
  int x6 ;
  int x7 ;
  int x8 ;
  int x9 ;
  int x10 ;
  int x11 ;
  int x12 ;
  int x13 ;
  int x14 ;
  int x15 ;
  int x16 ;
  int x17 ;
  int x18 ;
  int x19 ;
  int x20 ;
  int x21 ;
  int x22 ;
  int x23 ;
  int x24 ;
  int x25 ;
  int x26 ;
  int x27 ;
  int x28 ;
  int x29 ;
  int x30 ;
  int tmp ;

  {
  while (1) {
    tmp = n;
    n --;
    if (! tmp) {
      break;
    }
    x1 = (int )gvol[1];
    x2 = (int )gvol[2];
    x3 = (int )gvol[3];
    x4 = (int )gvol[4];
    x5 = (int )gvol[5];
    x6 = (int )gvol[6];
    x7 = (int )gvol[7];
    x8 = (int )gvol[8];
    x9 = (int )gvol[9];
    x10 = (int )gvol[10];
    x11 = (int )gvol[11];
    x12 = (int )gvol[12];
    x13 = (int )gvol[13];
    x14 = (int )gvol[14];
    x15 = (int )gvol[15];
    x16 = (int )gvol[16];
    x17 = (int )gvol[17];
    x18 = (int )gvol[18];
    x19 = (int )gvol[19];
    x20 = (int )gvol[20];
    x21 = (int )gvol[21];
    x22 = (int )gvol[22];
    x23 = (int )gvol[23];
    x24 = (int )gvol[24];
    x25 = (int )gvol[25];
    x26 = (int )gvol[26];
    x27 = (int )gvol[27];
    x28 = (int )gvol[28];
    x29 = (int )gvol[29];
    x30 = (int )gvol[30];
    gvol[1] = (int volatile   )x1;
    gvol[2] = (int volatile   )x2;
    gvol[3] = (int volatile   )x3;
    gvol[4] = (int volatile   )x4;
    gvol[5] = (int volatile   )x5;
    gvol[6] = (int volatile   )x6;
    gvol[7] = (int volatile   )x7;
    gvol[8] = (int volatile   )x8;
    gvol[9] = (int volatile   )x9;
    gvol[10] = (int volatile   )x10;
    gvol[11] = (int volatile   )x11;
    gvol[12] = (int volatile   )x12;
    gvol[13] = (int volatile   )x13;
    gvol[14] = (int volatile   )x14;
    gvol[15] = (int volatile   )x15;
    gvol[16] = (int volatile   )x16;
    gvol[17] = (int volatile   )x17;
    gvol[18] = (int volatile   )x18;
    gvol[19] = (int volatile   )x19;
    gvol[20] = (int volatile   )x20;
    gvol[21] = (int volatile   )x21;
    gvol[22] = (int volatile   )x22;
    gvol[23] = (int volatile   )x23;
    gvol[24] = (int volatile   )x24;
    gvol[25] = (int volatile   )x25;
    gvol[26] = (int volatile   )x26;
    gvol[27] = (int volatile   )x27;
    gvol[28] = (int volatile   )x28;
    gvol[29] = (int volatile   )x29;
    gvol[30] = (int volatile   )x30;
    x += - gull;
  }
  return (x);
}
}
ull neg(ull x ) 
{ 

  {
  return (- x);
}
}
int main(void) 
{ ull tmp ;
  ull tmp___0 ;
  ull tmp___1 ;
  ull tmp___2 ;
  ull tmp___3 ;
  ull tmp___4 ;
  ull tmp___5 ;
  ull tmp___6 ;
  ull tmp___7 ;
  ull tmp___8 ;
  ull tmp___9 ;
  ull tmp___10 ;
  ull tmp___11 ;
  ull tmp___12 ;
  ull tmp___13 ;
  ull tmp___14 ;
  ull tmp___15 ;
  ull tmp___16 ;
  ull tmp___17 ;
  ull tmp___18 ;
  ull tmp___19 ;
  ull tmp___20 ;
  ull tmp___21 ;

  {
  gull = 100ULL;
  tmp = t1(3, ~ 0ULL);
  if (tmp != 0xffffffffffffe7ffULL) {
    abort();
  }
  tmp___0 = t1(3, 4294967295ULL);
  if (tmp___0 != 4294961151ULL) {
    abort();
  }
  tmp___1 = t2(3, ~ 0ULL);
  if (tmp___1 != 0xfffffffffffff9fcULL) {
    abort();
  }
  tmp___2 = t2(3, 4294967295ULL);
  if (tmp___2 != 4294965756ULL) {
    abort();
  }
  tmp___3 = t3(3, ~ 0ULL);
  if (tmp___3 != 0xfffffffffffff9ffULL) {
    abort();
  }
  tmp___4 = t3(3, 4294967295ULL);
  if (tmp___4 != 4294965759ULL) {
    abort();
  }
  tmp___5 = t4(3, ~ 0ULL);
  if (tmp___5 != 0xfffffffffffffa02ULL) {
    abort();
  }
  tmp___6 = t4(3, 4294967295ULL);
  if (tmp___6 != 4294965762ULL) {
    abort();
  }
  tmp___7 = t5(3, ~ 0ULL);
  if (tmp___7 != 0xfffffffffffffffcULL) {
    abort();
  }
  tmp___8 = t5(3, 4294967295ULL);
  if (tmp___8 != 4294967292ULL) {
    abort();
  }
  tmp___9 = t6(3, ~ 0ULL);
  if (tmp___9 != 2ULL) {
    abort();
  }
  tmp___10 = t6(3, 4294967295ULL);
  if (tmp___10 != 4294967298ULL) {
    abort();
  }
  tmp___11 = t7(3, ~ 0ULL);
  if (tmp___11 != 1532ULL) {
    abort();
  }
  tmp___12 = t7(3, 4294967295ULL);
  if (tmp___12 != 4294968828ULL) {
    abort();
  }
  tmp___13 = t8(3, ~ 0ULL);
  if (tmp___13 != 1535ULL) {
    abort();
  }
  tmp___14 = t8(3, 4294967295ULL);
  if (tmp___14 != 4294968831ULL) {
    abort();
  }
  tmp___15 = t9(3, ~ 0ULL);
  if (tmp___15 != 1538ULL) {
    abort();
  }
  tmp___16 = t9(3, 4294967295ULL);
  if (tmp___16 != 4294968834ULL) {
    abort();
  }
  tmp___17 = t10(3, ~ 0ULL);
  if (tmp___17 != gull * 3ULL - 1ULL) {
    abort();
  }
  tmp___18 = t10(3, 4294967295ULL);
  if (tmp___18 != gull * 3ULL + 4294967295ULL) {
    abort();
  }
  tmp___19 = t11(3, ~ 0ULL);
  if (tmp___19 != - gull * 3ULL - 1ULL) {
    abort();
  }
  tmp___20 = t11(3, 4294967295ULL);
  if (tmp___20 != - gull * 3ULL + 4294967295ULL) {
    abort();
  }
  tmp___21 = neg(gull);
  if (tmp___21 != 0xffffffffffffff9cULL) {
    abort();
  }
  exit(0);
}
}
