/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 2 "20041126-1.c"
extern int abs(int  ) ;
#line 5 "20041126-1.c"
void check(int *p ) 
{ int i ;

  {
#line 9
  i = 0;
#line 9
  while (i < 5) {
#line 10
    if (*(p + i)) {
#line 11
      abort();
    }
#line 9
    i ++;
  }
#line 12
  while (i < 10) {
#line 13
    if (*(p + i) != i + 1) {
#line 14
      abort();
    }
#line 12
    i ++;
  }
#line 15
  return;
}
}
#line 17 "20041126-1.c"
int main(void) 
{ int a[10] ;
  int i ;
  int tmp ;

  {
#line 19
  a[0] = 1;
#line 19
  a[1] = 2;
#line 19
  a[2] = 3;
#line 19
  a[3] = 4;
#line 19
  a[4] = 5;
#line 19
  a[5] = 6;
#line 19
  a[6] = 7;
#line 19
  a[7] = 8;
#line 19
  a[8] = 9;
#line 19
  a[9] = 10;
#line 22
  i = -5;
#line 22
  while (i < 0) {
#line 23
    tmp = abs(i - 10);
#line 23
    a[tmp - 11] = 0;
#line 22
    i ++;
  }
#line 24
  check(a);
#line 25
  return (0);
}
}
