/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int x[4]  = {      -1073741824,      2147483647,      2,      4};
int main(void) 
{ 

  {
  if (x[0] < x[1]) {
    if ((x[2] & x[3]) < 0) {
      abort();
    }
  }
  exit(0);
}
}
