/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct s {
   struct s *next ;
} __attribute__((__packed__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
struct s *( __attribute__((__noinline__)) maybe_next)(struct s *s , int t ) 
{ 

  {
  if (t) {
    s = s->next;
  }
  return (s);
}
}
int main(void) 
{ struct s s1 ;
  struct s s2 ;
  struct s *tmp ;

  {
  s1.next = & s2;
  tmp = maybe_next(& s1, 1);
  if ((unsigned long )tmp != (unsigned long )(& s2)) {
    abort();
  }
  exit(0);
}
}
