/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "20040707-1.c"
struct s {
   char c1 ;
   char c2 ;
};
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 5 "20040707-1.c"
static struct s s1  ;
#line 3 "20040707-1.c"
void foo(struct s s ) 
{ 

  {
#line 6
  s1 = s;
#line 7
  return;
}
}
#line 10 "20040707-1.c"
static struct s s2  ;
#line 8 "20040707-1.c"
int main(void) 
{ 

  {
#line 11
  foo(s2);
#line 12
  exit(0);
}
}
