/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
static long long min(void) 
{ 

  {
  return ((-0x7FFFFFFFFFFFFFFF-1));
}
}
void foo(long long j ) 
{ long long tmp ;

  {
  if (j > 10LL) {
    abort();
  } else {
    tmp = min();
    if (j < tmp) {
      abort();
    }
  }
  return;
}
}
int main(void) 
{ 

  {
  foo(10LL);
  return (0);
}
}
