/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 2 "20051110-1.c"
void add_unwind_adjustsp(long offset ) ;
#line 5 "20051110-1.c"
unsigned char bytes[5]  ;
#line 7 "20051110-1.c"
void add_unwind_adjustsp(long offset ) 
{ int n ;
  unsigned long o ;

  {
#line 13
  o = (unsigned long )((offset - 516L) >> 2);
#line 15
  n = 0;
#line 16
  while (o) {
#line 18
    bytes[n] = (unsigned char )(o & 127UL);
#line 19
    o >>= 7;
#line 20
    if (o) {
#line 21
      bytes[n] = (unsigned char )((int )bytes[n] | 128);
    }
#line 22
    n ++;
  }
#line 24
  return;
}
}
#line 26 "20051110-1.c"
int main(void) 
{ 

  {
#line 28
  add_unwind_adjustsp(4132L);
#line 29
  if ((int )bytes[0] != 136) {
#line 30
    abort();
  } else {
#line 29
    if ((int )bytes[1] != 7) {
#line 30
      abort();
    }
  }
#line 31
  return (0);
}
}
