/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

enum __anonenum_E_1 {
    A = 0,
    B = 1,
    C = 2,
    D = 3
} ;
typedef enum __anonenum_E_1 E;
struct S {
   E /* mode(__byte__) */   a ;
   E /* mode(__byte__) */   b ;
   E /* mode(__byte__) */   c ;
   E /* mode(__byte__) */   d ;
};
extern void abort(void) ;
extern void exit(int  ) ;
void foo(struct S *s ) 
{ 

  {
  if ((unsigned int /* mode(__byte__) */   )s->a != (unsigned int /* mode(__byte__) */   )s->b) {
    abort();
  }
  if ((unsigned int /* mode(__byte__) */   )s->c != (unsigned int /* mode(__byte__) */   )2) {
    abort();
  }
  return;
}
}
int main(void) 
{ struct S s[2] ;

  {
  s[0].a = (enum __anonenum_E_1  /* mode(__byte__) */  )1;
  s[0].b = (enum __anonenum_E_1  /* mode(__byte__) */  )1;
  s[0].c = (enum __anonenum_E_1  /* mode(__byte__) */  )2;
  s[0].d = (enum __anonenum_E_1  /* mode(__byte__) */  )3;
  s[1].a = (enum __anonenum_E_1  /* mode(__byte__) */  )3;
  s[1].b = (enum __anonenum_E_1  /* mode(__byte__) */  )2;
  s[1].c = (enum __anonenum_E_1  /* mode(__byte__) */  )1;
  s[1].d = (enum __anonenum_E_1  /* mode(__byte__) */  )0;
  foo(s);
  exit(0);
}
}
