/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 6 "20050713-1.c"
struct S {
   int a ;
   int b ;
   int c ;
};
#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 11 "20050713-1.c"
int foo2(struct S x , struct S y ) 
{ 

  {
#line 14
  if (x.a != 3) {
#line 15
    abort();
  } else {
#line 14
    if (x.b != 4) {
#line 15
      abort();
    } else {
#line 14
      if (x.c != 5) {
#line 15
        abort();
      }
    }
  }
#line 16
  if (y.a != 6) {
#line 17
    abort();
  } else {
#line 16
    if (y.b != 7) {
#line 17
      abort();
    } else {
#line 16
      if (y.c != 8) {
#line 17
        abort();
      }
    }
  }
#line 18
  return (0);
}
}
#line 21 "20050713-1.c"
int foo3(struct S x , struct S y , struct S z ) 
{ 

  {
#line 24
  foo2(x, y);
#line 25
  if (z.a != 9) {
#line 26
    abort();
  } else {
#line 25
    if (z.b != 10) {
#line 26
      abort();
    } else {
#line 25
      if (z.c != 11) {
#line 26
        abort();
      }
    }
  }
#line 27
  return (0);
}
}
#line 30 "20050713-1.c"
int bar2(struct S x , struct S y ) 
{ int tmp ;

  {
#line 33
  tmp = foo2(y, x);
#line 33
  return (tmp);
}
}
#line 36 "20050713-1.c"
int bar3(struct S x , struct S y , struct S z ) 
{ int tmp ;

  {
#line 39
  tmp = foo3(y, x, z);
#line 39
  return (tmp);
}
}
#line 42 "20050713-1.c"
int baz3(struct S x , struct S y , struct S z ) 
{ int tmp ;

  {
#line 45
  tmp = foo3(y, z, x);
#line 45
  return (tmp);
}
}
#line 48 "20050713-1.c"
int main(void) 
{ struct S a ;
  struct S b ;
  struct S c ;

  {
#line 50
  a.a = 3;
#line 50
  a.b = 4;
#line 50
  a.c = 5;
#line 50
  b.a = 6;
#line 50
  b.b = 7;
#line 50
  b.c = 8;
#line 50
  c.a = 9;
#line 50
  c.b = 10;
#line 50
  c.c = 11;
#line 52
  bar2(b, a);
#line 53
  bar3(b, a, c);
#line 54
  baz3(c, a, b);
#line 55
  return (0);
}
}
