/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "20050111-1.c"
unsigned int foo(unsigned long long x ) 
{ unsigned int u ;

  {
#line 9
  if (x == 0ULL) {
#line 10
    return (0U);
  }
#line 11
  u = (unsigned int )(x >> 32);
#line 12
  return (u);
}
}
#line 15 "20050111-1.c"
unsigned long long bar(unsigned short x ) 
{ 

  {
#line 18
  return ((unsigned long long )x << 32);
}
}
#line 23 "20050111-1.c"
int main(void) 
{ unsigned int tmp ;
  unsigned int tmp___0 ;
  unsigned int tmp___1 ;
  unsigned long long tmp___2 ;
  unsigned long long tmp___3 ;

  {
#line 25
  if (sizeof(long long ) != 8UL) {
#line 26
    return (0);
  }
#line 28
  tmp = foo(0ULL);
#line 28
  if (tmp != 0U) {
#line 29
    abort();
  }
#line 30
  tmp___0 = foo(4294967295ULL);
#line 30
  if (tmp___0 != 0U) {
#line 31
    abort();
  }
#line 32
  tmp___1 = foo(163192045312ULL);
#line 32
  if (tmp___1 != 37U) {
#line 33
    abort();
  }
#line 34
  tmp___2 = bar((unsigned short)0);
#line 34
  if (tmp___2 != 0ULL) {
#line 35
    abort();
  }
#line 36
  tmp___3 = bar((unsigned short)37);
#line 36
  if (tmp___3 != 158913789952ULL) {
#line 37
    abort();
  }
#line 38
  return (0);
}
}
