/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern int strcmp(char const   * , char const   * ) ;
int ( __attribute__((__noinline__)) bar)(char const   **x ) 
{ char const   *tmp ;

  {
  tmp = *x;
  (*x) ++;
  return ((int )*tmp);
}
}
int ( __attribute__((__noinline__)) baz)(int c ) 
{ 

  {
  return (c != 64);
}
}
void ( __attribute__((__noinline__)) foo)(char const   **w , char *x , _Bool y , _Bool z ) 
{ char c ;
  int tmp ;
  int i ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;

  {
  tmp = bar(w);
  c = (char )tmp;
  i = 0;
  while (1) {
    tmp___0 = i;
    i ++;
    *(x + tmp___0) = c;
    tmp___1 = bar(w);
    c = (char )tmp___1;
    if (y) {
      if ((int )c == 39) {
        break;
      }
    }
    if (z) {
      if ((int )c == 34) {
        break;
      }
    }
    if (! y) {
      if (! z) {
        tmp___2 = baz((int )c);
        if (! tmp___2) {
          break;
        }
      }
    }
  }
  *(x + i) = (char)0;
  return;
}
}
int main(void) 
{ char buf[64] ;
  char const   *p ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;

  {
  p = "abcde\'fgh";
  foo(& p, buf, (_Bool)1, (_Bool)0);
  tmp = strcmp(p, "fgh");
  if (tmp != 0) {
    abort();
  } else {
    tmp___0 = strcmp((char const   *)(buf), "abcde");
    if (tmp___0 != 0) {
      abort();
    }
  }
  p = "ABCDEFG\"HI";
  foo(& p, buf, (_Bool)0, (_Bool)1);
  tmp___1 = strcmp(p, "HI");
  if (tmp___1 != 0) {
    abort();
  } else {
    tmp___2 = strcmp((char const   *)(buf), "ABCDEFG");
    if (tmp___2 != 0) {
      abort();
    }
  }
  p = "abcd\"e\'fgh";
  foo(& p, buf, (_Bool)1, (_Bool)1);
  tmp___3 = strcmp(p, "e\'fgh");
  if (tmp___3 != 0) {
    abort();
  } else {
    tmp___4 = strcmp((char const   *)(buf), "abcd");
    if (tmp___4 != 0) {
      abort();
    }
  }
  p = "ABCDEF\'G\"HI";
  foo(& p, buf, (_Bool)1, (_Bool)1);
  tmp___5 = strcmp(p, "G\"HI");
  if (tmp___5 != 0) {
    abort();
  } else {
    tmp___6 = strcmp((char const   *)(buf), "ABCDEF");
    if (tmp___6 != 0) {
      abort();
    }
  }
  p = "abcdef@gh";
  foo(& p, buf, (_Bool)0, (_Bool)0);
  tmp___7 = strcmp(p, "gh");
  if (tmp___7 != 0) {
    abort();
  } else {
    tmp___8 = strcmp((char const   *)(buf), "abcdef");
    if (tmp___8 != 0) {
      abort();
    }
  }
  return (0);
}
}
