/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
unsigned int foo(unsigned long long x ) 
{ unsigned int u ;

  {
  if (x == 0ULL) {
    return (0U);
  }
  u = (unsigned int )(x >> 32);
  return (u);
}
}
unsigned long long bar(unsigned short x ) 
{ 

  {
  return ((unsigned long long )x << 32);
}
}
int main(void) 
{ unsigned int tmp ;
  unsigned int tmp___0 ;
  unsigned int tmp___1 ;
  unsigned long long tmp___2 ;
  unsigned long long tmp___3 ;

  {
  if (sizeof(long long ) != 8UL) {
    return (0);
  }
  tmp = foo(0ULL);
  if (tmp != 0U) {
    abort();
  }
  tmp___0 = foo(4294967295ULL);
  if (tmp___0 != 0U) {
    abort();
  }
  tmp___1 = foo(163192045312ULL);
  if (tmp___1 != 37U) {
    abort();
  }
  tmp___2 = bar((unsigned short)0);
  if (tmp___2 != 0ULL) {
    abort();
  }
  tmp___3 = bar((unsigned short)37);
  if (tmp___3 != 158913789952ULL) {
    abort();
  }
  return (0);
}
}
