/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "20050119-2.c"
enum __anonenum_E_1 {
    A = 0,
    B = 1,
    C = 2,
    D = 3
} ;
#line 2 "20050119-2.c"
typedef enum __anonenum_E_1 E;
#line 4 "20050119-2.c"
struct S {
   E /* mode(__byte__) */   a ;
   E /* mode(__byte__) */   b ;
   E /* mode(__byte__) */   c ;
   E /* mode(__byte__) */   d ;
};
#line 11
extern void abort(void) ;
#line 12
extern void exit(int  ) ;
#line 14 "20050119-2.c"
E foo(struct S *s ) 
{ 

  {
#line 17
  if ((unsigned int /* mode(__byte__) */   )s->a != (unsigned int /* mode(__byte__) */   )s->b) {
#line 18
    abort();
  }
#line 19
  if ((unsigned int /* mode(__byte__) */   )s->c != (unsigned int /* mode(__byte__) */   )2) {
#line 20
    abort();
  }
#line 21
  return ((enum __anonenum_E_1 )s->d);
}
}
#line 24 "20050119-2.c"
int main(void) 
{ struct S s[2] ;
  E tmp ;

  {
#line 28
  s[0].a = (enum __anonenum_E_1  /* mode(__byte__) */  )1;
#line 29
  s[0].b = (enum __anonenum_E_1  /* mode(__byte__) */  )1;
#line 30
  s[0].c = (enum __anonenum_E_1  /* mode(__byte__) */  )2;
#line 31
  s[0].d = (enum __anonenum_E_1  /* mode(__byte__) */  )3;
#line 32
  s[1].a = (enum __anonenum_E_1  /* mode(__byte__) */  )3;
#line 33
  s[1].b = (enum __anonenum_E_1  /* mode(__byte__) */  )2;
#line 34
  s[1].c = (enum __anonenum_E_1  /* mode(__byte__) */  )1;
#line 35
  s[1].d = (enum __anonenum_E_1  /* mode(__byte__) */  )0;
#line 36
  tmp = foo(s);
#line 36
  if ((unsigned int )tmp != 3U) {
#line 37
    abort();
  }
#line 38
  exit(0);
}
}
