/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 1 "20050107-1.c"
enum __anonenum_B_1 {
    C = 1,
    D = 2
} ;
#line 1 "20050107-1.c"
typedef enum __anonenum_B_1 B;
#line 4 "20050107-1.c"
struct S {
   B /* mode(byte) */   a ;
   B /* mode(byte) */   b ;
};
#line 2
extern void abort(void) ;
#line 10 "20050107-1.c"
void foo(struct S *x ) 
{ 

  {
#line 13
  if ((unsigned int /* mode(byte) */   )x->a != (unsigned int /* mode(byte) */   )1) {
#line 14
    abort();
  } else {
#line 13
    if ((unsigned int /* mode(byte) */   )x->b != (unsigned int /* mode(byte) */   )2) {
#line 14
      abort();
    }
  }
#line 15
  return;
}
}
#line 17 "20050107-1.c"
int main(void) 
{ struct S s ;

  {
#line 21
  s.a = (enum __anonenum_B_1  /* mode(byte) */  )1;
#line 22
  s.b = (enum __anonenum_B_1  /* mode(byte) */  )2;
#line 23
  foo(& s);
#line 24
  return (0);
}
}
