/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef unsigned long size_t;
struct __anonstruct_Struct1_21 {
   short a ;
   unsigned short b ;
   unsigned short c ;
   unsigned long long Count ;
   long long Count2 ;
} __attribute__((__packed__)) ;
typedef struct __anonstruct_Struct1_21 Struct1;
struct __anonstruct_Struct2_22 {
   short a ;
   unsigned short b ;
   unsigned short c ;
   unsigned long long d ;
   long long e ;
   long long f ;
} __attribute__((__packed__)) ;
typedef struct __anonstruct_Struct2_22 Struct2;
union __anonunion_Union_23 {
   Struct1 a ;
   Struct2 b ;
};
typedef union __anonunion_Union_23 Union;
struct __anonstruct_Struct3_24 {
   int Count ;
   Union List[] ;
} __attribute__((__packed__)) ;
typedef struct __anonstruct_Struct3_24 Struct3;
extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__malloc__,
__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern void *memset(void * , int  , size_t  ) ;
unsigned long long ( __attribute__((__noinline__)) Sum)(Struct3 *instrs ) ;
unsigned long long ( __attribute__((__noinline__)) Sum)(Struct3 *instrs ) 
{ unsigned long long count ;
  int i ;

  {
  count = 0ULL;
  i = 0;
  while (i < instrs->Count) {
    count += instrs->List[i].a.Count;
    i ++;
  }
  return (count);
}
}
long long ( __attribute__((__noinline__)) Sum2)(Struct3 *instrs ) ;
long long ( __attribute__((__noinline__)) Sum2)(Struct3 *instrs ) 
{ long long count ;
  int i ;

  {
  count = 0LL;
  i = 0;
  while (i < instrs->Count) {
    count += instrs->List[i].a.Count2;
    i ++;
  }
  return (count);
}
}
int main(void) 
{ Struct3 *p ;
  void *tmp ;
  unsigned long long tmp___0 ;
  long long tmp___1 ;

  {
  tmp = malloc(sizeof(int ) + 3UL * sizeof(Union ));
  p = (Struct3 *)tmp;
  memset((void *)p, 0, sizeof(int ) + 3UL * sizeof(Union ));
  p->Count = 3;
  p->List[0].a.Count = 555ULL;
  p->List[1].a.Count = 999ULL;
  p->List[2].a.Count = 4311810305ULL;
  p->List[0].a.Count2 = 555LL;
  p->List[1].a.Count2 = 999LL;
  p->List[2].a.Count2 = 4311810305LL;
  tmp___0 = Sum(p);
  if (tmp___0 != 4311811859ULL) {
    abort();
  }
  tmp___1 = Sum2(p);
  if (tmp___1 != 4311811859LL) {
    abort();
  }
  return (0);
}
}
