/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 6 "20060929-1.c"
void foo(int **p , int *q ) 
{ int **tmp ;
  int *tmp___0 ;
  int *tmp___1 ;

  {
#line 9
  tmp = p;
#line 9
  p ++;
#line 9
  tmp___0 = *tmp;
#line 9
  (*tmp) ++;
#line 9
  tmp___1 = q;
#line 9
  q ++;
#line 9
  *tmp___0 = *tmp___1;
#line 10
  return;
}
}
#line 12 "20060929-1.c"
void bar(int **p , int *q ) 
{ int *tmp ;
  int **tmp___0 ;
  int *tmp___1 ;

  {
#line 15
  tmp = q;
#line 15
  q ++;
#line 15
  *(*p) = *tmp;
#line 16
  tmp___0 = p;
#line 16
  p ++;
#line 16
  tmp___1 = *tmp___0;
#line 16
  (*tmp___0) ++;
#line 17
  return;
}
}
#line 19 "20060929-1.c"
void baz(int **p , int *q ) 
{ int *tmp ;
  int **tmp___0 ;

  {
#line 22
  tmp = q;
#line 22
  q ++;
#line 22
  *(*p) = *tmp;
#line 23
  tmp___0 = p;
#line 23
  p ++;
#line 23
  (*tmp___0) ++;
#line 24
  return;
}
}
#line 26 "20060929-1.c"
int main(void) 
{ int i ;
  int j ;
  int *p ;

  {
#line 28
  i = 42;
#line 28
  j = 0;
#line 29
  p = & i;
#line 30
  foo(& p, & j);
#line 31
  if ((unsigned long )(p - 1) != (unsigned long )(& i)) {
#line 32
    abort();
  } else {
#line 31
    if (j != 0) {
#line 32
      abort();
    } else {
#line 31
      if (i != 0) {
#line 32
        abort();
      }
    }
  }
#line 33
  i = 43;
#line 34
  p = & i;
#line 35
  bar(& p, & j);
#line 36
  if ((unsigned long )(p - 1) != (unsigned long )(& i)) {
#line 37
    abort();
  } else {
#line 36
    if (j != 0) {
#line 37
      abort();
    } else {
#line 36
      if (i != 0) {
#line 37
        abort();
      }
    }
  }
#line 38
  i = 44;
#line 39
  p = & i;
#line 40
  baz(& p, & j);
#line 41
  if ((unsigned long )(p - 1) != (unsigned long )(& i)) {
#line 42
    abort();
  } else {
#line 41
    if (j != 0) {
#line 42
      abort();
    } else {
#line 41
      if (i != 0) {
#line 42
        abort();
      }
    }
  }
#line 43
  return (0);
}
}
