/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 7 "20060930-1.c"
int ( __attribute__((__noinline__)) bar)(int a , int b ) ;
#line 8 "20060930-1.c"
int ( __attribute__((__noinline__)) bar)(int a , int b ) 
{ 

  {
#line 10
  if (b != 1) {
#line 11
    abort();
  }
#line 12
  return (0);
}
}
#line 15
void ( __attribute__((__noinline__)) foo)(int e , int n ) ;
#line 16 "20060930-1.c"
void ( __attribute__((__noinline__)) foo)(int e , int n ) 
{ int i ;
  int bb2 ;
  int bb5 ;

  {
#line 20
  if (e > 0) {
#line 21
    e = - e;
  }
#line 23
  i = 0;
#line 23
  while (i < n) {
#line 25
    if (e >= 0) {
#line 27
      bb2 = 0;
#line 28
      bb5 = 0;
    } else {
#line 32
      bb5 = - e;
#line 33
      bb2 = bb5;
    }
#line 36
    bar(bb5, bb2);
#line 23
    i ++;
  }
#line 38
  return;
}
}
#line 40 "20060930-1.c"
int main(void) 
{ 

  {
#line 42
  foo(1, 1);
#line 43
  return (0);
}
}
