/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 7 "20060910-1.c"
struct input_ty {
   unsigned char *buffer_position ;
   unsigned char *buffer_end ;
};
#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 13 "20060910-1.c"
int input_getc_complicated(struct input_ty *x ) 
{ 

  {
#line 13
  return (0);
}
}
#line 15 "20060910-1.c"
int check_header(struct input_ty *deeper ) 
{ unsigned int len ;
  unsigned char *tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 18
  len = 0U;
#line 18
  while (len < 6U) {
#line 19
    if ((unsigned long )deeper->buffer_position < (unsigned long )deeper->buffer_end) {
#line 19
      tmp = deeper->buffer_position;
#line 19
      (deeper->buffer_position) ++;
#line 19
      tmp___1 = (int )*tmp;
    } else {
#line 19
      tmp___0 = input_getc_complicated(deeper);
#line 19
      tmp___1 = tmp___0;
    }
#line 19
    if (tmp___1 < 0) {
#line 22
      return (0);
    }
#line 18
    len ++;
  }
#line 23
  return (1);
}
}
#line 26 "20060910-1.c"
struct input_ty s  ;
#line 27 "20060910-1.c"
unsigned char b[6]  ;
#line 29 "20060910-1.c"
int main(void) 
{ int tmp ;

  {
#line 31
  s.buffer_position = b;
#line 32
  s.buffer_end = b + sizeof(b);
#line 33
  tmp = check_header(& s);
#line 33
  if (! tmp) {
#line 34
    abort();
  }
#line 35
  if ((unsigned long )s.buffer_position != (unsigned long )s.buffer_end) {
#line 36
    abort();
  }
#line 37
  return (0);
}
}
