/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 7 "20060905-1.c"
char volatile   s[256][3]  ;
#line 9 "20060905-1.c"
char g  ;
#line 11 "20060905-1.c"
static void dummy(char a ) 
{ 

  {
#line 13
  g = a;
#line 14
  return;
}
}
#line 16 "20060905-1.c"
static int foo(void) 
{ int i ;
  int j ;

  {
#line 18
  j = 0;
#line 20
  i = 0;
#line 20
  while (i < 256) {
#line 21
    if (i >= 128) {
#line 21
      if (i < 256) {
#line 23
        dummy((char )s[i - 128][0]);
#line 24
        j ++;
      }
    }
#line 20
    i ++;
  }
#line 27
  return (j);
}
}
#line 30 "20060905-1.c"
int main(void) 
{ int tmp ;

  {
#line 32
  tmp = foo();
#line 32
  if (tmp != 128) {
#line 33
    abort();
  }
#line 35
  return (0);
}
}
