/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 6 "20071205-1.c"
int foo(int x ) 
{ 

  {
#line 9
  return (((x << 8) & 65535) | 255);
}
}
#line 12 "20071205-1.c"
int main(void) 
{ int tmp ;
  int tmp___0 ;

  {
#line 14
  tmp = foo(50);
#line 14
  if (tmp != 13055) {
#line 15
    abort();
  } else {
#line 14
    tmp___0 = foo(372);
#line 14
    if (tmp___0 != 29951) {
#line 15
      abort();
    }
  }
#line 16
  return (0);
}
}
