/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 4 "20071029-1.c"
struct __anonstruct_f_2 {
   int f1 ;
   int f2 ;
   int f3 ;
   int f4 ;
   int f5 ;
   int f6 ;
   int f7 ;
   int f8 ;
   long f9 ;
   long f10 ;
   int f11 ;
};
#line 4 "20071029-1.c"
union __anonunion_T_1 {
   struct __anonstruct_f_2 f ;
   char s[56] ;
   long a ;
};
#line 4 "20071029-1.c"
typedef union __anonunion_T_1 T;
#line 1
extern void exit(int  ) ;
#line 2
extern void abort(void) ;
#line 20
void ( __attribute__((__noinline__)) test)(T *t ) ;
#line 20 "20071029-1.c"
static int i  =    11;
#line 16 "20071029-1.c"
void ( __attribute__((__noinline__)) test)(T *t ) 
{ int tmp ;

  {
#line 21
  tmp = i;
#line 21
  i ++;
#line 21
  if (t->f.f1 != tmp) {
#line 22
    abort();
  }
#line 23
  if (t->f.f2) {
#line 25
    abort();
  } else {
#line 23
    if (t->f.f3) {
#line 25
      abort();
    } else {
#line 23
      if (t->f.f4) {
#line 25
        abort();
      } else {
#line 23
        if (t->f.f5) {
#line 25
          abort();
        } else {
#line 23
          if (t->f.f6) {
#line 25
            abort();
          } else {
#line 23
            if (t->f.f7) {
#line 25
              abort();
            } else {
#line 23
              if (t->f.f8) {
#line 25
                abort();
              } else {
#line 23
                if (t->f.f9) {
#line 25
                  abort();
                } else {
#line 23
                  if (t->f.f10) {
#line 25
                    abort();
                  } else {
#line 23
                    if (t->f.f11) {
#line 25
                      abort();
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
#line 26
  if (i == 20) {
#line 27
    exit(0);
  }
#line 28
  return;
}
}
#line 30 "20071029-1.c"
void ( __attribute__((__noinline__)) foo)(int i___0 ) 
{ T t ;
  T __constr_expr_0 ;

  {
  again: 
#line 36
  i___0 ++;
#line 36
  __constr_expr_0.f.f1 = i___0;
#line 36
  __constr_expr_0.f.f2 = 0;
#line 36
  __constr_expr_0.f.f3 = 0;
#line 36
  __constr_expr_0.f.f4 = 0;
#line 36
  __constr_expr_0.f.f5 = 0;
#line 36
  __constr_expr_0.f.f6 = 0;
#line 36
  __constr_expr_0.f.f7 = 0;
#line 36
  __constr_expr_0.f.f8 = 0;
#line 36
  __constr_expr_0.f.f9 = 0L;
#line 36
  __constr_expr_0.f.f10 = 0L;
#line 36
  __constr_expr_0.f.f11 = 0;
#line 36
  t = __constr_expr_0;
#line 37
  test(& t);
  goto again;
}
}
#line 41 "20071029-1.c"
int main(void) 
{ T *t1 ;
  T *t2 ;
  int cnt ;
  T __constr_expr_0 ;
  int tmp ;

  {
#line 44
  cnt = 0;
#line 45
  t1 = (T *)0;
  loop: 
#line 47
  t2 = t1;
#line 48
  tmp = cnt;
#line 48
  cnt ++;
#line 48
  __constr_expr_0.f.f1 = 0;
#line 48
  __constr_expr_0.f.f2 = 0;
#line 48
  __constr_expr_0.f.f3 = 0;
#line 48
  __constr_expr_0.f.f4 = 0;
#line 48
  __constr_expr_0.f.f5 = 0;
#line 48
  __constr_expr_0.f.f6 = 0;
#line 48
  __constr_expr_0.f.f7 = 0;
#line 48
  __constr_expr_0.f.f8 = 0;
#line 48
  __constr_expr_0.f.f9 = (long )tmp;
#line 48
  __constr_expr_0.f.f10 = 0L;
#line 48
  __constr_expr_0.f.f11 = 0;
#line 48
  t1 = & __constr_expr_0;
#line 49
  if (cnt < 3) {
    goto loop;
  }
#line 51
  if ((unsigned long )t1 != (unsigned long )t2) {
#line 52
    abort();
  } else {
#line 51
    if (t1->f.f9 != 2L) {
#line 52
      abort();
    }
  }
#line 53
  foo(10);
#line 54
  return (0);
}
}
