/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "20070212-1.c"
struct f {
   int i ;
};
#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 7 "20070212-1.c"
int g(int i , int c , struct f *ff , int *p ) 
{ int *t ;

  {
#line 10
  if (c) {
#line 11
    t = & i;
  } else {
#line 13
    t = & ff->i;
  }
#line 14
  *p = 0;
#line 15
  return (*t);
}
}
#line 20 "20070212-1.c"
int main(void) 
{ struct f f ;
  int tmp ;

  {
#line 23
  f.i = 1;
#line 24
  tmp = g(5, 0, & f, & f.i);
#line 24
  if (tmp != 0) {
#line 25
    abort();
  }
#line 26
  return (0);
}
}
