/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 6 "../../lib/includes/stddef.h"
typedef unsigned int size_t___0;
#line 8 "20071219-1.c"
struct S {
   char s[25] ;
};
#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 6 "20071219-1.c"
extern void *memset(void *s , int c , size_t___0 n ) ;
#line 13 "20071219-1.c"
struct S *p  ;
#line 15 "20071219-1.c"
void ( __attribute__((__noinline__)) foo)(struct S *x , int set ) 
{ int i ;

  {
#line 19
  i = 0;
#line 19
  while ((unsigned long )i < sizeof(x->s)) {
#line 20
    if ((int )x->s[i] != 0) {
#line 21
      abort();
    } else {
#line 22
      if (set) {
#line 23
        x->s[i] = (char )set;
      }
    }
#line 19
    i ++;
  }
#line 24
  p = x;
#line 25
  return;
}
}
#line 27 "20071219-1.c"
void ( __attribute__((__noinline__)) test1)(void) 
{ struct S a ;
  struct S b ;

  {
#line 31
  memset((void *)(& a.s), '\000', (unsigned int )sizeof(a.s));
#line 32
  foo(& a, 0);
#line 33
  b = a;
#line 34
  foo(& b, 1);
#line 35
  b = a;
#line 36
  b = b;
#line 37
  foo(& b, 0);
#line 38
  return;
}
}
#line 40 "20071219-1.c"
void ( __attribute__((__noinline__)) test2)(void) 
{ struct S a ;
  struct S b ;

  {
#line 44
  memset((void *)(& a.s), '\000', (unsigned int )sizeof(a.s));
#line 45
  foo(& a, 0);
#line 46
  b = a;
#line 47
  foo(& b, 1);
#line 48
  b = a;
#line 49
  b = *p;
#line 50
  foo(& b, 0);
#line 51
  return;
}
}
#line 53 "20071219-1.c"
void ( __attribute__((__noinline__)) test3)(void) 
{ struct S a ;
  struct S b ;

  {
#line 57
  memset((void *)(& a.s), '\000', (unsigned int )sizeof(a.s));
#line 58
  foo(& a, 0);
#line 59
  b = a;
#line 60
  foo(& b, 1);
#line 61
  *p = a;
#line 62
  *p = b;
#line 63
  foo(& b, 0);
#line 64
  return;
}
}
#line 66 "20071219-1.c"
int main(void) 
{ 

  {
#line 68
  test1();
#line 69
  test2();
#line 70
  test3();
#line 71
  return (0);
}
}
