/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "20070212-3.c"
struct foo {
   int i ;
   int j ;
};
#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "20070212-3.c"
int bar(struct foo *k , int k2 , int f , int f2 ) 
{ int *p ;
  int *q ;
  int res ;

  {
#line 8
  if (f) {
#line 9
    p = & k->i;
  } else {
#line 11
    p = & k->j;
  }
#line 12
  res = *p;
#line 13
  k->i = 1;
#line 14
  if (f2) {
#line 15
    q = p;
  } else {
#line 17
    q = & k2;
  }
#line 18
  return (res + *q);
}
}
#line 23 "20070212-3.c"
int main(void) 
{ struct foo k ;
  int tmp ;

  {
#line 26
  k.i = 0;
#line 27
  k.j = 1;
#line 28
  tmp = bar(& k, 1, 1, 1);
#line 28
  if (tmp != 1) {
#line 29
    abort();
  }
#line 30
  return (0);
}
}
