/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 6 "20071216-1.c"
static int x  ;
#line 8 "20071216-1.c"
int ( __attribute__((__noinline__)) bar)(void) 
{ 

  {
#line 12
  return (x);
}
}
#line 15 "20071216-1.c"
int foo(void) 
{ long b ;
  int tmp ;

  {
#line 18
  tmp = bar();
#line 18
  b = (long )tmp;
#line 19
  if ((unsigned long )b < 0xfffff001UL) {
#line 20
    return ((int )b);
  }
#line 21
  if (- b != 38L) {
#line 22
    b = -2L;
  }
#line 23
  return ((int )(b + 1L));
}
}
#line 26 "20071216-1.c"
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 28
  x = 26;
#line 29
  tmp = foo();
#line 29
  if (tmp != 26) {
#line 30
    abort();
  }
#line 31
  x = -39;
#line 32
  tmp___0 = foo();
#line 32
  if (tmp___0 != -1) {
#line 33
    abort();
  }
#line 34
  x = -38;
#line 35
  tmp___1 = foo();
#line 35
  if (tmp___1 != -37) {
#line 36
    abort();
  }
#line 37
  return (0);
}
}
