/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 6 "20080506-2.c"
void ( __attribute__((__noinline__)) foo)(int ** __restrict  p , int ** __restrict  q ) 
{ 

  {
#line 9
  *(*(p + 0)) = 1;
#line 10
  *(*(q + 0)) = 2;
#line 11
  if (*(*(p + 0)) != 2) {
#line 12
    abort();
  }
#line 13
  return;
}
}
#line 15 "20080506-2.c"
int main(void) 
{ int a ;
  int *p1 ;
  int *p2 ;

  {
#line 18
  p1 = & a;
#line 18
  p2 = & a;
#line 19
  foo((int ** __restrict  )(& p1), (int ** __restrict  )(& p2));
#line 20
  return (0);
}
}
