/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 6 "20080813-1.c"
void foo(unsigned short x ) 
{ signed char y ;

  {
#line 9
  y = (signed char)-1;
#line 10
  if ((int )x == (int )y) {
#line 11
    abort();
  }
#line 12
  return;
}
}
#line 14 "20080813-1.c"
void bar(unsigned short x ) 
{ unsigned char y ;

  {
#line 17
  y = (unsigned char)255;
#line 18
  if ((int )x == (int )y) {
#line 19
    abort();
  }
#line 20
  return;
}
}
#line 22 "20080813-1.c"
int main(void) 
{ 

  {
#line 24
  if (sizeof(int ) == sizeof(short )) {
#line 25
    return (0);
  }
#line 26
  foo((unsigned short)65535);
#line 27
  if (sizeof(short ) > 1UL) {
#line 28
    bar((unsigned short)65535);
  }
#line 29
  return (0);
}
}
