/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 3 "20080408-1.c"
int main(void) 
{ short ssi ;
  unsigned short usi ;
  int fail ;

  {
#line 5
  ssi = (short)126;
#line 6
  usi = (unsigned short)65280;
#line 7
  fail = ! ((int )ssi < (int )usi);
#line 8
  if (fail) {
#line 9
    abort();
  }
#line 10
  return (0);
}
}
