/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int main(void) 
{ short ssi ;
  unsigned short usi ;
  int fail ;

  {
  ssi = (short)126;
  usi = (unsigned short)65280;
  fail = ! ((int )ssi < (int )usi);
  if (fail) {
    abort();
  }
  return (0);
}
}
