/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
static int i  ;
static int *p  =    & i;
int ( __attribute__((__noinline__)) foo)(int *q ) 
{ 

  {
  *p = 1;
  *q = 2;
  return (*p);
}
}
int ( __attribute__((__noinline__)) bar)(int *q ) 
{ 

  {
  *q = 2;
  *p = 1;
  return (*q);
}
}
int main(void) 
{ int j ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;

  {
  j = 0;
  tmp = foo(& i);
  if (tmp != 2) {
    abort();
  }
  tmp___0 = bar(& i);
  if (tmp___0 != 1) {
    abort();
  }
  tmp___1 = foo(& j);
  if (tmp___1 != 1) {
    abort();
  }
  if (j != 2) {
    abort();
  }
  tmp___2 = bar(& j);
  if (tmp___2 != 2) {
    abort();
  }
  if (j != 2) {
    abort();
  }
  return (0);
}
}
