/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
void ( __attribute__((__noinline__)) foo)(int ** __restrict  p , int ** __restrict  q ) 
{ 

  {
  *(*(p + 0)) = 1;
  *(*(q + 0)) = 2;
  if (*(*(p + 0)) != 2) {
    abort();
  }
  return;
}
}
int main(void) 
{ int a ;
  int *p1 ;
  int *p2 ;

  {
  p1 = & a;
  p2 = & a;
  foo((int ** __restrict  )(& p1), (int ** __restrict  )(& p2));
  return (0);
}
}
