/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "20091229-1.c"
long long foo(long long v ) 
{ 

  {
#line 2
  return (v / (-0x7FFFFFFF-1));
}
}
#line 3 "20091229-1.c"
int main(void) 
{ long long tmp ;

  {
#line 3
  tmp = foo(2147483648LL);
#line 3
  if (tmp != -1LL) {
#line 3
    abort();
  }
#line 3
  exit(0);
}
}
