/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int bar(int foo ) 
{ 

  {
  return ((int )((unsigned long long )((long long )foo) / 8ULL));
}
}
int main(void) 
{ int tmp ;

  {
  if (sizeof(long long ) > sizeof(int )) {
    tmp = bar(-1);
    if (tmp != -1) {
      abort();
    }
  }
  return (0);
}
}
