/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 6 "920410-1.c"
int main(void) 
{ int d[40000] ;

  {
#line 6
  d[0] = 0;
#line 6
  exit(0);
}
}
