/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "920429-1.c"
typedef unsigned char t;
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "920429-1.c"
int i  ;
#line 2 "920429-1.c"
int j  ;
#line 3 "920429-1.c"
t *f(t *p ) 
{ t c ;
  t *tmp ;

  {
#line 3
  tmp = p;
#line 3
  p ++;
#line 3
  c = *tmp;
#line 3
  if ((int )c & 2) {
#line 3
    i = 1;
  } else {
#line 3
    i = 0;
  }
#line 3
  j = ((int )c & 7) + 1;
#line 3
  return (p);
}
}
#line 4 "920429-1.c"
int main(void) 
{ t *p0 ;
  t *p1 ;

  {
#line 4
  p0 = (t *)"ab";
#line 4
  p1 = f(p0);
#line 4
  if ((unsigned long )(p0 + 1) != (unsigned long )p1) {
#line 4
    abort();
  }
#line 4
  exit(0);
}
}
