/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 1 "920731-1.c"
extern void exit(int status ) ;
#line 2
extern void abort(void) ;
#line 3 "920731-1.c"
int f(int x ) 
{ int i ;

  {
#line 3
  i = 0;
#line 3
  while (1) {
#line 3
    if (i < 8) {
#line 3
      if (! ((x & 1) == 0)) {
#line 3
        break;
      }
    } else {
#line 3
      break;
    }
#line 3
    x >>= 1;
#line 3
    i ++;
  }
#line 3
  return (i);
}
}
#line 4 "920731-1.c"
int main(void) 
{ int tmp ;

  {
#line 4
  tmp = f(4);
#line 4
  if (tmp != 2) {
#line 4
    abort();
  }
#line 4
  exit(0);
}
}
