/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 1 "920721-3.c"
extern void exit(int status ) ;
#line 2
extern void abort(void) ;
#line 3 "920721-3.c"
__inline static int fu(unsigned short data ) 
{ 

  {
#line 5
  return ((int )data);
}
}
#line 7 "920721-3.c"
void ru(int i ) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 9
  tmp = i;
#line 9
  i ++;
#line 9
  tmp___0 = fu((unsigned short )tmp);
#line 9
  if (tmp___0 != 5) {
#line 9
    abort();
  }
#line 10
  i ++;
#line 10
  tmp___1 = fu((unsigned short )i);
#line 10
  if (tmp___1 != 7) {
#line 10
    abort();
  }
#line 11
  return;
}
}
#line 12 "920721-3.c"
__inline static int fs(short data ) 
{ 

  {
#line 14
  return ((int )data);
}
}
#line 16 "920721-3.c"
void rs(int i ) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 18
  tmp = i;
#line 18
  i ++;
#line 18
  tmp___0 = fs((short )tmp);
#line 18
  if (tmp___0 != 5) {
#line 18
    abort();
  }
#line 19
  i ++;
#line 19
  tmp___1 = fs((short )i);
#line 19
  if (tmp___1 != 7) {
#line 19
    abort();
  }
#line 20
  return;
}
}
#line 23 "920721-3.c"
int main(void) 
{ 

  {
#line 25
  ru(5);
#line 26
  rs(5);
#line 27
  exit(0);
}
}
