/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "920829-1.c"
long long c  =    2863311530LL;
#line 2 "920829-1.c"
long long c3  =    8589934590LL;
#line 3 "920829-1.c"
int main(void) 
{ 

  {
#line 3
  if (c * 3LL != c3) {
#line 3
    abort();
  }
#line 3
  exit(0);
}
}
