/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 8 "../../lib/includes/string.h"
typedef unsigned int size_t___0;
#line 5 "920810-1.c"
struct __anonstruct_t_4 {
   void *super ;
   int name ;
   int size ;
};
#line 5 "920810-1.c"
typedef struct __anonstruct_t_4 t;
#line 16 "../../lib/includes/string.h"
extern void *memset(void *ptr , int value , size_t___0 num ) ;
#line 17
extern void *memcpy(void *destination , void const   *source , size_t___0 num ) ;
#line 13 "../../lib/includes/stdlib.h"
extern void *malloc(size_t___0 size ) ;
#line 17
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 6 "920810-1.c"
t *f(t *clas , int size ) 
{ t *child ;
  void *tmp ;

  {
#line 8
  tmp = malloc((unsigned int )size);
#line 8
  child = (t *)tmp;
#line 9
  memcpy((void *)child, (void const   *)clas, (unsigned int )clas->size);
#line 10
  child->super = (void *)clas;
#line 11
  child->name = 0;
#line 12
  child->size = size;
#line 13
  return (child);
}
}
#line 15 "920810-1.c"
int main(void) 
{ t foo ;
  t *bar ;

  {
#line 18
  memset((void *)(& foo), 37, (unsigned int )sizeof(t ));
#line 19
  foo.size = (int )sizeof(t );
#line 20
  bar = f(& foo, (int )sizeof(t ));
#line 21
  if ((unsigned long )bar->super != (unsigned long )(& foo)) {
#line 21
    abort();
  } else {
#line 21
    if (bar->name != 0) {
#line 21
      abort();
    } else {
#line 21
      if ((unsigned long )bar->size != sizeof(t )) {
#line 21
        abort();
      }
    }
  }
#line 22
  exit(0);
}
}
