/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern void exit(int status ) ;
extern void abort(void) ;
int f(int a ) 
{ 

  {
  switch (a) {
  case 1026: 
  return (a + 1);
  case 1027: 
  return (a + 2);
  case 1028: 
  return (a + 3);
  case 1029: 
  return (a + 4);
  case 1030: 
  return (1);
  case 1031: 
  return (4);
  }
  return (0);
}
}
int main(void) 
{ int tmp ;

  {
  tmp = f(1);
  if (tmp) {
    abort();
  }
  exit(0);
}
}
