/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
unsigned long *f(unsigned long *p ) 
{ unsigned long a ;
  unsigned long *tmp ;

  {
  tmp = p;
  p ++;
  a = *tmp >> 24;
  return (p + a);
}
}
int main(void) 
{ unsigned long x ;
  unsigned long *tmp ;

  {
  x = 2147483648UL;
  tmp = f(& x);
  if ((unsigned long )tmp != (unsigned long )(& x + 129)) {
    abort();
  }
  exit(0);
}
}
