/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "920922-1.c"
unsigned long *f(unsigned long *p ) 
{ unsigned long a ;
  unsigned long *tmp ;

  {
#line 5
  tmp = p;
#line 5
  p ++;
#line 5
  a = *tmp >> 24;
#line 6
  return (p + a);
}
}
#line 9 "920922-1.c"
int main(void) 
{ unsigned long x ;
  unsigned long *tmp ;

  {
#line 11
  x = 2147483648UL;
#line 12
  tmp = f(& x);
#line 12
  if ((unsigned long )tmp != (unsigned long )(& x + 129)) {
#line 13
    abort();
  }
#line 14
  exit(0);
}
}
