/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 14 "920908-2.c"
struct T {
   unsigned int i : 8 ;
   unsigned int c : 24 ;
};
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 19 "920908-2.c"
int f(struct T t ) 
{ struct T s[1] ;

  {
#line 22
  s[0] = t;
#line 23
  return ((int )((char )s[0].c));
}
}
#line 25 "920908-2.c"
int main(void) 
{ struct T t ;
  int tmp ;

  {
#line 28
  t.i = 255U;
#line 29
  t.c = 16776977U;
#line 30
  tmp = f(t);
#line 30
  if (tmp != 17) {
#line 30
    abort();
  }
#line 31
  exit(0);
}
}
