/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 5 "921016-1.c"
struct __anonstruct_l_3 {
   int m : 11 ;
};
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "921016-1.c"
int main(void) 
{ int j ;
  struct __anonstruct_l_3 l ;

  {
#line 4
  j = 1081;
#line 9
  l.m = j;
#line 9
  if (l.m == j) {
#line 9
    abort();
  }
#line 10
  exit(0);
}
}
