/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "921013-1.c"
void f(int *d , float *x , float *y , int n ) 
{ int *tmp ;
  float *tmp___0 ;
  float *tmp___1 ;
  int tmp___2 ;

  {
#line 7
  while (1) {
#line 7
    tmp___2 = n;
#line 7
    n --;
#line 7
    if (! tmp___2) {
#line 7
      break;
    }
#line 7
    tmp = d;
#line 7
    d ++;
#line 7
    tmp___0 = x;
#line 7
    x ++;
#line 7
    tmp___1 = y;
#line 7
    y ++;
#line 7
    *tmp = *tmp___0 == *tmp___1;
  }
#line 8
  return;
}
}
#line 10 "921013-1.c"
int main(void) 
{ int r[4] ;
  float a[4] ;
  float b[4] ;
  int i ;

  {
#line 13
  a[0] = (float )5;
#line 13
  a[1] = (float )1;
#line 13
  a[2] = (float )3;
#line 13
  a[3] = (float )5;
#line 14
  b[0] = (float )2;
#line 14
  b[1] = (float )4;
#line 14
  b[2] = (float )3;
#line 14
  b[3] = (float )0;
#line 16
  f(r, a, b, 4);
#line 17
  i = 0;
#line 17
  while (i < 4) {
#line 18
    if ((a[i] == b[i]) != r[i]) {
#line 19
      abort();
    }
#line 17
    i ++;
  }
#line 20
  exit(0);
}
}
