/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct __anonstruct_struct_list_21 {
   float wsx ;
};
typedef struct __anonstruct_struct_list_21 struct_list;
typedef struct_list *list_t;
struct __anonstruct_vector_t_22 {
   float x ;
   float y ;
};
typedef struct __anonstruct_vector_t_22 vector_t;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
void w(float x , float y ) 
{ 

  {
  return;
}
}
void f1(float x , float y ) 
{ 

  {
  if (x != (float )0) {
    abort();
  } else {
    if (y != (float )0) {
      abort();
    }
  }
  return;
}
}
void f2(float x , float y ) 
{ 

  {
  if (x != (float )1) {
    abort();
  } else {
    if (y != (float )1) {
      abort();
    }
  }
  return;
}
}
void gitter(int count , vector_t *pos , list_t list , int *nww , vector_t *limit ,
            float r ) 
{ float d ;

  {
  f1((limit + 0)->x, (limit + 0)->y);
  f2((limit + 1)->x, (limit + 1)->y);
  *nww = 0;
  d = (pos + 0)->x;
  if ((double )d <= 0.) {
    w(d, r);
    if ((double )d <= (double )r * 0.5) {
      w(d, r);
      (list + 0)->wsx = (float )1;
    }
  }
  return;
}
}
vector_t pos[1]  = {      {(float )0., (float )0.}};
vector_t limit[2]  = {      {(float )0., (float )0.}, 
        {(float )1., (float )1.}};
int main(void) 
{ int nww ;
  struct_list list ;

  {
  gitter(1, pos, & list, & nww, (vector_t *)(limit), (float )1.);
  exit(0);
}
}
