/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "921208-1.c"
double f(double x ) 
{ 

  {
#line 5
  return (x * x);
}
}
#line 8 "921208-1.c"
double Int(double (*f___0)(double  ) , double a ) 
{ double tmp ;

  {
#line 11
  tmp = (*f___0)(a);
#line 11
  return (tmp);
}
}
#line 14 "921208-1.c"
int main(void) 
{ double tmp ;

  {
#line 16
  tmp = Int(& f, 2.0);
#line 16
  if (tmp != 4.0) {
#line 17
    abort();
  }
#line 18
  exit(0);
}
}
