/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern void exit(int status ) ;
extern void abort(void) ;
void sub3(int const   *i ) 
{ 

  {
  return;
}
}
void eq(int a , int b ) ;
static int i  =    0;
void eq(int a , int b ) 
{ 

  {
  if (a != i) {
    abort();
  }
  i ++;
  return;
}
}
int main(void) 
{ int i___0 ;
  int j ;
  int k ;

  {
  i___0 = 0;
  while (i___0 < 4) {
    j = i___0;
    sub3((int const   *)(& j));
    k = j;
    eq(k, k);
    i___0 ++;
  }
  exit(0);
}
}
