/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "930527-1.c"
int f(unsigned char x ) 
{ 

  {
#line 4
  return ((80 | ((int )x >> 4)) ^ 255);
}
}
#line 7 "930527-1.c"
int main(void) 
{ int tmp ;

  {
#line 9
  tmp = f((unsigned char)0);
#line 9
  if (tmp != 175) {
#line 10
    abort();
  }
#line 11
  exit(0);
}
}
