/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "930622-2.c"
long double ll_to_ld(long long n ) 
{ 

  {
#line 5
  return ((long double )n);
}
}
#line 8 "930622-2.c"
long long ld_to_ll(long double n ) 
{ 

  {
#line 11
  return ((long long )n);
}
}
#line 14 "930622-2.c"
int main(void) 
{ long double tmp ;
  long long tmp___0 ;

  {
#line 18
  tmp = ll_to_ld(10LL);
#line 18
  if (tmp != (long double )10.0) {
#line 19
    abort();
  }
#line 21
  tmp___0 = ld_to_ll((long double )10.0);
#line 21
  if (tmp___0 != 10LL) {
#line 22
    abort();
  }
#line 24
  exit(0);
}
}
