/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
double f(double a ) 
{ 

  {
  return (0.0);
}
}
double (* const  a[1])(double  )  = {      (double (* const  )(double  ))(& f)};
int main(void) 
{ double (*p)() ;

  {
  p = (double (*)())(& f);
  if ((unsigned long )p != (unsigned long )a[0]) {
    abort();
  }
  exit(0);
}
}
