/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 12 "930621-1.c"
struct __anonstruct_foo_3 {
   int x : 18 ;
   int y : 14 ;
};
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 10 "930621-1.c"
int f(void) 
{ struct __anonstruct_foo_3 foo ;

  {
#line 17
  foo.x = 10;
#line 18
  foo.y = 20;
#line 20
  return (foo.y);
}
}
#line 23 "930621-1.c"
int main(void) 
{ int tmp ;

  {
#line 25
  tmp = f();
#line 25
  if (tmp != 20) {
#line 26
    abort();
  }
#line 27
  exit(0);
}
}
