/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int fp(double a , int b ) 
{ 

  {
  if (a != (double )33) {
    abort();
  } else {
    if (b != 11) {
      abort();
    }
  }
  return (0);
}
}
int main(void) 
{ int (*f)(double  , int  ) ;

  {
  f = & fp;
  fp((double )33, 11);
  (*f)((double )33, 11);
  exit(0);
}
}
