/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct rtx_def {
   int f1 : 1 ;
   int f2 : 1 ;
};
typedef struct rtx_def *rtx;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
static rtx f(rtx orig ) 
{ 

  {
  if (orig->f1) {
    return (orig);
  } else {
    if (orig->f2) {
      return (orig);
    }
  }
  orig->f2 = 1;
  return (orig);
}
}
void f2(void) 
{ 

  {
  abort();
}
}
int main(void) 
{ struct rtx_def foo ;
  rtx bar ;

  {
  foo.f1 = 1;
  foo.f2 = 0;
  bar = f(& foo);
  if ((unsigned long )bar != (unsigned long )(& foo)) {
    abort();
  } else {
    if (bar->f2 != 0) {
      abort();
    }
  }
  exit(0);
}
}
