/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "930818-1.c"
static double one  =    1.0;
#line 4 "930818-1.c"
int f(void) 
{ int colinear ;

  {
#line 7
  colinear = one == 0.0;
#line 8
  if (colinear) {
#line 9
    abort();
  }
#line 10
  return (colinear);
}
}
#line 12 "930818-1.c"
int main(void) 
{ int tmp ;

  {
#line 14
  tmp = f();
#line 14
  if (tmp) {
#line 14
    abort();
  }
#line 15
  exit(0);
}
}
