/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "930929-1.c"
int sub1(int i ) 
{ 

  {
#line 5
  return (i - (5 - i));
}
}
#line 8 "930929-1.c"
int sub2(int i ) 
{ 

  {
#line 11
  return (i + (5 + i));
}
}
#line 14 "930929-1.c"
int sub3(int i ) 
{ 

  {
#line 17
  return (i - (5 + i));
}
}
#line 20 "930929-1.c"
int sub4(int i ) 
{ 

  {
#line 23
  return (i + (5 - i));
}
}
#line 26 "930929-1.c"
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;

  {
#line 28
  tmp = sub1(20);
#line 28
  if (tmp != 35) {
#line 29
    abort();
  }
#line 30
  tmp___0 = sub2(20);
#line 30
  if (tmp___0 != 45) {
#line 31
    abort();
  }
#line 32
  tmp___1 = sub3(20);
#line 32
  if (tmp___1 != -5) {
#line 33
    abort();
  }
#line 34
  tmp___2 = sub4(20);
#line 34
  if (tmp___2 != 5) {
#line 35
    abort();
  }
#line 36
  exit(0);
}
}
