/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
void f(unsigned int n ) 
{ 

  {
  if ((int )n >= 0) {
    abort();
  }
  return;
}
}
int main(void) 
{ unsigned int x ;

  {
  x = (unsigned int )(~ 0);
  f(x);
  exit(0);
}
}
