/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct __anonstruct_T_21 {
   char x ;
};
typedef struct __anonstruct_T_21 T;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
T f(T s1 ) 
{ T s1a ;

  {
  s1a.x = s1.x;
  return (s1a);
}
}
int main(void) 
{ T s1a ;
  T s1b ;

  {
  s1a.x = (char)100;
  s1b = f(s1a);
  if ((int )s1b.x != 100) {
    abort();
  }
  exit(0);
}
}
