/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "931004-13.c"
struct tiny {
   char c ;
   char d ;
   char e ;
   char f ;
};
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 10 "931004-13.c"
void f(int n , struct tiny x , struct tiny y , struct tiny z , long l ) 
{ 

  {
#line 12
  if ((int )x.c != 10) {
#line 13
    abort();
  }
#line 14
  if ((int )x.d != 20) {
#line 15
    abort();
  }
#line 16
  if ((int )x.e != 30) {
#line 17
    abort();
  }
#line 18
  if ((int )x.f != 40) {
#line 19
    abort();
  }
#line 21
  if ((int )y.c != 11) {
#line 22
    abort();
  }
#line 23
  if ((int )y.d != 21) {
#line 24
    abort();
  }
#line 25
  if ((int )y.e != 31) {
#line 26
    abort();
  }
#line 27
  if ((int )y.f != 41) {
#line 28
    abort();
  }
#line 30
  if ((int )z.c != 12) {
#line 31
    abort();
  }
#line 32
  if ((int )z.d != 22) {
#line 33
    abort();
  }
#line 34
  if ((int )z.e != 32) {
#line 35
    abort();
  }
#line 36
  if ((int )z.f != 42) {
#line 37
    abort();
  }
#line 39
  if (l != 123L) {
#line 40
    abort();
  }
#line 41
  return;
}
}
#line 43 "931004-13.c"
int main(void) 
{ struct tiny x[3] ;

  {
#line 46
  x[0].c = (char)10;
#line 47
  x[1].c = (char)11;
#line 48
  x[2].c = (char)12;
#line 49
  x[0].d = (char)20;
#line 50
  x[1].d = (char)21;
#line 51
  x[2].d = (char)22;
#line 52
  x[0].e = (char)30;
#line 53
  x[1].e = (char)31;
#line 54
  x[2].e = (char)32;
#line 55
  x[0].f = (char)40;
#line 56
  x[1].f = (char)41;
#line 57
  x[2].f = (char)42;
#line 58
  f(3, x[0], x[1], x[2], 123L);
#line 59
  exit(0);
}
}
