/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 9 "../../lib/includes/stdlib.h"
typedef unsigned int size_t;
#line 6 "../../lib/includes/stdarg.h"
typedef void *va_list;
#line 4 "931004-14.c"
struct tiny {
   char c ;
   char d ;
   char e ;
   char f ;
};
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 27 "../../lib/includes/stdarg.h"
extern va_list __va_inc(va_list *ap , size_t size ) ;
#line 32
extern void __va_start(va_list *ap , void *pN ) ;
#line 37
extern void __va_end(va_list *ap ) ;
#line 12 "931004-14.c"
void f(int n  , ...) 
{ struct tiny x ;
  int i ;
  va_list ap ;
  va_list tmp ;
  long x___0 ;
  va_list tmp___0 ;

  {
#line 18
  __va_start(& ap, (void *)(& n));
#line 19
  i = 0;
#line 19
  while (i < n) {
#line 21
    tmp = __va_inc(& ap, (unsigned int )sizeof(struct tiny ));
#line 21
    x = *((struct tiny *)tmp);
#line 22
    if ((int )x.c != i + 10) {
#line 23
      abort();
    }
#line 24
    if ((int )x.d != i + 20) {
#line 25
      abort();
    }
#line 26
    if ((int )x.e != i + 30) {
#line 27
      abort();
    }
#line 28
    if ((int )x.f != i + 40) {
#line 29
      abort();
    }
#line 19
    i ++;
  }
#line 32
  tmp___0 = __va_inc(& ap, (unsigned int )sizeof(long ));
#line 32
  x___0 = *((long *)tmp___0);
#line 33
  if (x___0 != 123L) {
#line 34
    abort();
  }
#line 36
  __va_end(& ap);
#line 37
  return;
}
}
#line 39 "931004-14.c"
int main(void) 
{ struct tiny x[3] ;

  {
#line 42
  x[0].c = (char)10;
#line 43
  x[1].c = (char)11;
#line 44
  x[2].c = (char)12;
#line 45
  x[0].d = (char)20;
#line 46
  x[1].d = (char)21;
#line 47
  x[2].d = (char)22;
#line 48
  x[0].e = (char)30;
#line 49
  x[1].e = (char)31;
#line 50
  x[2].e = (char)32;
#line 51
  x[0].f = (char)40;
#line 52
  x[1].f = (char)41;
#line 53
  x[2].f = (char)42;
#line 54
  f(3, x[0], x[1], x[2], 123L);
#line 55
  exit(0);
}
}
