/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "931004-11.c"
struct tiny {
   char c ;
   char d ;
   char e ;
};
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 9 "931004-11.c"
void f(int n , struct tiny x , struct tiny y , struct tiny z , long l ) 
{ 

  {
#line 11
  if ((int )x.c != 10) {
#line 12
    abort();
  }
#line 13
  if ((int )x.d != 20) {
#line 14
    abort();
  }
#line 15
  if ((int )x.e != 30) {
#line 16
    abort();
  }
#line 18
  if ((int )y.c != 11) {
#line 19
    abort();
  }
#line 20
  if ((int )y.d != 21) {
#line 21
    abort();
  }
#line 22
  if ((int )y.e != 31) {
#line 23
    abort();
  }
#line 25
  if ((int )z.c != 12) {
#line 26
    abort();
  }
#line 27
  if ((int )z.d != 22) {
#line 28
    abort();
  }
#line 29
  if ((int )z.e != 32) {
#line 30
    abort();
  }
#line 32
  if (l != 123L) {
#line 33
    abort();
  }
#line 34
  return;
}
}
#line 36 "931004-11.c"
int main(void) 
{ struct tiny x[3] ;

  {
#line 39
  x[0].c = (char)10;
#line 40
  x[1].c = (char)11;
#line 41
  x[2].c = (char)12;
#line 42
  x[0].d = (char)20;
#line 43
  x[1].d = (char)21;
#line 44
  x[2].d = (char)22;
#line 45
  x[0].e = (char)30;
#line 46
  x[1].e = (char)31;
#line 47
  x[2].e = (char)32;
#line 48
  f(3, x[0], x[1], x[2], 123L);
#line 49
  exit(0);
}
}
