/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "931017-1.c"
int v  ;
#line 3
void f(void) ;
#line 4 "931017-1.c"
int main(void) 
{ 

  {
#line 6
  f();
#line 7
  exit(0);
}
}
#line 10 "931017-1.c"
int h1(void) 
{ 

  {
#line 12
  return (0);
}
}
#line 15 "931017-1.c"
int h2(int *e ) 
{ 

  {
#line 18
  if ((unsigned long )e != (unsigned long )(& v)) {
#line 19
    abort();
  }
#line 20
  return (0);
}
}
#line 23 "931017-1.c"
int g(char *c ) 
{ int i ;
  int b ;

  {
#line 29
  while (1) {
#line 31
    i = h1();
#line 32
    if (i == -1) {
#line 33
      return (0);
    } else {
#line 34
      if (i == 1) {
#line 35
        h1();
      }
    }
#line 29
    if (! (i == 1)) {
#line 29
      break;
    }
  }
#line 39
  while (1) {
#line 40
    b = h2(& v);
#line 39
    if (! (i == 5)) {
#line 39
      break;
    }
  }
#line 43
  if (i != 2) {
#line 44
    return (b);
  }
#line 45
  *c = (char )'a';
#line 47
  return (0);
}
}
#line 51 "931017-1.c"
void f(void) 
{ char c ;

  {
#line 54
  g(& c);
#line 55
  return;
}
}
