/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "931009-1.c"
void f(void) ;
#line 3 "931009-1.c"
int main(void) 
{ 

  {
#line 5
  f();
#line 6
  exit(0);
}
}
#line 9 "931009-1.c"
static void g(int *out , int size , int lo , int hi ) 
{ int j ;

  {
#line 15
  j = 0;
#line 15
  while (j < size) {
#line 16
    *(out + j) = j * (hi - lo);
#line 15
    j ++;
  }
#line 17
  return;
}
}
#line 20 "931009-1.c"
void f(void) 
{ int a[2] ;

  {
#line 24
  g(a, 2, 0, 1);
#line 26
  if (a[0] != 0) {
#line 27
    abort();
  } else {
#line 26
    if (a[1] != 1) {
#line 27
      abort();
    }
  }
#line 28
  return;
}
}
