/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 4 "931110-2.c"
int main(void) ;
#line 4 "931110-2.c"
static int a[2]  = {      3,      4};
#line 2 "931110-2.c"
int main(void) 
{ register int *b ;
  int c ;
  int *tmp ;

  {
#line 8
  b = a;
#line 9
  tmp = b;
#line 9
  b ++;
#line 9
  c = *tmp % 8;
#line 10
  if (c != 3) {
#line 11
    abort();
  }
#line 12
  exit(0);
}
}
