/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "940122-1.c"
char *a  =    (char *)0;
#line 3 "940122-1.c"
char *b  =    (char *)0;
#line 5 "940122-1.c"
void g(int x ) 
{ 

  {
#line 8
  if (! (! a) != ! (! b)) {
#line 9
    abort();
  }
#line 10
  return;
}
}
#line 12 "940122-1.c"
void f(int x ) 
{ 

  {
#line 15
  g(x * x);
#line 16
  return;
}
}
#line 18 "940122-1.c"
int main(void) 
{ 

  {
#line 20
  f(100);
#line 21
  exit(0);
}
}
