/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
long f(long x , long y ) 
{ long tmp ;

  {
  if (x > 1L) {
    tmp = y;
  } else {
    tmp = y & 1L;
  }
  return (tmp);
}
}
int main(void) 
{ long tmp ;

  {
  tmp = f(2L, 14600926L);
  if (tmp != 14600926L) {
    abort();
  }
  exit(0);
}
}
