/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "950511-1.c"
int main(void) 
{ unsigned long long xx ;
  unsigned long long *x ;

  {
#line 5
  x = & xx;
#line 7
  *x = 0xfffffffffffffffdULL;
#line 8
  *x *= *x;
#line 9
  if (*x != 9ULL) {
#line 10
    abort();
  }
#line 11
  exit(0);
}
}
