/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int main(void) 
{ unsigned long long xx ;
  unsigned long long *x ;

  {
  x = & xx;
  *x = 0xfffffffffffffffdULL;
  *x *= *x;
  if (*x != 9ULL) {
    abort();
  }
  exit(0);
}
}
