/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct __anonstruct_T_21 {
   char hours ;
   char day ;
   char month ;
   short year ;
};
typedef struct __anonstruct_T_21 T;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
T g(void) 
{ T now ;

  {
  now.hours = (char)1;
  now.day = (char)2;
  now.month = (char)3;
  now.year = (short)4;
  return (now);
}
}
T f(void) 
{ T virk ;

  {
  virk = g();
  return (virk);
}
}
int main(void) 
{ T tmp ;
  T tmp___0 ;
  T tmp___1 ;
  T tmp___2 ;

  {
  tmp = f();
  if ((int )tmp.hours != 1) {
    abort();
  } else {
    tmp___0 = f();
    if ((int )tmp___0.day != 2) {
      abort();
    } else {
      tmp___1 = f();
      if ((int )tmp___1.month != 3) {
        abort();
      } else {
        tmp___2 = f();
        if ((int )tmp___2.year != 4) {
          abort();
        }
      }
    }
  }
  exit(0);
}
}
