/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct s {
   int a ;
   int b ;
   struct s *dummy ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int f(struct s *sp ) 
{ int tmp ;

  {
  if (sp) {
    if (sp->a == -1) {
      if (sp->b == -1) {
        tmp = 1;
      } else {
        tmp = 0;
      }
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int main(void) 
{ struct s x ;
  int tmp ;

  {
  x.b = -1;
  x.a = x.b;
  tmp = f(& x);
  if (tmp == 0) {
    abort();
  }
  exit(0);
}
}
