/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "950621-1.c"
struct s {
   int a ;
   int b ;
   struct s *dummy ;
};
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 9 "950621-1.c"
int f(struct s *sp ) 
{ int tmp ;

  {
#line 11
  if (sp) {
#line 11
    if (sp->a == -1) {
#line 11
      if (sp->b == -1) {
#line 11
        tmp = 1;
      } else {
#line 11
        tmp = 0;
      }
    } else {
#line 11
      tmp = 0;
    }
  } else {
#line 11
    tmp = 0;
  }
#line 11
  return (tmp);
}
}
#line 14 "950621-1.c"
int main(void) 
{ struct s x ;
  int tmp ;

  {
#line 17
  x.b = -1;
#line 17
  x.a = x.b;
#line 18
  tmp = f(& x);
#line 18
  if (tmp == 0) {
#line 19
    abort();
  }
#line 20
  exit(0);
}
}
