/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int f(int n ) 
{ 

  {
  return ((n > 0) - (n < 0));
}
}
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
  tmp = f(-1);
  if (tmp != -1) {
    abort();
  }
  tmp___0 = f(1);
  if (tmp___0 != 1) {
    abort();
  }
  tmp___1 = f(0);
  if (tmp___1 != 0) {
    abort();
  }
  exit(0);
}
}
