/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "950706-1.c"
int f(int n ) 
{ 

  {
#line 5
  return ((n > 0) - (n < 0));
}
}
#line 8 "950706-1.c"
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
#line 10
  tmp = f(-1);
#line 10
  if (tmp != -1) {
#line 11
    abort();
  }
#line 12
  tmp___0 = f(1);
#line 12
  if (tmp___0 != 1) {
#line 13
    abort();
  }
#line 14
  tmp___1 = f(0);
#line 14
  if (tmp___1 != 0) {
#line 15
    abort();
  }
#line 16
  exit(0);
}
}
