/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern void exit(int status ) ;
extern void abort(void) ;
int glob  ;
int g(int x ) 
{ 

  {
  glob = x;
  return (0);
}
}
void f(int x ) 
{ int a ;

  {
  a = ~ x;
  while (a) {
    a = g(a);
  }
  return;
}
}
int main(void) 
{ 

  {
  f(3);
  if (glob != -4) {
    abort();
  }
  exit(0);
}
}
