/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct a_struct {
   unsigned char a_character ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
struct a_struct an_array[5]  ;
struct a_struct *a_ptr  ;
int yabba  =    1;
int f(unsigned char a , unsigned long b ) 
{ long i ;
  long j ;
  long p ;
  long q ;
  long r ;
  long s ;
  long tmp ;
  long tmp___0 ;

  {
  if (b != 0UL) {
    if (yabba) {
      return (-1);
    }
    s = (long )(4000000UL / b);
    i = 0L;
    while (i < 11L) {
      j = 0L;
      while (j < 256L) {
        if (p - s < 0L) {
          tmp = - s;
        } else {
          tmp = 0L;
        }
        if (q - s < 0L) {
          tmp___0 = - s;
        } else {
          tmp___0 = q;
        }
        if (tmp < tmp___0) {
          r = i;
        }
        j ++;
      }
      i ++;
    }
  }
  if (yabba) {
    return (0);
  }
  a_ptr = & an_array[a];
  a_ptr->a_character = (unsigned char )r;
  return (0);
}
}
int main(void) 
{ int tmp ;

  {
  tmp = f((unsigned char)1, 0UL);
  if (tmp != 0) {
    abort();
  }
  exit(0);
}
}
