/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int count  ;
void a1(void) 
{ 

  {
  count ++;
  return;
}
}
void b(unsigned short data ) 
{ 

  {
  if ((int )data & 32768) {
    a1();
  }
  data = (unsigned short )((int )data << 1);
  if ((int )data & 32768) {
    a1();
  }
  data = (unsigned short )((int )data << 1);
  if ((int )data & 32768) {
    a1();
  }
  return;
}
}
int main(void) 
{ 

  {
  count = 0;
  b((unsigned short)0);
  if (count != 0) {
    abort();
  }
  count = 0;
  b((unsigned short)32768);
  if (count != 1) {
    abort();
  }
  count = 0;
  b((unsigned short)16384);
  if (count != 1) {
    abort();
  }
  count = 0;
  b((unsigned short)8192);
  if (count != 1) {
    abort();
  }
  count = 0;
  b((unsigned short)49152);
  if (count != 2) {
    abort();
  }
  count = 0;
  b((unsigned short)40960);
  if (count != 2) {
    abort();
  }
  count = 0;
  b((unsigned short)24576);
  if (count != 2) {
    abort();
  }
  count = 0;
  b((unsigned short)57344);
  if (count != 3) {
    abort();
  }
  exit(0);
}
}
