/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "960419-1.c"
static int i  ;
#line 4 "960419-1.c"
void check(int x ) 
{ 

  {
#line 8
  if (! x) {
#line 9
    abort();
  }
#line 10
  return;
}
}
#line 12 "960419-1.c"
int main(void) 
{ int *p ;

  {
#line 14
  p = & i;
#line 16
  check((unsigned long )p != (unsigned long )((void *)0));
#line 17
  exit(0);
}
}
