/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
static int i  ;
void check(int x ) 
{ 

  {
  if (! x) {
    abort();
  }
  return;
}
}
int main(void) 
{ int *p ;

  {
  p = & i;
  check((unsigned long )p != (unsigned long )((void *)0));
  exit(0);
}
}
