/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
unsigned int f(void) 
{ long long l2 ;
  unsigned short us ;
  unsigned long long ul ;
  short s2 ;

  {
  s2 = (short)-1;
  l2 = (long long )s2;
  us = (unsigned short )l2;
  ul = (unsigned long long )us;
  return ((unsigned int )ul);
}
}
unsigned long long g(void) 
{ long long l2 ;
  unsigned short us ;
  unsigned long long ul ;
  short s2 ;

  {
  s2 = (short)-1;
  l2 = (long long )s2;
  us = (unsigned short )l2;
  ul = (unsigned long long )us;
  return (ul);
}
}
int main(void) 
{ unsigned int tmp ;
  unsigned long long tmp___0 ;

  {
  tmp = f();
  if (tmp != 65535U) {
    abort();
  }
  tmp___0 = g();
  if (tmp___0 != 65535ULL) {
    abort();
  }
  exit(0);
}
}
