/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "960802-1.c"
long val  =    1577058304L;
#line 4 "960802-1.c"
long f1(void) 
{ 

  {
#line 7
  return (306L);
}
}
#line 10 "960802-1.c"
long f2(void) 
{ 

  {
#line 13
  return (1577058304L);
}
}
#line 16 "960802-1.c"
void f3(long b ) 
{ 

  {
#line 19
  val = b;
#line 20
  return;
}
}
#line 22 "960802-1.c"
void f4(void) 
{ long v ;
  long tmp ;
  long o ;
  long tmp___0 ;

  {
#line 25
  tmp = f1();
#line 25
  v = tmp;
#line 26
  tmp___0 = f2();
#line 26
  o = tmp___0;
#line 27
  v = (v & 16777215L) | (o & 4278190080L);
#line 28
  f3(v);
#line 29
  return;
}
}
#line 31 "960802-1.c"
int main(void) 
{ 

  {
#line 33
  f4();
#line 34
  if (val != 1577058610L) {
#line 35
    abort();
  }
#line 36
  exit(0);
}
}
