/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "961213-1.c"
int g(unsigned long long *v , int n , unsigned int *a , int b ) 
{ int cnt ;

  {
#line 6
  *v = 0ULL;
#line 7
  cnt = 0;
#line 7
  while (cnt < n) {
#line 8
    *v = *v * (unsigned long long )b + (unsigned long long )*(a + cnt);
#line 7
    cnt ++;
  }
#line 9
  return (n);
}
}
#line 12 "961213-1.c"
int main(void) 
{ int res ;
  unsigned int ar[5] ;
  unsigned long long v ;

  {
#line 15
  ar[0] = 10U;
#line 15
  ar[1] = 11U;
#line 15
  ar[2] = 12U;
#line 15
  ar[3] = 13U;
#line 15
  ar[4] = 14U;
#line 18
  res = g(& v, (int )(sizeof(ar) / sizeof(ar[0])), ar, 16);
#line 19
  if (v != 703710ULL) {
#line 20
    abort();
  }
#line 22
  exit(0);
}
}
