/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int sub1(unsigned long long i ) 
{ 

  {
  if (i < 2147483648ULL) {
    return (1);
  } else {
    return (0);
  }
}
}
int sub2(unsigned long long i ) 
{ 

  {
  if (i <= 2147483647ULL) {
    return (1);
  } else {
    return (0);
  }
}
}
int sub3(unsigned long long i ) 
{ 

  {
  if (i >= 2147483648ULL) {
    return (0);
  } else {
    return (1);
  }
}
}
int sub4(unsigned long long i ) 
{ 

  {
  if (i > 2147483647ULL) {
    return (0);
  } else {
    return (1);
  }
}
}
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;

  {
  tmp = sub1(2147483648ULL);
  if (tmp) {
    abort();
  }
  tmp___0 = sub2(2147483648ULL);
  if (tmp___0) {
    abort();
  }
  tmp___1 = sub3(2147483648ULL);
  if (tmp___1) {
    abort();
  }
  tmp___2 = sub4(2147483648ULL);
  if (tmp___2) {
    abort();
  }
  exit(0);
}
}
