/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "961206-1.c"
int sub1(unsigned long long i ) 
{ 

  {
#line 5
  if (i < 2147483648ULL) {
#line 6
    return (1);
  } else {
#line 8
    return (0);
  }
}
}
#line 11 "961206-1.c"
int sub2(unsigned long long i ) 
{ 

  {
#line 14
  if (i <= 2147483647ULL) {
#line 15
    return (1);
  } else {
#line 17
    return (0);
  }
}
}
#line 20 "961206-1.c"
int sub3(unsigned long long i ) 
{ 

  {
#line 23
  if (i >= 2147483648ULL) {
#line 24
    return (0);
  } else {
#line 26
    return (1);
  }
}
}
#line 29 "961206-1.c"
int sub4(unsigned long long i ) 
{ 

  {
#line 32
  if (i > 2147483647ULL) {
#line 33
    return (0);
  } else {
#line 35
    return (1);
  }
}
}
#line 38 "961206-1.c"
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;

  {
#line 40
  tmp = sub1(2147483648ULL);
#line 40
  if (tmp) {
#line 41
    abort();
  }
#line 43
  tmp___0 = sub2(2147483648ULL);
#line 43
  if (tmp___0) {
#line 44
    abort();
  }
#line 46
  tmp___1 = sub3(2147483648ULL);
#line 46
  if (tmp___1) {
#line 47
    abort();
  }
#line 49
  tmp___2 = sub4(2147483648ULL);
#line 49
  if (tmp___2) {
#line 50
    abort();
  }
#line 52
  exit(0);
}
}
