/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef __builtin_va_list __gnuc_va_list;
typedef __gnuc_va_list va_list;
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
void fdouble(double one  , ...) 
{ double value ;
  va_list ap ;

  {
  __builtin_va_start(ap, one);
  value = __builtin_va_arg(ap, double );
  __builtin_va_end(ap);
  if (one != 1.0) {
    abort();
  } else {
    if (value != 2.0) {
      abort();
    }
  }
  return;
}
}
int main(void) 
{ 

  {
  fdouble(1.0, 2.0);
  exit(0);
}
}
