/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 9 "../../lib/includes/stdlib.h"
typedef unsigned int size_t;
#line 6 "../../lib/includes/stdarg.h"
typedef void *va_list;
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 27 "../../lib/includes/stdarg.h"
extern va_list __va_inc(va_list *ap , size_t size ) ;
#line 32
extern void __va_start(va_list *ap , void *pN ) ;
#line 37
extern void __va_end(va_list *ap ) ;
#line 4 "980205.c"
void fdouble(double one  , ...) 
{ double value ;
  va_list ap ;
  va_list tmp ;

  {
#line 9
  __va_start(& ap, (void *)(& one));
#line 10
  tmp = __va_inc(& ap, (unsigned int )sizeof(double ));
#line 10
  value = *((double *)tmp);
#line 11
  __va_end(& ap);
#line 13
  if (one != 1.0) {
#line 14
    abort();
  } else {
#line 13
    if (value != 2.0) {
#line 14
      abort();
    }
  }
#line 15
  return;
}
}
#line 17 "980205.c"
int main(void) 
{ 

  {
#line 19
  fdouble(1.0, 2.0);
#line 20
  exit(0);
}
}
