/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef unsigned short Uint16;
typedef unsigned int Uint;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
Uint f(void) ;
static Uint16 values[1]  = {      (Uint16 )37632};
Uint f(void) 
{ Uint16 token ;
  Uint count ;

  {
  token = values[0];
  count = (unsigned int )((int )token >> 8);
  return (count);
}
}
int main(void) 
{ Uint tmp ;

  {
  tmp = f();
  if (tmp != 147U) {
    abort();
  }
  exit(0);
}
}
