/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int compare(unsigned int x , unsigned int y ) 
{ 

  {
  if (x == y) {
    return (0);
  } else {
    return (1);
  }
}
}
int main(void) 
{ unsigned int i ;
  unsigned int j ;
  unsigned int k ;
  unsigned int l ;
  int tmp ;
  int tmp___0 ;

  {
  i = 5U;
  j = 2U;
  k = 0U;
  l = 2U;
  tmp = compare(5U, i % ~ j);
  if (tmp) {
    abort();
  } else {
    tmp___0 = compare(0U, k % ~ l);
    if (tmp___0) {
      abort();
    } else {
      exit(0);
    }
  }
}
}
