/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 10 "980602-2.c"
struct __anonstruct_t_3 {
   unsigned int bit : 30 ;
};
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 10 "980602-2.c"
struct __anonstruct_t_3 t  ;
#line 14 "980602-2.c"
int main(void) 
{ unsigned int tmp ;

  {
#line 16
  tmp = t.bit;
#line 16
  (t.bit) ++;
#line 16
  if (tmp) {
#line 19
    abort();
  } else {
#line 17
    exit(0);
  }
#line 20
  return (0);
}
}
