/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 6 "../../lib/includes/stdarg.h"
typedef __builtin_va_list va_list;
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 25 "../../lib/includes/stdarg.h"
extern void *__va_arg(va_list *ap ) ;
#line 30
extern void __va_start(va_list *ap , void *pN ) ;
#line 35
extern void __va_end(va_list *ap ) ;
#line 4 "980608-1.c"
void f1(int a , int b , int c , int d , int e , int f , int g , int h , int i , int j ,
        int k , int l , int m , int n , int o ) 
{ 

  {
#line 7
  return;
}
}
#line 10 "980608-1.c"
__inline void debug(char const   *msg  , ...) 
{ va_list ap ;
  void *tmp ;
  void *tmp___0 ;
  void *tmp___1 ;
  void *tmp___2 ;
  void *tmp___3 ;
  void *tmp___4 ;

  {
#line 13
  __va_start(& ap, (void *)(& msg));
#line 15
  f1(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
#line 17
  tmp = __va_arg(& ap);
#line 17
  if (*((int *)tmp) != 101) {
#line 18
    abort();
  }
#line 19
  tmp___0 = __va_arg(& ap);
#line 19
  if (*((int *)tmp___0) != 102) {
#line 20
    abort();
  }
#line 21
  tmp___1 = __va_arg(& ap);
#line 21
  if (*((int *)tmp___1) != 103) {
#line 22
    abort();
  }
#line 23
  tmp___2 = __va_arg(& ap);
#line 23
  if (*((int *)tmp___2) != 104) {
#line 24
    abort();
  }
#line 25
  tmp___3 = __va_arg(& ap);
#line 25
  if (*((int *)tmp___3) != 105) {
#line 26
    abort();
  }
#line 27
  tmp___4 = __va_arg(& ap);
#line 27
  if (*((int *)tmp___4) != 106) {
#line 28
    abort();
  }
#line 30
  __va_end(& ap);
#line 31
  return;
}
}
#line 33 "980608-1.c"
int main(void) 
{ 

  {
#line 35
  debug("%d %d %d  %d %d %d\n", 101, 102, 103, 104, 105, 106);
#line 36
  exit(0);
}
}
