/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct __anonstruct_t_21 {
   unsigned int bit : 30 ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
struct __anonstruct_t_21 t  ;
int main(void) 
{ unsigned int tmp ;

  {
  tmp = t.bit;
  (t.bit) ++;
  if (tmp) {
    abort();
  } else {
    exit(0);
  }
}
}
