/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct fd {
   unsigned char a ;
   unsigned char b ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
struct fd f  =    {(unsigned char)5, (unsigned char)0};
struct fd *g(void) 
{ 

  {
  return (& f);
}
}
int h(void) 
{ 

  {
  return (-1);
}
}
int main(void) 
{ struct fd *f___0 ;
  struct fd *tmp ;
  int tmp___0 ;

  {
  tmp = g();
  f___0 = tmp;
  tmp___0 = h();
  f___0->b = (unsigned char )tmp___0;
  if ((((int )f___0->a & 127) & -17) <= 2) {
    abort();
  }
  exit(0);
}
}
