/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 10 "../../lib/includes/string.h"
extern int strcmp(char const   *str1 , char const   *str2 ) ;
#line 11
extern char *strcpy(char *s1 , char const   *s2 ) ;
#line 7 "980707-1.c"
static char *arglist[256]  ;
#line 4 "980707-1.c"
char **buildargv(char *input ) 
{ int numargs ;
  int tmp ;
  char *tmp___0 ;

  {
#line 8
  numargs = 0;
#line 10
  while (1) {
#line 12
    while ((int )*input == 32) {
#line 13
      input ++;
    }
#line 14
    if ((int )*input == 0) {
#line 15
      break;
    }
#line 16
    tmp = numargs;
#line 16
    numargs ++;
#line 16
    arglist[tmp] = input;
#line 17
    while (1) {
#line 17
      if ((int )*input != 32) {
#line 17
        if (! ((int )*input != 0)) {
#line 17
          break;
        }
      } else {
#line 17
        break;
      }
#line 18
      input ++;
    }
#line 19
    if ((int )*input == 0) {
#line 20
      break;
    }
#line 21
    tmp___0 = input;
#line 21
    input ++;
#line 21
    *tmp___0 = (char)0;
  }
#line 23
  arglist[numargs] = (char *)((void *)0);
#line 24
  return (arglist);
}
}
#line 28 "980707-1.c"
int main(void) 
{ char **args ;
  char input[256] ;
  int tmp ;
  int tmp___0 ;

  {
#line 34
  strcpy(input, " a b");
#line 35
  args = buildargv(input);
#line 37
  tmp = strcmp((char const   *)*(args + 0), "a");
#line 37
  if (tmp) {
#line 38
    abort();
  }
#line 39
  tmp___0 = strcmp((char const   *)*(args + 1), "b");
#line 39
  if (tmp___0) {
#line 40
    abort();
  }
#line 41
  if ((unsigned long )*(args + 2) != (unsigned long )((void *)0)) {
#line 42
    abort();
  }
#line 44
  exit(0);
}
}
