/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int main(void) 
{ int a ;
  int b ;
  int c ;
  int *pa ;
  int *pb ;
  int *pc ;
  int **ppa ;
  int **ppb ;
  int **ppc ;
  int i ;
  int x ;
  int y ;
  int z ;
  int tmp ;

  {
  a = 10;
  b = 20;
  c = 30;
  pa = & a;
  pb = & b;
  pc = & c;
  ppa = & pa;
  ppb = & pb;
  ppc = & pc;
  x = 0;
  y = 0;
  z = 0;
  i = 0;
  while (i < 10) {
    if ((unsigned long )pa == (unsigned long )(& a)) {
      pa = & b;
    } else {
      pa = & a;
    }
    while (1) {
      tmp = *pa;
      (*pa) --;
      if (! tmp) {
        break;
      }
      x ++;
      if (*pa < 3) {
        break;
      } else {
        pa = & b;
      }
    }
    x ++;
    pa = & b;
    i ++;
  }
  if (*pa != -5) {
    abort();
  } else {
    if (*pb != -5) {
      abort();
    } else {
      if (x != 43) {
        abort();
      }
    }
  }
  exit(0);
}
}
