/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "990106-1.c"
int foo(char *bufp ) 
{ int x ;
  char *tmp ;
  char tmp___0 ;

  {
#line 5
  x = 80;
#line 6
  tmp = bufp;
#line 6
  bufp ++;
#line 6
  if (x) {
#line 6
    tmp___0 = (char )'a';
  } else {
#line 6
    tmp___0 = (char )'b';
  }
#line 6
  *tmp = tmp___0;
#line 6
  return ((int )tmp___0);
}
}
#line 9 "990106-1.c"
int main(void) 
{ char x ;
  int tmp ;

  {
#line 13
  tmp = foo(& x);
#line 13
  if (tmp != 97) {
#line 14
    abort();
  }
#line 16
  exit(0);
}
}
