/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 11 "990211-1.c"
void func(int i ) 
{ 

  {
#line 17
  if (i < 0) {
#line 17
    if (i >= 0) {
#line 18
      abort();
    }
  }
#line 19
  if (i > 0) {
#line 19
    if (i <= 0) {
#line 20
      abort();
    }
  }
#line 21
  if (i >= 0) {
#line 21
    if (i < 0) {
#line 22
      abort();
    }
  }
#line 23
  if (i <= 0) {
#line 23
    if (i > 0) {
#line 24
      abort();
    }
  }
#line 26
  if (i < 77) {
#line 26
    if (i >= 77) {
#line 27
      abort();
    }
  }
#line 28
  if (i > 77) {
#line 28
    if (i <= 77) {
#line 29
      abort();
    }
  }
#line 30
  if (i >= 77) {
#line 30
    if (i < 77) {
#line 31
      abort();
    }
  }
#line 32
  if (i <= 77) {
#line 32
    if (i > 77) {
#line 33
      abort();
    }
  }
#line 36
  if (! (i < 0)) {
#line 36
    if (! (i >= 0)) {
#line 37
      abort();
    }
  }
#line 38
  if (! (i > 0)) {
#line 38
    if (! (i <= 0)) {
#line 39
      abort();
    }
  }
#line 40
  if (! (i >= 0)) {
#line 40
    if (! (i < 0)) {
#line 41
      abort();
    }
  }
#line 42
  if (! (i <= 0)) {
#line 42
    if (! (i > 0)) {
#line 43
      abort();
    }
  }
#line 45
  if (! (i < 77)) {
#line 45
    if (! (i >= 77)) {
#line 46
      abort();
    }
  }
#line 47
  if (! (i > 77)) {
#line 47
    if (! (i <= 77)) {
#line 48
      abort();
    }
  }
#line 49
  if (! (i >= 77)) {
#line 49
    if (! (i < 77)) {
#line 50
      abort();
    }
  }
#line 51
  if (! (i <= 77)) {
#line 51
    if (! (i > 77)) {
#line 52
      abort();
    }
  }
#line 54
  return;
}
}
#line 57 "990211-1.c"
int main(void) 
{ 

  {
#line 59
  func(0);
#line 60
  func(1);
#line 61
  return (0);
}
}
