/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct a {
   char a ;
   char b ;
   short c ;
};
struct b {
   int c ;
   short b ;
   short a ;
};
struct c {
   unsigned int c : 4 ;
   unsigned int b : 14 ;
   unsigned int a : 14 ;
} __attribute__((__aligned__)) ;
struct d {
   unsigned int a : 14 ;
   unsigned int b : 14 ;
   unsigned int c : 4 ;
} __attribute__((__aligned__)) ;
struct e {
   int c : 4 ;
   int b : 14 ;
   int a : 14 ;
} __attribute__((__aligned__)) ;
struct f {
   int a : 14 ;
   int b : 14 ;
   int c : 4 ;
} __attribute__((__aligned__)) ;
struct gx {
   int c : 4 ;
   int b : 14 ;
   int a : 14 ;
} __attribute__((__aligned__)) ;
struct gy {
   int b : 14 ;
   int a : 14 ;
   int c : 4 ;
} __attribute__((__aligned__)) ;
struct hx {
   int a : 14 ;
   int b : 14 ;
   int c : 4 ;
} __attribute__((__aligned__)) ;
struct hy {
   int c : 4 ;
   int a : 14 ;
   int b : 14 ;
} __attribute__((__aligned__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int a1(void) ;
static struct a x  =    {(char)1, (char)2, (short )(~ 1)};
int a1(void) ;
static struct a y  =    {(char)65, (char)2, (short )(~ 2)};
int a1(void) 
{ int tmp ;

  {
  if ((int )x.a == ((int )y.a & -65)) {
    if ((int )x.b == (int )y.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int a2(void) ;
static struct a x___0  =    {(char)1, (char)66, (short )(~ 1)};
int a2(void) ;
static struct a y___0  =    {(char)1, (char)2, (short )(~ 2)};
int a2(void) 
{ int tmp ;

  {
  if ((int )x___0.a == (int )y___0.a) {
    if (((int )x___0.b & -65) == (int )y___0.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int a3(void) ;
static struct a x___1  =    {(char)9, (char)66, (short )(~ 1)};
int a3(void) ;
static struct a y___1  =    {(char)33, (char)18, (short )(~ 2)};
int a3(void) 
{ int tmp ;

  {
  if (((int )x___1.a & -9) == ((int )y___1.a & -33)) {
    if (((int )x___1.b & -65) == ((int )y___1.b & -17)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int b1(void) ;
static struct b x___2  =    {~ 1, (short)2, (short)1};
int b1(void) ;
static struct b y___2  =    {~ 2, (short)2, (short)65};
int b1(void) 
{ int tmp ;

  {
  if ((int )x___2.a == ((int )y___2.a & -65)) {
    if ((int )x___2.b == (int )y___2.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int b2(void) ;
static struct b x___3  =    {~ 1, (short)66, (short)1};
int b2(void) ;
static struct b y___3  =    {~ 2, (short)2, (short)1};
int b2(void) 
{ int tmp ;

  {
  if ((int )x___3.a == (int )y___3.a) {
    if (((int )x___3.b & -65) == (int )y___3.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int b3(void) ;
static struct b x___4  =    {~ 1, (short)66, (short)9};
int b3(void) ;
static struct b y___4  =    {~ 2, (short)18, (short)33};
int b3(void) 
{ int tmp ;

  {
  if (((int )x___4.a & -9) == ((int )y___4.a & -33)) {
    if (((int )x___4.b & -65) == ((int )y___4.b & -17)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int c1(void) ;
static struct c x___5  =    {(unsigned int )(~ 1), 2U, 1U};
int c1(void) ;
static struct c y___5  =    {(unsigned int )(~ 2), 2U, 65U};
int c1(void) 
{ int tmp ;

  {
  if (x___5.a == (y___5.a & 4294967231U)) {
    if (x___5.b == y___5.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int c2(void) ;
static struct c x___6  =    {(unsigned int )(~ 1), 66U, 1U};
int c2(void) ;
static struct c y___6  =    {(unsigned int )(~ 2), 2U, 1U};
int c2(void) 
{ int tmp ;

  {
  if (x___6.a == y___6.a) {
    if ((x___6.b & 4294967231U) == y___6.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int c3(void) ;
static struct c x___7  =    {(unsigned int )(~ 1), 66U, 9U};
int c3(void) ;
static struct c y___7  =    {(unsigned int )(~ 2), 18U, 33U};
int c3(void) 
{ int tmp ;

  {
  if ((x___7.a & 4294967287U) == (y___7.a & 4294967263U)) {
    if ((x___7.b & 4294967231U) == (y___7.b & 4294967279U)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int d1(void) ;
static struct d x___8  =    {1U, 2U, (unsigned int )(~ 1)};
int d1(void) ;
static struct d y___8  =    {65U, 2U, (unsigned int )(~ 2)};
int d1(void) 
{ int tmp ;

  {
  if (x___8.a == (y___8.a & 4294967231U)) {
    if (x___8.b == y___8.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int d2(void) ;
static struct d x___9  =    {1U, 66U, (unsigned int )(~ 1)};
int d2(void) ;
static struct d y___9  =    {1U, 2U, (unsigned int )(~ 2)};
int d2(void) 
{ int tmp ;

  {
  if (x___9.a == y___9.a) {
    if ((x___9.b & 4294967231U) == y___9.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int d3(void) ;
static struct d x___10  =    {9U, 66U, (unsigned int )(~ 1)};
int d3(void) ;
static struct d y___10  =    {33U, 18U, (unsigned int )(~ 2)};
int d3(void) 
{ int tmp ;

  {
  if ((x___10.a & 4294967287U) == (y___10.a & 4294967263U)) {
    if ((x___10.b & 4294967231U) == (y___10.b & 4294967279U)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int e1(void) ;
static struct e x___11  =    {~ 1, -2, -65};
int e1(void) ;
static struct e y___11  =    {~ 2, -2, -1};
int e1(void) 
{ int tmp ;

  {
  if (x___11.a == (y___11.a & -65)) {
    if (x___11.b == y___11.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int e2(void) ;
static struct e x___12  =    {~ 1, -2, -1};
int e2(void) ;
static struct e y___12  =    {~ 2, -66, -1};
int e2(void) 
{ int tmp ;

  {
  if (x___12.a == y___12.a) {
    if ((x___12.b & -65) == y___12.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int e3(void) ;
static struct e x___13  =    {~ 1, -18, -33};
int e3(void) ;
static struct e y___13  =    {~ 2, -66, -9};
int e3(void) 
{ int tmp ;

  {
  if ((x___13.a & -9) == (y___13.a & -33)) {
    if ((x___13.b & -65) == (y___13.b & -17)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int e4(void) ;
static struct e x___14  =    {-1, -1, 0};
int e4(void) 
{ int tmp ;

  {
  if (x___14.a == 0) {
    if (x___14.b & 8192) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int f1(void) ;
static struct f x___15  =    {-65, -2, ~ 1};
int f1(void) ;
static struct f y___14  =    {-1, -2, ~ 2};
int f1(void) 
{ int tmp ;

  {
  if (x___15.a == (y___14.a & -65)) {
    if (x___15.b == y___14.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int f2(void) ;
static struct f x___16  =    {-1, -2, ~ 1};
int f2(void) ;
static struct f y___15  =    {-1, -66, ~ 2};
int f2(void) 
{ int tmp ;

  {
  if (x___16.a == y___15.a) {
    if ((x___16.b & -65) == y___15.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int f3(void) ;
static struct f x___17  =    {-33, -18, ~ 1};
int f3(void) ;
static struct f y___16  =    {-9, -66, ~ 2};
int f3(void) 
{ int tmp ;

  {
  if ((x___17.a & -9) == (y___16.a & -33)) {
    if ((x___17.b & -65) == (y___16.b & -17)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int f4(void) ;
static struct f x___18  =    {0, -1, -1};
int f4(void) 
{ int tmp ;

  {
  if (x___18.a == 0) {
    if (x___18.b & 8192) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int g1(void) ;
static struct gx x___19  =    {~ 1, -2, -65};
int g1(void) ;
static struct gy y___17  =    {-2, -1, ~ 2};
int g1(void) 
{ int tmp ;

  {
  if (x___19.a == (y___17.a & -65)) {
    if (x___19.b == y___17.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int g2(void) ;
static struct gx x___20  =    {~ 1, -2, -1};
int g2(void) ;
static struct gy y___18  =    {-66, -1, ~ 2};
int g2(void) 
{ int tmp ;

  {
  if (x___20.a == y___18.a) {
    if ((x___20.b & -65) == y___18.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int g3(void) ;
static struct gx x___21  =    {~ 1, -18, -33};
int g3(void) ;
static struct gy y___19  =    {-66, -9, ~ 2};
int g3(void) 
{ int tmp ;

  {
  if ((x___21.a & -9) == (y___19.a & -33)) {
    if ((x___21.b & -65) == (y___19.b & -17)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int g4(void) ;
static struct gx x___22  =    {~ 1, 32, 16};
int g4(void) ;
static struct gy y___20  =    {512, 256, ~ 2};
int g4(void) 
{ int tmp ;

  {
  if ((x___22.a & 240) == (y___20.a & 3840)) {
    if ((x___22.b & 240) == (y___20.b & 3840)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int g5(void) ;
static struct gx x___23  =    {~ 1, 512, 256};
int g5(void) ;
static struct gy y___21  =    {32, 16, ~ 2};
int g5(void) 
{ int tmp ;

  {
  if ((x___23.a & 3840) == (y___21.a & 240)) {
    if ((x___23.b & 3840) == (y___21.b & 240)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int g6(void) ;
static struct gx x___24  =    {~ 1, 65056, 64784};
int g6(void) ;
static struct gy y___22  =    {49711, 49439, ~ 2};
int g6(void) 
{ int tmp ;

  {
  if ((x___24.a & 1023) == (y___22.a & 16368)) {
    if ((x___24.b & 1023) == (y___22.b & 16368)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int g7(void) ;
static struct gx x___25  =    {~ 1, 49711, 49439};
int g7(void) ;
static struct gy y___23  =    {65056, 64784, ~ 2};
int g7(void) 
{ int tmp ;

  {
  if ((x___25.a & 16368) == (y___23.a & 1023)) {
    if ((x___25.b & 16368) == (y___23.b & 1023)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int h1(void) ;
static struct hx x___26  =    {-65, -2, ~ 1};
int h1(void) ;
static struct hy y___24  =    {~ 2, -1, -2};
int h1(void) 
{ int tmp ;

  {
  if (x___26.a == (y___24.a & -65)) {
    if (x___26.b == y___24.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int h2(void) ;
static struct hx x___27  =    {-1, -2, ~ 1};
int h2(void) ;
static struct hy y___25  =    {~ 2, -1, -66};
int h2(void) 
{ int tmp ;

  {
  if (x___27.a == y___25.a) {
    if ((x___27.b & -65) == y___25.b) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int h3(void) ;
static struct hx x___28  =    {-33, -18, ~ 1};
int h3(void) ;
static struct hy y___26  =    {~ 2, -9, -66};
int h3(void) 
{ int tmp ;

  {
  if ((x___28.a & -9) == (y___26.a & -33)) {
    if ((x___28.b & -65) == (y___26.b & -17)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int h4(void) ;
static struct hx x___29  =    {16, 32, ~ 1};
int h4(void) ;
static struct hy y___27  =    {~ 2, 256, 512};
int h4(void) 
{ int tmp ;

  {
  if ((x___29.a & 240) == (y___27.a & 3840)) {
    if ((x___29.b & 240) == (y___27.b & 3840)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int h5(void) ;
static struct hx x___30  =    {256, 512, ~ 1};
int h5(void) ;
static struct hy y___28  =    {~ 2, 16, 32};
int h5(void) 
{ int tmp ;

  {
  if ((x___30.a & 3840) == (y___28.a & 240)) {
    if ((x___30.b & 3840) == (y___28.b & 240)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int h6(void) ;
static struct hx x___31  =    {64784, 65056, ~ 1};
int h6(void) ;
static struct hy y___29  =    {~ 2, 49439, 49711};
int h6(void) 
{ int tmp ;

  {
  if ((x___31.a & 1023) == (y___29.a & 16368)) {
    if ((x___31.b & 1023) == (y___29.b & 16368)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int h7(void) ;
static struct hx x___32  =    {49439, 49711, ~ 1};
int h7(void) ;
static struct hy y___30  =    {~ 2, 64784, 65056};
int h7(void) 
{ int tmp ;

  {
  if ((x___32.a & 16368) == (y___30.a & 1023)) {
    if ((x___32.b & 16368) == (y___30.b & 1023)) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;
  int tmp___11 ;
  int tmp___12 ;
  int tmp___13 ;
  int tmp___14 ;
  int tmp___15 ;
  int tmp___16 ;
  int tmp___17 ;
  int tmp___18 ;
  int tmp___19 ;
  int tmp___20 ;
  int tmp___21 ;
  int tmp___22 ;
  int tmp___23 ;
  int tmp___24 ;
  int tmp___25 ;
  int tmp___26 ;
  int tmp___27 ;
  int tmp___28 ;
  int tmp___29 ;
  int tmp___30 ;
  int tmp___31 ;
  int tmp___32 ;

  {
  tmp = a1();
  if (! tmp) {
    abort();
  }
  tmp___0 = a2();
  if (! tmp___0) {
    abort();
  }
  tmp___1 = a3();
  if (! tmp___1) {
    abort();
  }
  tmp___2 = b1();
  if (! tmp___2) {
    abort();
  }
  tmp___3 = b2();
  if (! tmp___3) {
    abort();
  }
  tmp___4 = b3();
  if (! tmp___4) {
    abort();
  }
  tmp___5 = c1();
  if (! tmp___5) {
    abort();
  }
  tmp___6 = c2();
  if (! tmp___6) {
    abort();
  }
  tmp___7 = c3();
  if (! tmp___7) {
    abort();
  }
  tmp___8 = d1();
  if (! tmp___8) {
    abort();
  }
  tmp___9 = d2();
  if (! tmp___9) {
    abort();
  }
  tmp___10 = d3();
  if (! tmp___10) {
    abort();
  }
  tmp___11 = e1();
  if (! tmp___11) {
    abort();
  }
  tmp___12 = e2();
  if (! tmp___12) {
    abort();
  }
  tmp___13 = e3();
  if (! tmp___13) {
    abort();
  }
  tmp___14 = e4();
  if (! tmp___14) {
    abort();
  }
  tmp___15 = f1();
  if (! tmp___15) {
    abort();
  }
  tmp___16 = f2();
  if (! tmp___16) {
    abort();
  }
  tmp___17 = f3();
  if (! tmp___17) {
    abort();
  }
  tmp___18 = f4();
  if (! tmp___18) {
    abort();
  }
  tmp___19 = g1();
  if (! tmp___19) {
    abort();
  }
  tmp___20 = g2();
  if (! tmp___20) {
    abort();
  }
  tmp___21 = g3();
  if (! tmp___21) {
    abort();
  }
  tmp___22 = g4();
  if (tmp___22) {
    abort();
  }
  tmp___23 = g5();
  if (tmp___23) {
    abort();
  }
  tmp___24 = g6();
  if (! tmp___24) {
    abort();
  }
  tmp___25 = g7();
  if (! tmp___25) {
    abort();
  }
  tmp___26 = h1();
  if (! tmp___26) {
    abort();
  }
  tmp___27 = h2();
  if (! tmp___27) {
    abort();
  }
  tmp___28 = h3();
  if (! tmp___28) {
    abort();
  }
  tmp___29 = h4();
  if (tmp___29) {
    abort();
  }
  tmp___30 = h5();
  if (tmp___30) {
    abort();
  }
  tmp___31 = h6();
  if (! tmp___31) {
    abort();
  }
  tmp___32 = h7();
  if (! tmp___32) {
    abort();
  }
  exit(0);
}
}
