/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

union __anonunion_data_21 {
   unsigned long word ;
   unsigned char byte[4] ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
unsigned long bad(int reg , unsigned long inWord ) 
{ union __anonunion_data_21 data ;

  {
  data.word = inWord;
  data.byte[reg] = (unsigned char)0;
  return (data.word);
}
}
int main(void) 
{ unsigned long tmp ;

  {
  if (sizeof(long ) != 4UL) {
    exit(0);
  }
  tmp = bad(0, 3735928559UL);
  if (tmp == 3735928559UL) {
    abort();
  }
  exit(0);
}
}
