/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct __anonstruct_Test1_21 {
   int v[4] ;
};
typedef struct __anonstruct_Test1_21 Test1;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
Test1 func2(void) ;
int func1(void) 
{ Test1 test ;

  {
  test = func2();
  if (test.v[0] != 10) {
    abort();
  }
  if (test.v[1] != 20) {
    abort();
  }
  if (test.v[2] != 30) {
    abort();
  }
  if (test.v[3] != 40) {
    abort();
  }
  return (0);
}
}
Test1 func2(void) 
{ Test1 tmp ;

  {
  tmp.v[0] = 10;
  tmp.v[1] = 20;
  tmp.v[2] = 30;
  tmp.v[3] = 40;
  return (tmp);
}
}
int main(void) 
{ 

  {
  func1();
  exit(0);
}
}
