/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int gfbyte(void) 
{ 

  {
  return (0);
}
}
int main(void) 
{ int i ;
  int j ;
  int k ;
  int tmp ;

  {
  i = gfbyte();
  i ++;
  if (i == 0) {
    k = 0;
  } else {
    k = i;
  }
  if (i != 1) {
    abort();
  }
  k = 1;
  if (k <= i) {
    while (1) {
      j = gfbyte();
      tmp = k;
      k ++;
      if (! (tmp < i)) {
        break;
      }
    }
  }
  exit(0);
}
}
