/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "990804-1.c"
int gfbyte(void) 
{ 

  {
#line 4
  return (0);
}
}
#line 7 "990804-1.c"
int main(void) 
{ int i ;
  int j ;
  int k ;
  int tmp ;

  {
#line 11
  i = gfbyte();
#line 13
  i ++;
#line 15
  if (i == 0) {
#line 16
    k = 0;
  } else {
#line 18
    k = i;
  }
#line 20
  if (i != 1) {
#line 21
    abort();
  }
#line 23
  k = 1;
#line 24
  if (k <= i) {
#line 25
    while (1) {
#line 26
      j = gfbyte();
#line 25
      tmp = k;
#line 25
      k ++;
#line 25
      if (! (tmp < i)) {
#line 25
        break;
      }
    }
  }
#line 29
  exit(0);
}
}
