/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
unsigned int test(unsigned int one , unsigned int bit ) 
{ unsigned int val ;
  unsigned int zero ;

  {
  val = bit & 1U;
  zero = one >> 1;
  val ++;
  return (zero + (val >> 1));
}
}
int main(void) 
{ unsigned int tmp ;
  unsigned int tmp___0 ;
  unsigned int tmp___1 ;

  {
  tmp = test(1U, 0U);
  if (tmp != 0U) {
    abort();
  }
  tmp___0 = test(1U, 1U);
  if (tmp___0 != 1U) {
    abort();
  }
  tmp___1 = test(1U, 65535U);
  if (tmp___1 != 1U) {
    abort();
  }
  exit(0);
  return (0);
}
}
