/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
long foo(long x ) 
{ 

  {
  if ((x & 4294901760L) == 2882338816L) {
    return (x & 65535L);
  }
  return (1L);
}
}
int main(void) 
{ long tmp ;
  long tmp___0 ;

  {
  tmp = foo(2882338816L);
  if (tmp != 0L) {
    abort();
  } else {
    tmp___0 = foo(0L);
    if (tmp___0 != 1L) {
      abort();
    }
  }
  exit(0);
}
}
