/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 5 "990923-1.c"
long foo(long x ) 
{ 

  {
#line 8
  if ((x & 4294901760L) == 2882338816L) {
#line 9
    return (x & 65535L);
  }
#line 10
  return (1L);
}
}
#line 13 "990923-1.c"
int main(void) 
{ long tmp ;
  long tmp___0 ;

  {
#line 15
  tmp = foo(2882338816L);
#line 15
  if (tmp != 0L) {
#line 16
    abort();
  } else {
#line 15
    tmp___0 = foo(0L);
#line 15
    if (tmp___0 != 1L) {
#line 16
      abort();
    }
  }
#line 18
  exit(0);
}
}
