/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef int T0;
typedef long T1;
typedef long long T2;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int doit(int sel , int n , void *p ) 
{ T0 *p0 ;
  T1 *p1 ;
  T2 *p2 ;

  {
  p0 = (T0 *)p;
  p1 = (T1 *)p;
  p2 = (T2 *)p;
  switch (sel) {
  case 0: 
  while (1) {
    *p0 += *p0;
    n --;
    if (! n) {
      break;
    }
  }
  return (*p0 == 0);
  case 1: 
  while (1) {
    *p1 += *p1;
    n --;
    if (! n) {
      break;
    }
  }
  return (*p1 == 0L);
  case 2: 
  while (1) {
    *p2 += *p2;
    n --;
    if (! n) {
      break;
    }
  }
  return (*p2 == 0LL);
  default: 
  abort();
  }
}
}
int main(void) 
{ T0 v0 ;
  T1 v1 ;
  T2 v2 ;

  {
  v0 = 1;
  doit(0, 5, (void *)(& v0));
  v1 = 1L;
  doit(1, 5, (void *)(& v1));
  v2 = 1LL;
  doit(2, 5, (void *)(& v2));
  if (v0 != 32) {
    abort();
  }
  if (v1 != 32L) {
    abort();
  }
  if (v2 != 32LL) {
    abort();
  }
  exit(0);
}
}
