/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int blah  ;
int foo(void) 
{ int i ;

  {
  i = 0;
  while (i < 7) {
    if (i == 6) {
      blah = 4044;
    } else {
      blah = 4078;
    }
    i ++;
  }
  return (blah);
}
}
int main(void) 
{ int tmp ;

  {
  tmp = foo();
  if (tmp != 4044) {
    abort();
  }
  exit(0);
}
}
