/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "991030-1.c"
double x  =    0x1.fp1;
#line 3 "991030-1.c"
int main(void) 
{ 

  {
#line 5
  if (x != 3.875) {
#line 6
    abort();
  }
#line 7
  exit(0);
}
}
