/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct vc_data {
   unsigned long space ;
   unsigned char vc_palette[48] ;
};
struct vc {
   struct vc_data *d ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
struct vc_data a_con  ;
struct vc vc_cons[63]  = {      {& a_con}};
int default_red[16]  ;
int default_grn[16]  ;
int default_blu[16]  ;
void bar(int k ) ;
void reset_palette(int currcons ) 
{ int j ;
  int k ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
  k = 0;
  j = k;
  while (j < 16) {
    tmp = k;
    k ++;
    (vc_cons[currcons].d)->vc_palette[tmp] = (unsigned char )default_red[j];
    tmp___0 = k;
    k ++;
    (vc_cons[currcons].d)->vc_palette[tmp___0] = (unsigned char )default_grn[j];
    tmp___1 = k;
    k ++;
    (vc_cons[currcons].d)->vc_palette[tmp___1] = (unsigned char )default_blu[j];
    j ++;
  }
  bar(k);
  return;
}
}
void bar(int k ) 
{ 

  {
  if (k != 48) {
    abort();
  }
  return;
}
}
int main(void) 
{ 

  {
  reset_palette(0);
  exit(0);
}
}
