/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 9 "../../lib/includes/stdlib.h"
typedef unsigned int size_t;
#line 6 "../../lib/includes/stdarg.h"
typedef void *va_list;
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 27 "../../lib/includes/stdarg.h"
extern va_list __va_inc(va_list *ap , size_t size ) ;
#line 32
extern void __va_start(va_list *ap , void *pN ) ;
#line 37
extern void __va_end(va_list *ap ) ;
#line 7 "991216-2.c"
void test(int n  , ...) 
{ va_list ap ;
  int i ;
  va_list tmp ;
  va_list tmp___0 ;
  va_list tmp___1 ;

  {
#line 13
  __va_start(& ap, (void *)(& n));
#line 14
  i = 2;
#line 14
  while (i <= n) {
#line 16
    tmp = __va_inc(& ap, (unsigned int )sizeof(int ));
#line 16
    if (*((int *)tmp) != i) {
#line 17
      abort();
    }
#line 14
    i ++;
  }
#line 20
  tmp___0 = __va_inc(& ap, (unsigned int )sizeof(long long ));
#line 20
  if (*((long long *)tmp___0) != 81985529216486895LL) {
#line 21
    abort();
  }
#line 23
  tmp___1 = __va_inc(& ap, (unsigned int )sizeof(int ));
#line 23
  if (*((int *)tmp___1) != 85) {
#line 24
    abort();
  }
#line 26
  __va_end(& ap);
#line 27
  return;
}
}
#line 29 "991216-2.c"
int main(void) 
{ 

  {
#line 31
  test(1, 81985529216486895LL, 85);
#line 32
  test(2, 2, 81985529216486895LL, 85);
#line 33
  test(3, 2, 3, 81985529216486895LL, 85);
#line 34
  test(4, 2, 3, 4, 81985529216486895LL, 85);
#line 35
  test(5, 2, 3, 4, 5, 81985529216486895LL, 85);
#line 36
  test(6, 2, 3, 4, 5, 6, 81985529216486895LL, 85);
#line 37
  test(7, 2, 3, 4, 5, 6, 7, 81985529216486895LL, 85);
#line 38
  test(8, 2, 3, 4, 5, 6, 7, 8, 81985529216486895LL, 85);
#line 39
  exit(0);
}
}
