/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "991227-1.c"
char *doit(int flag ) 
{ char const   *tmp ;

  {
#line 4
  if (flag) {
#line 4
    tmp = "\000wrong\n";
  } else {
#line 4
    tmp = "\000right\n";
  }
#line 4
  return ((char *)(tmp + 1));
}
}
#line 6 "991227-1.c"
int main(void) 
{ char *result ;
  char *tmp ;

  {
#line 8
  tmp = doit(0);
#line 8
  result = tmp;
#line 9
  if ((int )*result == 114) {
#line 9
    if ((int )*(result + 1) == 105) {
#line 10
      exit(0);
    }
  }
#line 11
  abort();
#line 12
  return (0);
}
}
