/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
unsigned int sat_add(unsigned int i ) 
{ unsigned int ret ;

  {
  ret = i + 1U;
  if (ret < i) {
    ret = i;
  }
  return (ret);
}
}
int main(void) 
{ unsigned int tmp ;

  {
  tmp = sat_add(~ 0U);
  if (tmp != 4294967295U) {
    abort();
  }
  exit(0);
}
}
