/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern void exit(int  ) ;
extern void abort(void) ;
int foo(void) 
{ 

  {
  exit(0);
  return (0);
}
}
void bar(void) 
{ 

  {
  return;
}
}
int main(void) 
{ int tmp ;

  {
  tmp = foo();
  (*((long (*)(int  ))(& bar)))(tmp);
  abort();
  return (0);
}
}
