/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int foo(int x , int y ) 
{ int tmp ;

  {
  if (x <= y) {
    if ((unsigned int )x >= (unsigned int )y) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int main(void) 
{ int tmp ;

  {
  tmp = foo(-1, 0);
  if (! tmp) {
    abort();
  }
  return (0);
}
}
