/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct complex {
   float r ;
   float i ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
struct complex f(float a , float b ) 
{ struct complex c ;

  {
  c.r = a;
  c.i = b;
  return (c);
}
}
int main(void) 
{ struct complex z ;
  struct complex tmp ;

  {
  tmp = f((float )1.0, (float )0.0);
  z = tmp;
  if ((double )z.r != 1.0) {
    abort();
  } else {
    if ((double )z.i != 0.0) {
      abort();
    }
  }
  exit(0);
}
}
