/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
__inline static long g1(double x ) 
{ 

  {
  return ((long )((double )((long )x)));
}
}
long g2(double f ) 
{ 

  {
  return ((long )f);
}
}
double f(long i ) 
{ long tmp ;
  long tmp___0 ;
  long tmp___1 ;

  {
  tmp = g1((double )i);
  tmp___0 = g2((double )i);
  if (tmp != tmp___0) {
    abort();
  }
  tmp___1 = g2((double )i);
  return ((double )tmp___1);
}
}
int main(void) 
{ double tmp ;
  double tmp___0 ;
  long tmp___1 ;

  {
  tmp = f(123456789L);
  if (tmp != (double )123456789L) {
    abort();
  }
  tmp___0 = f(123456789L);
  tmp___1 = g2((double )123456789L);
  if (tmp___0 != (double )tmp___1) {
    abort();
  }
  exit(0);
}
}
