/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int f1(long a ) 
{ int i ;

  {
  i = 0;
  while (i < 10) {
    a --;
    if (a == -1L) {
      return (i);
    }
    i ++;
  }
  return (-1);
}
}
int f2(long a ) 
{ int i ;

  {
  i = 0;
  while (i < 10) {
    a --;
    if (a != -1L) {
      return (i);
    }
    i ++;
  }
  return (-1);
}
}
int f3(long a ) 
{ int i ;

  {
  i = 0;
  while (i < 10) {
    a --;
    if (a == 0L) {
      return (i);
    }
    i ++;
  }
  return (-1);
}
}
int f4(long a ) 
{ int i ;

  {
  i = 0;
  while (i < 10) {
    a --;
    if (a != 0L) {
      return (i);
    }
    i ++;
  }
  return (-1);
}
}
int f5(long a ) 
{ int i ;

  {
  i = 0;
  while (i < 10) {
    a ++;
    if (a == 0L) {
      return (i);
    }
    i ++;
  }
  return (-1);
}
}
int f6(long a ) 
{ int i ;

  {
  i = 0;
  while (i < 10) {
    a ++;
    if (a != 0L) {
      return (i);
    }
    i ++;
  }
  return (-1);
}
}
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;

  {
  tmp = f1(5L);
  if (tmp != 5) {
    abort();
  }
  tmp___0 = f2(1L);
  if (tmp___0 != 0) {
    abort();
  }
  tmp___1 = f2(0L);
  if (tmp___1 != 1) {
    abort();
  }
  tmp___2 = f3(5L);
  if (tmp___2 != 4) {
    abort();
  }
  tmp___3 = f4(1L);
  if (tmp___3 != 1) {
    abort();
  }
  tmp___4 = f4(0L);
  if (tmp___4 != 0) {
    abort();
  }
  tmp___5 = f5(-5L);
  if (tmp___5 != 4) {
    abort();
  }
  tmp___6 = f6(-1L);
  if (tmp___6 != 1) {
    abort();
  }
  tmp___7 = f6(0L);
  if (tmp___7 != 0) {
    abort();
  }
  exit(0);
}
}
