/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "divconst-1.c"
struct __anonstruct_t1_3 {
   unsigned int a ;
   unsigned int b ;
   unsigned int c ;
   unsigned int d ;
};
#line 2 "divconst-1.c"
typedef struct __anonstruct_t1_3 t1;
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 7 "divconst-1.c"
void f(t1 *ps ) 
{ 

  {
#line 9
  ps->a = 10000U;
#line 10
  ps->b = ps->a / 3U;
#line 11
  ps->c = 10000U;
#line 12
  ps->d = ps->c / 3U;
#line 13
  return;
}
}
#line 15 "divconst-1.c"
int main(void) 
{ t1 s ;

  {
#line 18
  f(& s);
#line 19
  if (s.a != 10000U) {
#line 20
    abort();
  } else {
#line 19
    if (s.b != 3333U) {
#line 20
      abort();
    } else {
#line 19
      if (s.c != 10000U) {
#line 20
        abort();
      } else {
#line 19
        if (s.d != 3333U) {
#line 20
          abort();
        }
      }
    }
  }
#line 21
  exit(0);
}
}
