/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "divcmp-1.c"
int test1(int x ) 
{ 

  {
#line 6
  return (x / 10 == 2);
}
}
#line 9 "divcmp-1.c"
int test1u(unsigned int x ) 
{ 

  {
#line 11
  return (x / 10U == 2U);
}
}
#line 14 "divcmp-1.c"
int test2(int x ) 
{ 

  {
#line 16
  return (x / 10 == 0);
}
}
#line 19 "divcmp-1.c"
int test2u(unsigned int x ) 
{ 

  {
#line 21
  return (x / 10U == 0U);
}
}
#line 24 "divcmp-1.c"
int test3(int x ) 
{ 

  {
#line 26
  return (x / 10 != 2);
}
}
#line 29 "divcmp-1.c"
int test3u(unsigned int x ) 
{ 

  {
#line 31
  return (x / 10U != 2U);
}
}
#line 34 "divcmp-1.c"
int test4(int x ) 
{ 

  {
#line 36
  return (x / 10 != 0);
}
}
#line 39 "divcmp-1.c"
int test4u(unsigned int x ) 
{ 

  {
#line 41
  return (x / 10U != 0U);
}
}
#line 44 "divcmp-1.c"
int test5(int x ) 
{ 

  {
#line 46
  return (x / 10 < 2);
}
}
#line 49 "divcmp-1.c"
int test5u(unsigned int x ) 
{ 

  {
#line 51
  return (x / 10U < 2U);
}
}
#line 54 "divcmp-1.c"
int test6(int x ) 
{ 

  {
#line 56
  return (x / 10 < 0);
}
}
#line 59 "divcmp-1.c"
int test7(int x ) 
{ 

  {
#line 61
  return (x / 10 <= 2);
}
}
#line 64 "divcmp-1.c"
int test7u(unsigned int x ) 
{ 

  {
#line 66
  return (x / 10U <= 2U);
}
}
#line 69 "divcmp-1.c"
int test8(int x ) 
{ 

  {
#line 71
  return (x / 10 <= 0);
}
}
#line 74 "divcmp-1.c"
int test8u(unsigned int x ) 
{ 

  {
#line 76
  return (x / 10U <= 0U);
}
}
#line 79 "divcmp-1.c"
int test9(int x ) 
{ 

  {
#line 81
  return (x / 10 > 2);
}
}
#line 84 "divcmp-1.c"
int test9u(unsigned int x ) 
{ 

  {
#line 86
  return (x / 10U > 2U);
}
}
#line 89 "divcmp-1.c"
int test10(int x ) 
{ 

  {
#line 91
  return (x / 10 > 0);
}
}
#line 94 "divcmp-1.c"
int test10u(unsigned int x ) 
{ 

  {
#line 96
  return (x / 10U > 0U);
}
}
#line 99 "divcmp-1.c"
int test11(int x ) 
{ 

  {
#line 101
  return (x / 10 >= 2);
}
}
#line 104 "divcmp-1.c"
int test11u(unsigned int x ) 
{ 

  {
#line 106
  return (x / 10U >= 2U);
}
}
#line 109 "divcmp-1.c"
int test12(int x ) 
{ 

  {
#line 111
  return (x / 10 >= 0);
}
}
#line 115 "divcmp-1.c"
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;
  int tmp___11 ;
  int tmp___12 ;
  int tmp___13 ;
  int tmp___14 ;
  int tmp___15 ;
  int tmp___16 ;
  int tmp___17 ;
  int tmp___18 ;
  int tmp___19 ;
  int tmp___20 ;
  int tmp___21 ;
  int tmp___22 ;
  int tmp___23 ;
  int tmp___24 ;
  int tmp___25 ;
  int tmp___26 ;
  int tmp___27 ;
  int tmp___28 ;
  int tmp___29 ;
  int tmp___30 ;
  int tmp___31 ;
  int tmp___32 ;
  int tmp___33 ;
  int tmp___34 ;
  int tmp___35 ;
  int tmp___36 ;
  int tmp___37 ;
  int tmp___38 ;
  int tmp___39 ;
  int tmp___40 ;
  int tmp___41 ;
  int tmp___42 ;
  int tmp___43 ;
  int tmp___44 ;
  int tmp___45 ;
  int tmp___46 ;
  int tmp___47 ;
  int tmp___48 ;
  int tmp___49 ;
  int tmp___50 ;
  int tmp___51 ;
  int tmp___52 ;
  int tmp___53 ;
  int tmp___54 ;
  int tmp___55 ;
  int tmp___56 ;
  int tmp___57 ;
  int tmp___58 ;
  int tmp___59 ;
  int tmp___60 ;
  int tmp___61 ;
  int tmp___62 ;
  int tmp___63 ;
  int tmp___64 ;
  int tmp___65 ;
  int tmp___66 ;
  int tmp___67 ;
  int tmp___68 ;
  int tmp___69 ;
  int tmp___70 ;
  int tmp___71 ;
  int tmp___72 ;
  int tmp___73 ;
  int tmp___74 ;
  int tmp___75 ;
  int tmp___76 ;
  int tmp___77 ;
  int tmp___78 ;
  int tmp___79 ;
  int tmp___80 ;
  int tmp___81 ;
  int tmp___82 ;
  int tmp___83 ;
  int tmp___84 ;
  int tmp___85 ;
  int tmp___86 ;
  int tmp___87 ;
  int tmp___88 ;
  int tmp___89 ;
  int tmp___90 ;
  int tmp___91 ;
  int tmp___92 ;
  int tmp___93 ;
  int tmp___94 ;
  int tmp___95 ;
  int tmp___96 ;
  int tmp___97 ;
  int tmp___98 ;
  int tmp___99 ;
  int tmp___100 ;
  int tmp___101 ;
  int tmp___102 ;
  int tmp___103 ;
  int tmp___104 ;
  int tmp___105 ;
  int tmp___106 ;

  {
#line 117
  tmp = test1(19);
#line 117
  if (tmp != 0) {
#line 118
    abort();
  }
#line 119
  tmp___0 = test1(20);
#line 119
  if (tmp___0 != 1) {
#line 120
    abort();
  }
#line 121
  tmp___1 = test1(29);
#line 121
  if (tmp___1 != 1) {
#line 122
    abort();
  }
#line 123
  tmp___2 = test1(30);
#line 123
  if (tmp___2 != 0) {
#line 124
    abort();
  }
#line 126
  tmp___3 = test1u(19U);
#line 126
  if (tmp___3 != 0) {
#line 127
    abort();
  }
#line 128
  tmp___4 = test1u(20U);
#line 128
  if (tmp___4 != 1) {
#line 129
    abort();
  }
#line 130
  tmp___5 = test1u(29U);
#line 130
  if (tmp___5 != 1) {
#line 131
    abort();
  }
#line 132
  tmp___6 = test1u(30U);
#line 132
  if (tmp___6 != 0) {
#line 133
    abort();
  }
#line 135
  tmp___7 = test2(0);
#line 135
  if (tmp___7 != 1) {
#line 136
    abort();
  }
#line 137
  tmp___8 = test2(9);
#line 137
  if (tmp___8 != 1) {
#line 138
    abort();
  }
#line 139
  tmp___9 = test2(10);
#line 139
  if (tmp___9 != 0) {
#line 140
    abort();
  }
#line 141
  tmp___10 = test2(-1);
#line 141
  if (tmp___10 != 1) {
#line 142
    abort();
  }
#line 143
  tmp___11 = test2(-9);
#line 143
  if (tmp___11 != 1) {
#line 144
    abort();
  }
#line 145
  tmp___12 = test2(-10);
#line 145
  if (tmp___12 != 0) {
#line 146
    abort();
  }
#line 148
  tmp___13 = test2u(0U);
#line 148
  if (tmp___13 != 1) {
#line 149
    abort();
  }
#line 150
  tmp___14 = test2u(9U);
#line 150
  if (tmp___14 != 1) {
#line 151
    abort();
  }
#line 152
  tmp___15 = test2u(10U);
#line 152
  if (tmp___15 != 0) {
#line 153
    abort();
  }
#line 154
  tmp___16 = test2u(4294967295U);
#line 154
  if (tmp___16 != 0) {
#line 155
    abort();
  }
#line 156
  tmp___17 = test2u(4294967287U);
#line 156
  if (tmp___17 != 0) {
#line 157
    abort();
  }
#line 158
  tmp___18 = test2u(4294967286U);
#line 158
  if (tmp___18 != 0) {
#line 159
    abort();
  }
#line 161
  tmp___19 = test3(19);
#line 161
  if (tmp___19 != 1) {
#line 162
    abort();
  }
#line 163
  tmp___20 = test3(20);
#line 163
  if (tmp___20 != 0) {
#line 164
    abort();
  }
#line 165
  tmp___21 = test3(29);
#line 165
  if (tmp___21 != 0) {
#line 166
    abort();
  }
#line 167
  tmp___22 = test3(30);
#line 167
  if (tmp___22 != 1) {
#line 168
    abort();
  }
#line 170
  tmp___23 = test3u(19U);
#line 170
  if (tmp___23 != 1) {
#line 171
    abort();
  }
#line 172
  tmp___24 = test3u(20U);
#line 172
  if (tmp___24 != 0) {
#line 173
    abort();
  }
#line 174
  tmp___25 = test3u(29U);
#line 174
  if (tmp___25 != 0) {
#line 175
    abort();
  }
#line 176
  tmp___26 = test3u(30U);
#line 176
  if (tmp___26 != 1) {
#line 177
    abort();
  }
#line 179
  tmp___27 = test4(0);
#line 179
  if (tmp___27 != 0) {
#line 180
    abort();
  }
#line 181
  tmp___28 = test4(9);
#line 181
  if (tmp___28 != 0) {
#line 182
    abort();
  }
#line 183
  tmp___29 = test4(10);
#line 183
  if (tmp___29 != 1) {
#line 184
    abort();
  }
#line 185
  tmp___30 = test4(-1);
#line 185
  if (tmp___30 != 0) {
#line 186
    abort();
  }
#line 187
  tmp___31 = test4(-9);
#line 187
  if (tmp___31 != 0) {
#line 188
    abort();
  }
#line 189
  tmp___32 = test4(-10);
#line 189
  if (tmp___32 != 1) {
#line 190
    abort();
  }
#line 192
  tmp___33 = test4u(0U);
#line 192
  if (tmp___33 != 0) {
#line 193
    abort();
  }
#line 194
  tmp___34 = test4u(9U);
#line 194
  if (tmp___34 != 0) {
#line 195
    abort();
  }
#line 196
  tmp___35 = test4u(10U);
#line 196
  if (tmp___35 != 1) {
#line 197
    abort();
  }
#line 198
  tmp___36 = test4u(4294967295U);
#line 198
  if (tmp___36 != 1) {
#line 199
    abort();
  }
#line 200
  tmp___37 = test4u(4294967287U);
#line 200
  if (tmp___37 != 1) {
#line 201
    abort();
  }
#line 202
  tmp___38 = test4u(4294967286U);
#line 202
  if (tmp___38 != 1) {
#line 203
    abort();
  }
#line 205
  tmp___39 = test5(19);
#line 205
  if (tmp___39 != 1) {
#line 206
    abort();
  }
#line 207
  tmp___40 = test5(20);
#line 207
  if (tmp___40 != 0) {
#line 208
    abort();
  }
#line 209
  tmp___41 = test5(29);
#line 209
  if (tmp___41 != 0) {
#line 210
    abort();
  }
#line 211
  tmp___42 = test5(30);
#line 211
  if (tmp___42 != 0) {
#line 212
    abort();
  }
#line 214
  tmp___43 = test5u(19U);
#line 214
  if (tmp___43 != 1) {
#line 215
    abort();
  }
#line 216
  tmp___44 = test5u(20U);
#line 216
  if (tmp___44 != 0) {
#line 217
    abort();
  }
#line 218
  tmp___45 = test5u(29U);
#line 218
  if (tmp___45 != 0) {
#line 219
    abort();
  }
#line 220
  tmp___46 = test5u(30U);
#line 220
  if (tmp___46 != 0) {
#line 221
    abort();
  }
#line 223
  tmp___47 = test6(0);
#line 223
  if (tmp___47 != 0) {
#line 224
    abort();
  }
#line 225
  tmp___48 = test6(9);
#line 225
  if (tmp___48 != 0) {
#line 226
    abort();
  }
#line 227
  tmp___49 = test6(10);
#line 227
  if (tmp___49 != 0) {
#line 228
    abort();
  }
#line 229
  tmp___50 = test6(-1);
#line 229
  if (tmp___50 != 0) {
#line 230
    abort();
  }
#line 231
  tmp___51 = test6(-9);
#line 231
  if (tmp___51 != 0) {
#line 232
    abort();
  }
#line 233
  tmp___52 = test6(-10);
#line 233
  if (tmp___52 != 1) {
#line 234
    abort();
  }
#line 236
  tmp___53 = test7(19);
#line 236
  if (tmp___53 != 1) {
#line 237
    abort();
  }
#line 238
  tmp___54 = test7(20);
#line 238
  if (tmp___54 != 1) {
#line 239
    abort();
  }
#line 240
  tmp___55 = test7(29);
#line 240
  if (tmp___55 != 1) {
#line 241
    abort();
  }
#line 242
  tmp___56 = test7(30);
#line 242
  if (tmp___56 != 0) {
#line 243
    abort();
  }
#line 245
  tmp___57 = test7u(19U);
#line 245
  if (tmp___57 != 1) {
#line 246
    abort();
  }
#line 247
  tmp___58 = test7u(20U);
#line 247
  if (tmp___58 != 1) {
#line 248
    abort();
  }
#line 249
  tmp___59 = test7u(29U);
#line 249
  if (tmp___59 != 1) {
#line 250
    abort();
  }
#line 251
  tmp___60 = test7u(30U);
#line 251
  if (tmp___60 != 0) {
#line 252
    abort();
  }
#line 254
  tmp___61 = test8(0);
#line 254
  if (tmp___61 != 1) {
#line 255
    abort();
  }
#line 256
  tmp___62 = test8(9);
#line 256
  if (tmp___62 != 1) {
#line 257
    abort();
  }
#line 258
  tmp___63 = test8(10);
#line 258
  if (tmp___63 != 0) {
#line 259
    abort();
  }
#line 260
  tmp___64 = test8(-1);
#line 260
  if (tmp___64 != 1) {
#line 261
    abort();
  }
#line 262
  tmp___65 = test8(-9);
#line 262
  if (tmp___65 != 1) {
#line 263
    abort();
  }
#line 264
  tmp___66 = test8(-10);
#line 264
  if (tmp___66 != 1) {
#line 265
    abort();
  }
#line 267
  tmp___67 = test8u(0U);
#line 267
  if (tmp___67 != 1) {
#line 268
    abort();
  }
#line 269
  tmp___68 = test8u(9U);
#line 269
  if (tmp___68 != 1) {
#line 270
    abort();
  }
#line 271
  tmp___69 = test8u(10U);
#line 271
  if (tmp___69 != 0) {
#line 272
    abort();
  }
#line 273
  tmp___70 = test8u(4294967295U);
#line 273
  if (tmp___70 != 0) {
#line 274
    abort();
  }
#line 275
  tmp___71 = test8u(4294967287U);
#line 275
  if (tmp___71 != 0) {
#line 276
    abort();
  }
#line 277
  tmp___72 = test8u(4294967286U);
#line 277
  if (tmp___72 != 0) {
#line 278
    abort();
  }
#line 280
  tmp___73 = test9(19);
#line 280
  if (tmp___73 != 0) {
#line 281
    abort();
  }
#line 282
  tmp___74 = test9(20);
#line 282
  if (tmp___74 != 0) {
#line 283
    abort();
  }
#line 284
  tmp___75 = test9(29);
#line 284
  if (tmp___75 != 0) {
#line 285
    abort();
  }
#line 286
  tmp___76 = test9(30);
#line 286
  if (tmp___76 != 1) {
#line 287
    abort();
  }
#line 289
  tmp___77 = test9u(19U);
#line 289
  if (tmp___77 != 0) {
#line 290
    abort();
  }
#line 291
  tmp___78 = test9u(20U);
#line 291
  if (tmp___78 != 0) {
#line 292
    abort();
  }
#line 293
  tmp___79 = test9u(29U);
#line 293
  if (tmp___79 != 0) {
#line 294
    abort();
  }
#line 295
  tmp___80 = test9u(30U);
#line 295
  if (tmp___80 != 1) {
#line 296
    abort();
  }
#line 298
  tmp___81 = test10(0);
#line 298
  if (tmp___81 != 0) {
#line 299
    abort();
  }
#line 300
  tmp___82 = test10(9);
#line 300
  if (tmp___82 != 0) {
#line 301
    abort();
  }
#line 302
  tmp___83 = test10(10);
#line 302
  if (tmp___83 != 1) {
#line 303
    abort();
  }
#line 304
  tmp___84 = test10(-1);
#line 304
  if (tmp___84 != 0) {
#line 305
    abort();
  }
#line 306
  tmp___85 = test10(-9);
#line 306
  if (tmp___85 != 0) {
#line 307
    abort();
  }
#line 308
  tmp___86 = test10(-10);
#line 308
  if (tmp___86 != 0) {
#line 309
    abort();
  }
#line 311
  tmp___87 = test10u(0U);
#line 311
  if (tmp___87 != 0) {
#line 312
    abort();
  }
#line 313
  tmp___88 = test10u(9U);
#line 313
  if (tmp___88 != 0) {
#line 314
    abort();
  }
#line 315
  tmp___89 = test10u(10U);
#line 315
  if (tmp___89 != 1) {
#line 316
    abort();
  }
#line 317
  tmp___90 = test10u(4294967295U);
#line 317
  if (tmp___90 != 1) {
#line 318
    abort();
  }
#line 319
  tmp___91 = test10u(4294967287U);
#line 319
  if (tmp___91 != 1) {
#line 320
    abort();
  }
#line 321
  tmp___92 = test10u(4294967286U);
#line 321
  if (tmp___92 != 1) {
#line 322
    abort();
  }
#line 324
  tmp___93 = test11(19);
#line 324
  if (tmp___93 != 0) {
#line 325
    abort();
  }
#line 326
  tmp___94 = test11(20);
#line 326
  if (tmp___94 != 1) {
#line 327
    abort();
  }
#line 328
  tmp___95 = test11(29);
#line 328
  if (tmp___95 != 1) {
#line 329
    abort();
  }
#line 330
  tmp___96 = test11(30);
#line 330
  if (tmp___96 != 1) {
#line 331
    abort();
  }
#line 333
  tmp___97 = test11u(19U);
#line 333
  if (tmp___97 != 0) {
#line 334
    abort();
  }
#line 335
  tmp___98 = test11u(20U);
#line 335
  if (tmp___98 != 1) {
#line 336
    abort();
  }
#line 337
  tmp___99 = test11u(29U);
#line 337
  if (tmp___99 != 1) {
#line 338
    abort();
  }
#line 339
  tmp___100 = test11u(30U);
#line 339
  if (tmp___100 != 1) {
#line 340
    abort();
  }
#line 342
  tmp___101 = test12(0);
#line 342
  if (tmp___101 != 1) {
#line 343
    abort();
  }
#line 344
  tmp___102 = test12(9);
#line 344
  if (tmp___102 != 1) {
#line 345
    abort();
  }
#line 346
  tmp___103 = test12(10);
#line 346
  if (tmp___103 != 1) {
#line 347
    abort();
  }
#line 348
  tmp___104 = test12(-1);
#line 348
  if (tmp___104 != 1) {
#line 349
    abort();
  }
#line 350
  tmp___105 = test12(-9);
#line 350
  if (tmp___105 != 1) {
#line 351
    abort();
  }
#line 352
  tmp___106 = test12(-10);
#line 352
  if (tmp___106 != 0) {
#line 353
    abort();
  }
#line 355
  return (0);
}
}
