/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct __anonstruct_t1_21 {
   unsigned int a ;
   unsigned int b ;
   unsigned int c ;
   unsigned int d ;
};
typedef struct __anonstruct_t1_21 t1;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
void f(t1 *ps ) 
{ 

  {
  ps->a = 10000U;
  ps->b = ps->a / 3U;
  ps->c = 10000U;
  ps->d = ps->c / 3U;
  return;
}
}
int main(void) 
{ t1 s ;

  {
  f(& s);
  if (s.a != 10000U) {
    abort();
  } else {
    if (s.b != 3333U) {
      abort();
    } else {
      if (s.c != 10000U) {
        abort();
      } else {
        if (s.d != 3333U) {
          abort();
        }
      }
    }
  }
  exit(0);
}
}
