/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int test1(int x ) 
{ 

  {
  return (x / 10 == 2);
}
}
int test2(int x ) 
{ 

  {
  return (x / 10 == 0);
}
}
int test3(int x ) 
{ 

  {
  return (x / 10 == -2);
}
}
int test4(int x ) 
{ 

  {
  return (x / -10 == 2);
}
}
int test5(int x ) 
{ 

  {
  return (x / -10 == 0);
}
}
int test6(int x ) 
{ 

  {
  return (x / -10 == -2);
}
}
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;
  int tmp___11 ;
  int tmp___12 ;
  int tmp___13 ;
  int tmp___14 ;
  int tmp___15 ;
  int tmp___16 ;
  int tmp___17 ;
  int tmp___18 ;
  int tmp___19 ;
  int tmp___20 ;
  int tmp___21 ;
  int tmp___22 ;

  {
  tmp = test1(19);
  if (tmp != 0) {
    abort();
  }
  tmp___0 = test1(20);
  if (tmp___0 != 1) {
    abort();
  }
  tmp___1 = test1(29);
  if (tmp___1 != 1) {
    abort();
  }
  tmp___2 = test1(30);
  if (tmp___2 != 0) {
    abort();
  }
  tmp___3 = test2(-10);
  if (tmp___3 != 0) {
    abort();
  }
  tmp___4 = test2(-9);
  if (tmp___4 != 1) {
    abort();
  }
  tmp___5 = test2(9);
  if (tmp___5 != 1) {
    abort();
  }
  tmp___6 = test2(10);
  if (tmp___6 != 0) {
    abort();
  }
  tmp___7 = test3(-30);
  if (tmp___7 != 0) {
    abort();
  }
  tmp___8 = test3(-29);
  if (tmp___8 != 1) {
    abort();
  }
  tmp___9 = test3(-20);
  if (tmp___9 != 1) {
    abort();
  }
  tmp___10 = test3(-19);
  if (tmp___10 != 0) {
    abort();
  }
  tmp___11 = test4(-30);
  if (tmp___11 != 0) {
    abort();
  }
  tmp___12 = test4(-29);
  if (tmp___12 != 1) {
    abort();
  }
  tmp___13 = test4(-20);
  if (tmp___13 != 1) {
    abort();
  }
  tmp___14 = test4(-19);
  if (tmp___14 != 0) {
    abort();
  }
  tmp___15 = test5(-10);
  if (tmp___15 != 0) {
    abort();
  }
  tmp___16 = test5(-9);
  if (tmp___16 != 1) {
    abort();
  }
  tmp___17 = test5(9);
  if (tmp___17 != 1) {
    abort();
  }
  tmp___18 = test5(10);
  if (tmp___18 != 0) {
    abort();
  }
  tmp___19 = test6(19);
  if (tmp___19 != 0) {
    abort();
  }
  tmp___20 = test6(20);
  if (tmp___20 != 1) {
    abort();
  }
  tmp___21 = test6(29);
  if (tmp___21 != 1) {
    abort();
  }
  tmp___22 = test6(30);
  if (tmp___22 != 0) {
    abort();
  }
  return (0);
}
}
