/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

enum __anonenum_token_21 {
    END = -1,
    EMPTY = 256,
    BACKREF = 257,
    BEGLINE = 258,
    ENDLINE = 259,
    BEGWORD = 260,
    ENDWORD = 261,
    LIMWORD = 262,
    NOTLIMWORD = 263,
    QMARK = 264,
    STAR = 265,
    PLUS = 266,
    REPMN = 267,
    CAT = 268,
    OR = 269,
    ORTOP = 270,
    LPAREN = 271,
    RPAREN = 272,
    CSET = 273
} ;
typedef enum __anonenum_token_21 token;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
static token tok  ;
static int atom(void) 
{ 

  {
  if ((int )tok >= 0) {
    if ((int )tok < 1 << 8) {
      return (1);
    } else {
      goto _L;
    }
  } else {
    _L: /* CIL Label */ 
    if ((int )tok >= 273) {
      return (1);
    } else {
      if ((int )tok == 257) {
        return (1);
      } else {
        if ((int )tok == 258) {
          return (1);
        } else {
          if ((int )tok == 259) {
            return (1);
          } else {
            if ((int )tok == 260) {
              return (1);
            } else {
              if ((int )tok == 261) {
                return (1);
              } else {
                if ((int )tok == 262) {
                  return (1);
                } else {
                  if ((int )tok == 263) {
                    return (1);
                  } else {
                    return (0);
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
}
int main(void) 
{ int tmp ;

  {
  tok = (enum __anonenum_token_21 )0;
  tmp = atom();
  if (tmp != 1) {
    abort();
  }
  exit(0);
}
}
