/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 12 "extzvsi.c"
struct ieee {
   unsigned int negative : 1 ;
   unsigned int exponent : 11 ;
   unsigned int mantissa0 : 20 ;
   unsigned int mantissa1 : 32 ;
};
#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 12 "extzvsi.c"
struct ieee x  ;
#line 20 "extzvsi.c"
unsigned int foo(void) 
{ unsigned int exponent ;

  {
#line 25
  exponent = x.exponent;
#line 26
  if (exponent == 0U) {
#line 27
    return (1U);
  } else {
#line 28
    if (exponent > 1U) {
#line 29
      return (2U);
    }
  }
#line 30
  return (0U);
}
}
#line 33 "extzvsi.c"
int main(void) 
{ unsigned int tmp ;

  {
#line 35
  x.exponent = 1U;
#line 36
  tmp = foo();
#line 36
  if (tmp != 0U) {
#line 37
    abort();
  }
#line 38
  return (0);
}
}
