/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
double d  =    1024.0 - 1.0 / 32768.0;
extern double floor(double  ) ;
int main(void) 
{ double df ;
  double tmp ;
  float f1 ;
  double tmp___0 ;

  {
  tmp = floor(d);
  df = tmp;
  tmp___0 = floor(d);
  f1 = (float )tmp___0;
  if ((int )df != 1023) {
    abort();
  } else {
    if ((int )f1 != 1023) {
      abort();
    }
  }
  return (0);
}
}
