/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
static double f(float a ) ;
static double (*fp)(float a )  ;
int main(void) 
{ double tmp ;

  {
  fp = & f;
  tmp = (*fp)((float )1);
  if (tmp != 1.0) {
    abort();
  }
  exit(0);
}
}
static double f(float a ) 
{ 

  {
  return ((double )a);
}
}
