/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 8 "../../lib/includes/stdio.h"
struct __anonstruct_FILE_3 {
   unsigned long long offset ;
   unsigned short handle ;
   unsigned char eof ;
};
#line 8 "../../lib/includes/stdio.h"
typedef struct __anonstruct_FILE_3 FILE;
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 20 "../../lib/includes/stdio.h"
extern FILE *stderr ;
#line 10 "gofast.c"
float fp_add(float a , float b ) 
{ 

  {
#line 10
  return (a + b);
}
}
#line 11 "gofast.c"
float fp_sub(float a , float b ) 
{ 

  {
#line 11
  return (a - b);
}
}
#line 12 "gofast.c"
float fp_mul(float a , float b ) 
{ 

  {
#line 12
  return (a * b);
}
}
#line 13 "gofast.c"
float fp_div(float a , float b ) 
{ 

  {
#line 13
  return (a / b);
}
}
#line 14 "gofast.c"
float fp_neg(float a ) 
{ 

  {
#line 14
  return (- a);
}
}
#line 16 "gofast.c"
double dp_add(double a , double b ) 
{ 

  {
#line 16
  return (a + b);
}
}
#line 17 "gofast.c"
double dp_sub(double a , double b ) 
{ 

  {
#line 17
  return (a - b);
}
}
#line 18 "gofast.c"
double dp_mul(double a , double b ) 
{ 

  {
#line 18
  return (a * b);
}
}
#line 19 "gofast.c"
double dp_div(double a , double b ) 
{ 

  {
#line 19
  return (a / b);
}
}
#line 20 "gofast.c"
double dp_neg(double a ) 
{ 

  {
#line 20
  return (- a);
}
}
#line 22 "gofast.c"
double fp_to_dp(float f ) 
{ 

  {
#line 22
  return ((double )f);
}
}
#line 23 "gofast.c"
float dp_to_fp(double d ) 
{ 

  {
#line 23
  return ((float )d);
}
}
#line 25 "gofast.c"
int eqsf2(float a , float b ) 
{ 

  {
#line 25
  return (a == b);
}
}
#line 26 "gofast.c"
int nesf2(float a , float b ) 
{ 

  {
#line 26
  return (a != b);
}
}
#line 27 "gofast.c"
int gtsf2(float a , float b ) 
{ 

  {
#line 27
  return (a > b);
}
}
#line 28 "gofast.c"
int gesf2(float a , float b ) 
{ 

  {
#line 28
  return (a >= b);
}
}
#line 29 "gofast.c"
int ltsf2(float a , float b ) 
{ 

  {
#line 29
  return (a < b);
}
}
#line 30 "gofast.c"
int lesf2(float a , float b ) 
{ 

  {
#line 30
  return (a <= b);
}
}
#line 32 "gofast.c"
int eqdf2(double a , double b ) 
{ 

  {
#line 32
  return (a == b);
}
}
#line 33 "gofast.c"
int nedf2(double a , double b ) 
{ 

  {
#line 33
  return (a != b);
}
}
#line 34 "gofast.c"
int gtdf2(double a , double b ) 
{ 

  {
#line 34
  return (a > b);
}
}
#line 35 "gofast.c"
int gedf2(double a , double b ) 
{ 

  {
#line 35
  return (a >= b);
}
}
#line 36 "gofast.c"
int ltdf2(double a , double b ) 
{ 

  {
#line 36
  return (a < b);
}
}
#line 37 "gofast.c"
int ledf2(double a , double b ) 
{ 

  {
#line 37
  return (a <= b);
}
}
#line 39 "gofast.c"
float floatsisf(int i ) 
{ 

  {
#line 39
  return ((float )i);
}
}
#line 40 "gofast.c"
double floatsidf(int i ) 
{ 

  {
#line 40
  return ((double )i);
}
}
#line 41 "gofast.c"
int fixsfsi(float f ) 
{ 

  {
#line 41
  return ((int )f);
}
}
#line 42 "gofast.c"
int fixdfsi(double d ) 
{ 

  {
#line 42
  return ((int )d);
}
}
#line 43 "gofast.c"
unsigned int fixunssfsi(float f ) 
{ 

  {
#line 43
  return ((unsigned int )f);
}
}
#line 44 "gofast.c"
unsigned int fixunsdfsi(double d ) 
{ 

  {
#line 44
  return ((unsigned int )d);
}
}
#line 46 "gofast.c"
int fail_count  =    0;
#line 52
extern int ( /* missing proto */  fprintf)() ;
#line 48 "gofast.c"
int fail(char *msg ) 
{ 

  {
#line 51
  fail_count ++;
#line 52
  fprintf(stderr, "Test failed: %s\n", msg);
#line 53
  return (0);
}
}
#line 56 "gofast.c"
int main(void) 
{ float tmp ;
  float tmp___0 ;
  float tmp___1 ;
  float tmp___2 ;
  float tmp___3 ;
  double tmp___4 ;
  double tmp___5 ;
  double tmp___6 ;
  double tmp___7 ;
  double tmp___8 ;
  double tmp___9 ;
  float tmp___10 ;
  float tmp___11 ;
  double tmp___12 ;
  int tmp___13 ;
  unsigned int tmp___14 ;
  int tmp___15 ;
  unsigned int tmp___16 ;
  int tmp___17 ;
  int tmp___18 ;
  int tmp___19 ;
  int tmp___20 ;
  int tmp___21 ;
  int tmp___22 ;
  int tmp___23 ;
  int tmp___24 ;
  int tmp___25 ;
  int tmp___26 ;
  int tmp___27 ;
  int tmp___28 ;
  int tmp___29 ;
  int tmp___30 ;
  int tmp___31 ;
  int tmp___32 ;

  {
#line 58
  tmp = fp_add((float )1, (float )1);
#line 58
  if (tmp != (float )2) {
#line 58
    fail((char *)"fp_add 1+1");
  }
#line 59
  tmp___0 = fp_sub((float )3, (float )2);
#line 59
  if (tmp___0 != (float )1) {
#line 59
    fail((char *)"fp_sub 3-2");
  }
#line 60
  tmp___1 = fp_mul((float )2, (float )3);
#line 60
  if (tmp___1 != (float )6) {
#line 60
    fail((char *)"fp_mul 2*3");
  }
#line 61
  tmp___2 = fp_div((float )3, (float )2);
#line 61
  if ((double )tmp___2 != 1.5) {
#line 61
    fail((char *)"fp_div 3/2");
  }
#line 62
  tmp___3 = fp_neg((float )1);
#line 62
  if (tmp___3 != (float )-1) {
#line 62
    fail((char *)"fp_neg 1");
  }
#line 64
  tmp___4 = dp_add((double )1, (double )1);
#line 64
  if (tmp___4 != (double )2) {
#line 64
    fail((char *)"dp_add 1+1");
  }
#line 65
  tmp___5 = dp_sub((double )3, (double )2);
#line 65
  if (tmp___5 != (double )1) {
#line 65
    fail((char *)"dp_sub 3-2");
  }
#line 66
  tmp___6 = dp_mul((double )2, (double )3);
#line 66
  if (tmp___6 != (double )6) {
#line 66
    fail((char *)"dp_mul 2*3");
  }
#line 67
  tmp___7 = dp_div((double )3, (double )2);
#line 67
  if (tmp___7 != 1.5) {
#line 67
    fail((char *)"dp_div 3/2");
  }
#line 68
  tmp___8 = dp_neg((double )1);
#line 68
  if (tmp___8 != (double )-1) {
#line 68
    fail((char *)"dp_neg 1");
  }
#line 70
  tmp___9 = fp_to_dp((float )1.5);
#line 70
  if (tmp___9 != 1.5) {
#line 70
    fail((char *)"fp_to_dp 1.5");
  }
#line 71
  tmp___10 = dp_to_fp(1.5);
#line 71
  if ((double )tmp___10 != 1.5) {
#line 71
    fail((char *)"dp_to_fp 1.5");
  }
#line 73
  tmp___11 = floatsisf(1);
#line 73
  if (tmp___11 != (float )1) {
#line 73
    fail((char *)"floatsisf 1");
  }
#line 74
  tmp___12 = floatsidf(1);
#line 74
  if (tmp___12 != (double )1) {
#line 74
    fail((char *)"floatsidf 1");
  }
#line 75
  tmp___13 = fixsfsi((float )1.42);
#line 75
  if (tmp___13 != 1) {
#line 75
    fail((char *)"fixsfsi 1.42");
  }
#line 76
  tmp___14 = fixunssfsi((float )1.42);
#line 76
  if (tmp___14 != 1U) {
#line 76
    fail((char *)"fixunssfsi 1.42");
  }
#line 77
  tmp___15 = fixdfsi(1.42);
#line 77
  if (tmp___15 != 1) {
#line 77
    fail((char *)"fixdfsi 1.42");
  }
#line 78
  tmp___16 = fixunsdfsi(1.42);
#line 78
  if (tmp___16 != 1U) {
#line 78
    fail((char *)"fixunsdfsi 1.42");
  }
#line 80
  tmp___17 = eqsf2((float )1, (float )1);
#line 80
  if (tmp___17 == 0) {
#line 80
    fail((char *)"eqsf2 1==1");
  }
#line 81
  tmp___18 = eqsf2((float )1, (float )2);
#line 81
  if (tmp___18 != 0) {
#line 81
    fail((char *)"eqsf2 1==2");
  }
#line 82
  tmp___19 = nesf2((float )1, (float )2);
#line 82
  if (tmp___19 == 0) {
#line 82
    fail((char *)"nesf2 1!=1");
  }
#line 83
  tmp___20 = nesf2((float )1, (float )1);
#line 83
  if (tmp___20 != 0) {
#line 83
    fail((char *)"nesf2 1!=1");
  }
#line 84
  tmp___21 = gtsf2((float )2, (float )1);
#line 84
  if (tmp___21 == 0) {
#line 84
    fail((char *)"gtsf2 2>1");
  }
#line 85
  tmp___22 = gtsf2((float )1, (float )1);
#line 85
  if (tmp___22 != 0) {
#line 85
    fail((char *)"gtsf2 1>1");
  }
#line 86
  tmp___23 = gtsf2((float )0, (float )1);
#line 86
  if (tmp___23 != 0) {
#line 86
    fail((char *)"gtsf2 0>1");
  }
#line 87
  tmp___24 = gesf2((float )2, (float )1);
#line 87
  if (tmp___24 == 0) {
#line 87
    fail((char *)"gesf2 2>=1");
  }
#line 88
  tmp___25 = gesf2((float )1, (float )1);
#line 88
  if (tmp___25 == 0) {
#line 88
    fail((char *)"gesf2 1>=1");
  }
#line 89
  tmp___26 = gesf2((float )0, (float )1);
#line 89
  if (tmp___26 != 0) {
#line 89
    fail((char *)"gesf2 0>=1");
  }
#line 90
  tmp___27 = ltsf2((float )1, (float )2);
#line 90
  if (tmp___27 == 0) {
#line 90
    fail((char *)"ltsf2 1<2");
  }
#line 91
  tmp___28 = ltsf2((float )1, (float )1);
#line 91
  if (tmp___28 != 0) {
#line 91
    fail((char *)"ltsf2 1<1");
  }
#line 92
  tmp___29 = ltsf2((float )1, (float )0);
#line 92
  if (tmp___29 != 0) {
#line 92
    fail((char *)"ltsf2 1<0");
  }
#line 93
  tmp___30 = lesf2((float )1, (float )2);
#line 93
  if (tmp___30 == 0) {
#line 93
    fail((char *)"lesf2 1<=2");
  }
#line 94
  tmp___31 = lesf2((float )1, (float )1);
#line 94
  if (tmp___31 == 0) {
#line 94
    fail((char *)"lesf2 1<=1");
  }
#line 95
  tmp___32 = lesf2((float )1, (float )0);
#line 95
  if (tmp___32 != 0) {
#line 95
    fail((char *)"lesf2 1<=0");
  }
#line 97
  if (fail_count != 0) {
#line 98
    abort();
  }
#line 99
  exit(0);
}
}
