/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern void abort(void) ;
int ( __attribute__((__noinline__)) foo)(int n ) 
{ 

  {
  if (n < 0) {
    n = ~ n;
  }
  return (n);
}
}
int main(void) 
{ int tmp ;

  {
  tmp = foo(-1);
  if (tmp != 0) {
    abort();
  }
  return (0);
}
}
