/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "index-1.c"
int a[40]  = 
#line 2 "index-1.c"
  {      0,      1,      2,      3, 
        4,      5,      6,      7, 
        8,      9,      10,      11, 
        12,      13,      14,      15, 
        16,      17,      18,      19, 
        20,      21,      22,      23, 
        24,      25,      26,      27, 
        28,      29,      30,      31, 
        32,      33,      34,      35, 
        36,      37,      38,      39};
#line 10 "index-1.c"
int f(long n ) 
{ 

  {
#line 13
  return (a[n - 100000L]);
}
}
#line 16 "index-1.c"
int main(void) 
{ int tmp ;

  {
#line 18
  tmp = f(100030L);
#line 18
  if (tmp != 30) {
#line 19
    abort();
  }
#line 20
  exit(0);
}
}
