/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

int f(int m ) 
{ int i ;
  int s ;

  {
  s = 0;
  i = 0;
  while (i < m) {
    s += i;
    i ++;
  }
  return (s);
}
}
extern int ( /* missing proto */  exit)() ;
int main(void) 
{ 

  {
  exit(0);
}
}
