/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef unsigned long long uint64;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
unsigned long pars  ;
uint64 b[32]  ;
uint64 *r  =    b;
void alpha_ep_extbl_i_eq_0(void) 
{ unsigned int rb ;
  unsigned int ra ;
  unsigned int rc ;
  uint64 temp ;

  {
  rb = (unsigned int )((pars >> 27) & 31UL);
  ra = (unsigned int )((unsigned long )((unsigned int )pars >> 5) & 31UL);
  rc = (unsigned int )((unsigned long )((unsigned int )pars) & 31UL);
  temp = (*(r + ra) >> ((*(r + rb) & 7ULL) << 3)) & 255ULL;
  if (rc != 31U) {
    *(r + rc) = temp;
  }
  return;
}
}
int main(void) 
{ 

  {
  if (sizeof(uint64 ) == 8UL) {
    b[17] = 3160194ULL;
    b[2] = 6003104017374052362ULL;
    pars = 2281701442UL;
    alpha_ep_extbl_i_eq_0();
    if (b[2] != 77ULL) {
      abort();
    }
  }
  exit(0);
}
}
