/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 3 "loop-ivopts-1.c"
void foo(float *x ) ;
#line 5 "loop-ivopts-1.c"
int main(void) 
{ float x[4] ;

  {
#line 8
  foo(x);
#line 9
  return (0);
}
}
#line 16
void foo(float *x ) ;
#line 16 "loop-ivopts-1.c"
static float t16[16]  = 
#line 16
  {      (float )1.,      (float )2.,      (float )3.,      (float )4., 
        (float )5.,      (float )6.,      (float )7.,      (float )8., 
        (float )9.,      (float )10.,      (float )11.,      (float )12., 
        (float )13.,      (float )14.,      (float )15.,      (float )16.};
#line 18
void foo(float *x ) ;
#line 18 "loop-ivopts-1.c"
static float tmp[4]  = {      (float )0.,      (float )0.,      (float )0.,      (float )0.};
#line 12 "loop-ivopts-1.c"
void foo(float *x ) 
{ int i ;
  int j ;
  int k ;
  float temp ;

  {
#line 20
  i = 0;
#line 20
  while (i < 4) {
#line 21
    k = 3 - i;
#line 22
    temp = t16[5 * k];
#line 23
    j = k + 1;
#line 23
    while (j < 4) {
#line 24
      tmp[k] = t16[k + j * 4] * temp;
#line 23
      j ++;
    }
#line 20
    i ++;
  }
#line 27
  *(x + 0) = tmp[0];
#line 28
  *(x + 1) = tmp[1];
#line 29
  *(x + 2) = tmp[2];
#line 30
  *(x + 3) = tmp[3];
#line 31
  return;
}
}
