/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 1 "loop-2.c"
extern void exit(int status ) ;
#line 2
extern void abort(void) ;
#line 3 "loop-2.c"
int a[2]  ;
#line 5 "loop-2.c"
void f(int b ) 
{ unsigned int i ;

  {
#line 8
  i = 0U;
#line 8
  while (i < (unsigned int )b) {
#line 9
    a[i] = (int )(i - 2U);
#line 8
    i ++;
  }
#line 10
  return;
}
}
#line 12 "loop-2.c"
int main(void) 
{ 

  {
#line 14
  a[1] = 0;
#line 14
  a[0] = a[1];
#line 15
  f(2);
#line 16
  if (a[0] != -2) {
#line 17
    abort();
  } else {
#line 16
    if (a[1] != -1) {
#line 17
      abort();
    }
  }
#line 18
  exit(0);
}
}
