/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "loop-7.c"
void foo(unsigned int n ) 
{ int i ;
  int j ;

  {
#line 4
  j = -1;
#line 6
  i = 0;
#line 6
  while (1) {
#line 6
    if (i < 10) {
#line 6
      if (! (j < 0)) {
#line 6
        break;
      }
    } else {
#line 6
      break;
    }
#line 8
    if (1UL << i == (unsigned long )n) {
#line 9
      j = i;
    }
#line 6
    i ++;
  }
#line 12
  if (j < 0) {
#line 13
    abort();
  }
#line 14
  return;
}
}
#line 16 "loop-7.c"
int main(void) 
{ 

  {
#line 18
  foo(64U);
#line 19
  exit(0);
}
}
