/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "loop-14.c"
int a3[3]  ;
#line 4 "loop-14.c"
void f(int *a ) 
{ int i ;

  {
#line 8
  i = 3;
#line 8
  while (1) {
#line 8
    i --;
#line 8
    if (! i) {
#line 8
      break;
    }
#line 9
    *(a + i) = 42 / i;
  }
#line 10
  return;
}
}
#line 12 "loop-14.c"
int main(void) 
{ 

  {
#line 14
  f(a3);
#line 16
  if (a3[1] != 42) {
#line 17
    abort();
  } else {
#line 16
    if (a3[2] != 21) {
#line 17
      abort();
    }
  }
#line 19
  exit(0);
}
}
