/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern void exit(int status ) ;
extern void abort(void) ;
int a[2]  ;
void f(int b ) 
{ unsigned int i ;

  {
  i = 0U;
  while (i < (unsigned int )b) {
    a[i] = (int )(i - 2U);
    i ++;
  }
  return;
}
}
int main(void) 
{ 

  {
  a[1] = 0;
  a[0] = a[1];
  f(2);
  if (a[0] != -2) {
    abort();
  } else {
    if (a[1] != -1) {
      abort();
    }
  }
  exit(0);
}
}
