/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
double a[3]  = {      0.0,      1.0,      2.0};
void bar(int x , double *y ) 
{ 

  {
  if (x) {
    abort();
  } else {
    if (*y != 1.0) {
      abort();
    }
  }
  return;
}
}
int main(void) 
{ double c ;
  int d ;

  {
  d = 0;
  while (d < 3) {
    c = a[d];
    if (c > 0.0) {
      goto e;
    }
    d ++;
  }
  bar(1, & c);
  exit(1);
  e: 
  bar(0, & c);
  exit(0);
}
}
