/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "loop-9.c"
int false(void) 
{ 

  {
#line 6
  return (0);
}
}
#line 11 "loop-9.c"
int main(int argc , char **argv ) 
{ int count ;
  int tmp ;

  {
#line 13
  count = 0;
#line 15
  while (1) {
#line 15
    tmp = false();
#line 15
    if (! tmp) {
#line 15
      if (! (count < -123)) {
#line 15
        break;
      }
    }
#line 16
    count ++;
  }
#line 18
  if (count) {
#line 19
    abort();
  }
#line 21
  return (0);
}
}
