/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef short __attribute__((__may_alias__))  short_a;
extern void abort(void) ;
extern void exit(int  ) ;
int main(void) 
{ int a ;
  short_a *b ;

  {
  a = 305419896;
  b = (short_a *)(& a);
  *(b + 1) = (short __attribute__((__may_alias__))  )0;
  if (a == 305419896) {
    abort();
  }
  exit(0);
}
}
