/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern void link_error(void) ;
static int ok  =    0;
void bar(void) 
{ 

  {
  ok = 1;
  return;
}
}
void foo(int x ) 
{ 

  {
  switch (x) {
  case 0: 
  if (0) {
    link_error();
    case 1: 
    bar();
  }
  }
  return;
}
}
int main(void) 
{ 

  {
  foo(1);
  if (! ok) {
    abort();
  }
  return (0);
}
}
