/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "medce-1.c"
extern void link_error(void) ;
#line 6 "medce-1.c"
static int ok  =    0;
#line 8 "medce-1.c"
void bar(void) 
{ 

  {
#line 10
  ok = 1;
#line 11
  return;
}
}
#line 13 "medce-1.c"
void foo(int x ) 
{ 

  {
#line 15
  switch (x) {
  case 0: 
#line 18
  if (0) {
#line 20
    link_error();
    case 1: 
#line 22
    bar();
  }
  }
#line 25
  return;
}
}
#line 27 "medce-1.c"
int main(void) 
{ 

  {
#line 29
  foo(1);
#line 30
  if (! ok) {
#line 31
    abort();
  }
#line 32
  return (0);
}
}
