/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef signed char int8_t;
typedef short int16_t;
typedef unsigned char uint8_t;
typedef unsigned int uint32_t;
typedef unsigned long uint64_t;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
void f883b(int8_t *result , int16_t * __restrict  arg1 , uint32_t * __restrict  arg2 ,
           uint64_t * __restrict  arg3 , uint8_t * __restrict  arg4 ) 
{ int idx ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;

  {
  idx = 0;
  while (idx < 96) {
    if (-24 >> 1) {
      tmp___2 = 1;
    } else {
      if (*(arg4 + idx)) {
        tmp___2 = 1;
      } else {
        tmp___2 = 0;
      }
    }
    if (tmp___2 < (int )*(arg1 + idx)) {
      if (-24 >> 1) {
        tmp___0 = 1;
      } else {
        if (*(arg4 + idx)) {
          tmp___0 = 1;
        } else {
          tmp___0 = 0;
        }
      }
      tmp___1 = tmp___0;
    } else {
      tmp___1 = (int )*(arg1 + idx);
    }
    *(result + idx) = (signed char )((unsigned long )(((((tmp___1 >> (*(arg2 + idx) & 31U)) ^ 1) - -32) >> 7) | -5) & *(arg3 + idx));
    idx ++;
  }
  return;
}
}
int8_t result[96]  ;
int16_t arg1[96]  ;
uint32_t arg2[96]  ;
uint64_t arg3[96]  ;
uint8_t arg4[96]  ;
int main(void) 
{ int i ;
  int correct[96] ;
  uint32_t tmp ;
  int16_t tmp___0 ;
  uint8_t tmp___1 ;

  {
  correct[0] = 0;
  correct[1] = 1;
  correct[2] = 2;
  correct[3] = 3;
  correct[4] = 0;
  correct[5] = 1;
  correct[6] = 2;
  correct[7] = 3;
  correct[8] = 8;
  correct[9] = 9;
  correct[10] = 10;
  correct[11] = 11;
  correct[12] = 8;
  correct[13] = 9;
  correct[14] = 10;
  correct[15] = 11;
  correct[16] = 16;
  correct[17] = 17;
  correct[18] = 18;
  correct[19] = 19;
  correct[20] = 16;
  correct[21] = 17;
  correct[22] = 18;
  correct[23] = 19;
  correct[24] = 24;
  correct[25] = 25;
  correct[26] = 26;
  correct[27] = 27;
  correct[28] = 24;
  correct[29] = 25;
  correct[30] = 26;
  correct[31] = 27;
  correct[32] = 32;
  correct[33] = 33;
  correct[34] = 34;
  correct[35] = 35;
  correct[36] = 32;
  correct[37] = 33;
  correct[38] = 34;
  correct[39] = 35;
  correct[40] = 40;
  correct[41] = 41;
  correct[42] = 42;
  correct[43] = 43;
  correct[44] = 40;
  correct[45] = 41;
  correct[46] = 42;
  correct[47] = 43;
  correct[48] = 48;
  correct[49] = 49;
  correct[50] = 50;
  correct[51] = 51;
  correct[52] = 48;
  correct[53] = 49;
  correct[54] = 50;
  correct[55] = 51;
  correct[56] = 56;
  correct[57] = 57;
  correct[58] = 58;
  correct[59] = 59;
  correct[60] = 56;
  correct[61] = 57;
  correct[62] = 58;
  correct[63] = 59;
  correct[64] = 64;
  correct[65] = 65;
  correct[66] = 66;
  correct[67] = 67;
  correct[68] = 64;
  correct[69] = 65;
  correct[70] = 66;
  correct[71] = 67;
  correct[72] = 72;
  correct[73] = 73;
  correct[74] = 74;
  correct[75] = 75;
  correct[76] = 72;
  correct[77] = 73;
  correct[78] = 74;
  correct[79] = 75;
  correct[80] = 80;
  correct[81] = 81;
  correct[82] = 82;
  correct[83] = 83;
  correct[84] = 80;
  correct[85] = 81;
  correct[86] = 82;
  correct[87] = 83;
  correct[88] = 88;
  correct[89] = 89;
  correct[90] = 90;
  correct[91] = 91;
  correct[92] = 88;
  correct[93] = 89;
  correct[94] = 90;
  correct[95] = 91;
  i = 0;
  while (i < 96) {
    tmp___1 = (unsigned char )i;
    arg4[i] = tmp___1;
    tmp___0 = (short )tmp___1;
    arg1[i] = tmp___0;
    tmp = (unsigned int )tmp___0;
    arg2[i] = tmp;
    arg3[i] = (unsigned long )tmp;
    i ++;
  }
  f883b(result, (int16_t * __restrict  )(arg1), (uint32_t * __restrict  )(arg2), (uint64_t * __restrict  )(arg3),
        (uint8_t * __restrict  )(arg4));
  i = 0;
  while (i < 96) {
    if ((int )result[i] != correct[i]) {
      abort();
    }
    i ++;
  }
  return (0);
}
}
