/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 7 "multdi-1.c"
long long mpy_res  ;
#line 9 "multdi-1.c"
unsigned long long mpy(long a , long b ) 
{ 

  {
#line 11
  return ((unsigned long long )a * (unsigned long long )b);
}
}
#line 14 "multdi-1.c"
int main(void) 
{ unsigned long long tmp ;

  {
#line 16
  tmp = mpy(1L, -1L);
#line 16
  mpy_res = (long long )tmp;
#line 17
  if (mpy_res != -1LL) {
#line 18
    abort();
  }
#line 19
  return (0);
}
}
