/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern int strcmp(char const   * , char const   * ) ;
char s[2048]  = {      (char )'a',      (char )'\000'};
__inline _Bool foo(char const   *str ) 
{ int tmp ;
  int tmp___0 ;

  {
  tmp = strcmp((char const   *)(s), str);
  if (tmp) {
    tmp___0 = 0;
  } else {
    tmp___0 = 1;
  }
  return ((_Bool )tmp___0);
}
}
int main(void) 
{ int i ;
  _Bool tmp ;

  {
  i = 0;
  while (1) {
    tmp = foo("");
    if (tmp) {
      break;
    }
    i ++;
    s[0] = (char )'\000';
    if (i > 2) {
      abort();
    }
  }
  return (0);
}
}
