/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
void test(int *ptr ) 
{ int i ;

  {
  i = 1;
  goto useless;
  if (0) {
    useless: 
    i = 0;
  } else {
    i = 1;
  }
  *ptr = i;
}
}
int main(void) 
{ int i ;

  {
  i = 1;
  test(& i);
  if (i) {
    abort();
  }
  return (0);
}
}
