/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 4 "pr19689.c"
struct __anonstruct_f_3 {
   int b : 29 ;
};
#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "pr19689.c"
struct __anonstruct_f_3 f  ;
#line 9 "pr19689.c"
void foo(short j ) 
{ 

  {
#line 11
  f.b = (int )j;
#line 12
  return;
}
}
#line 14 "pr19689.c"
int main(void) 
{ 

  {
#line 16
  foo((short)-55);
#line 17
  if (f.b != -55) {
#line 18
    abort();
  }
#line 19
  return (0);
}
}
