/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct __anonstruct_f_21 {
   int b : 29 ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
struct __anonstruct_f_21 f  ;
void foo(short j ) 
{ 

  {
  f.b = (int )j;
  return;
}
}
int main(void) 
{ 

  {
  foo((short)-55);
  if (f.b != -55) {
    abort();
  }
  return (0);
}
}
