/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "pr21964-1.c"
void foo(int n , int m ) 
{ int tmp ;

  {
#line 5
  if (m == 0) {
#line 6
    exit(0);
  } else {
#line 7
    if (n != 0) {
#line 8
      abort();
    } else {
#line 10
      tmp = n;
#line 10
      n ++;
#line 10
      foo(tmp, m - 1);
    }
  }
#line 11
  return;
}
}
#line 13 "pr21964-1.c"
int main(void) 
{ 

  {
#line 15
  foo(0, 4);
#line 16
  return (0);
}
}
