/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "pr22630.c"
int j  ;
#line 6 "pr22630.c"
void bla(int *r ) 
{ int *p ;
  int *q ;

  {
#line 10
  q = r;
#line 10
  p = q;
#line 11
  if (! p) {
#line 12
    p = & j;
  }
#line 14
  if ((unsigned long )p != (unsigned long )q) {
#line 15
    j = 1;
  }
#line 16
  return;
}
}
#line 18 "pr22630.c"
int main(void) 
{ 

  {
#line 20
  bla((int *)0);
#line 21
  if (! j) {
#line 22
    abort();
  }
#line 23
  return (0);
}
}
