/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "pr24142.c"
int f(int a , int b ) 
{ 

  {
#line 6
  if (a == 1) {
#line 7
    a = 0;
  }
#line 8
  if (b == 0) {
#line 9
    a = 1;
  }
#line 10
  if (a != 0) {
#line 11
    return (0);
  }
#line 12
  return (1);
}
}
#line 15 "pr24142.c"
int main(void) 
{ int tmp ;

  {
#line 17
  tmp = f(1, 1);
#line 17
  if (tmp != 1) {
#line 18
    abort();
  }
#line 19
  return (0);
}
}
