/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 5 "pr27671-1.c"
extern  __attribute__((__noreturn__)) void abort(void) ;
#line 6
extern  __attribute__((__noreturn__)) void exit(int  ) ;
#line 8 "pr27671-1.c"
static int ( __attribute__((__noinline__)) foo)(int a , int b ) 
{ int c ;

  {
#line 11
  c = a ^ b;
#line 12
  if (c == a) {
#line 13
    abort();
  }
#line 14
  return (0);
}
}
#line 17 "pr27671-1.c"
int main(void) 
{ 

  {
#line 19
  foo(0, 1);
#line 20
  exit(0);
}
}
