/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct S {
   unsigned char a ;
   unsigned char b ;
   unsigned char c ;
   unsigned char d[16] ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
void ( __attribute__((__noinline__)) foo)(struct S *x , struct S *y ) 
{ int a ;
  int b ;
  unsigned char c ;
  unsigned char *d ;
  unsigned char *e ;

  {
  b = (int )x->b;
  d = x->d;
  e = y->d;
  a = 0;
  while (b) {
    if (b >= 8) {
      c = (unsigned char)255;
      b -= 8;
    } else {
      c = (unsigned char )(255 << (8 - b));
      b = 0;
    }
    *(e + a) = (unsigned char )((int )*(d + a) & (int )c);
    a ++;
  }
  return;
}
}
int main(void) 
{ struct S x ;
  struct S y ;

  {
  x.a = (unsigned char)0;
  x.b = (unsigned char)25;
  x.c = (unsigned char)0;
  x.d[0] = (unsigned char)170;
  x.d[1] = (unsigned char)187;
  x.d[2] = (unsigned char)204;
  x.d[3] = (unsigned char)221;
  x.d[4] = (unsigned char)0;
  x.d[5] = (unsigned char)0;
  x.d[6] = (unsigned char)0;
  x.d[7] = (unsigned char)0;
  x.d[8] = (unsigned char)0;
  x.d[9] = (unsigned char)0;
  x.d[10] = (unsigned char)0;
  x.d[11] = (unsigned char)0;
  x.d[12] = (unsigned char)0;
  x.d[13] = (unsigned char)0;
  x.d[14] = (unsigned char)0;
  x.d[15] = (unsigned char)0;
  y.a = (unsigned char)0;
  y.b = (unsigned char)0;
  y.c = (unsigned char)0;
  y.d[0] = (unsigned char)0;
  y.d[1] = (unsigned char)0;
  y.d[2] = (unsigned char)0;
  y.d[3] = (unsigned char)0;
  y.d[4] = (unsigned char)0;
  y.d[5] = (unsigned char)0;
  y.d[6] = (unsigned char)0;
  y.d[7] = (unsigned char)0;
  y.d[8] = (unsigned char)0;
  y.d[9] = (unsigned char)0;
  y.d[10] = (unsigned char)0;
  y.d[11] = (unsigned char)0;
  y.d[12] = (unsigned char)0;
  y.d[13] = (unsigned char)0;
  y.d[14] = (unsigned char)0;
  y.d[15] = (unsigned char)0;
  foo(& x, & y);
  if ((int )x.d[0] != (int )y.d[0]) {
    abort();
  } else {
    if ((int )x.d[1] != (int )y.d[1]) {
      abort();
    } else {
      if ((int )x.d[2] != (int )y.d[2]) {
        abort();
      } else {
        if (((int )x.d[3] & 128) != (int )y.d[3]) {
          abort();
        }
      }
    }
  }
  return (0);
}
}
