/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "pr27364.c"
int f(unsigned int number_of_digits_to_use ) 
{ 

  {
#line 4
  if (number_of_digits_to_use > 1294U) {
#line 5
    return (0);
  }
#line 6
  return ((int )(((number_of_digits_to_use * 3321928U) / 1000000U + 1U) / 16U));
}
}
#line 9 "pr27364.c"
int main(void) 
{ int tmp ;

  {
#line 11
  tmp = f(11U);
#line 11
  if (tmp != 2) {
#line 12
    abort();
  }
#line 13
  exit(0);
}
}
