/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 5 "pr28651.c"
int ( __attribute__((__noinline__)) foo)(unsigned int u ) 
{ 

  {
#line 8
  return ((int )(u + 4U) < (int )u);
}
}
#line 11 "pr28651.c"
int main(int argc , char **argv ) 
{ unsigned int u ;
  int tmp ;

  {
#line 13
  u = 2147483647U;
#line 15
  tmp = foo(u);
#line 15
  if (tmp == 0) {
#line 16
    abort();
  }
#line 17
  return (0);
}
}
