/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int ( __attribute__((__noinline__)) foo)(unsigned int u ) 
{ 

  {
  return ((int )(u + 4U) < (int )u);
}
}
int main(int argc , char **argv ) 
{ unsigned int u ;
  int tmp ;

  {
  u = 2147483647U;
  tmp = foo(u);
  if (tmp == 0) {
    abort();
  }
  return (0);
}
}
