/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

float *ptrs[20]  ;
float results[20]  ;
int incs[20]  ;
void ( __attribute__((__noinline__)) foo)(int n ) 
{ int inc0 ;
  int inc1 ;
  int inc2 ;
  int inc3 ;
  int inc4 ;
  int inc5 ;
  int inc6 ;
  int inc7 ;
  int inc8 ;
  int inc9 ;
  int inc10 ;
  int inc11 ;
  int inc12 ;
  int inc13 ;
  int inc14 ;
  int inc15 ;
  int inc16 ;
  int inc17 ;
  int inc18 ;
  int inc19 ;
  float *ptr0 ;
  float result0 ;
  float *ptr1 ;
  float result1 ;
  float *ptr2 ;
  float result2 ;
  float *ptr3 ;
  float result3 ;
  float *ptr4 ;
  float result4 ;
  float *ptr5 ;
  float result5 ;
  float *ptr6 ;
  float result6 ;
  float *ptr7 ;
  float result7 ;
  float *ptr8 ;
  float result8 ;
  float *ptr9 ;
  float result9 ;
  float *ptr10 ;
  float result10 ;
  float *ptr11 ;
  float result11 ;
  float *ptr12 ;
  float result12 ;
  float *ptr13 ;
  float result13 ;
  float *ptr14 ;
  float result14 ;
  float *ptr15 ;
  float result15 ;
  float *ptr16 ;
  float result16 ;
  float *ptr17 ;
  float result17 ;
  float *ptr18 ;
  float result18 ;
  float *ptr19 ;
  float result19 ;
  int tmp ;

  {
  inc0 = incs[0];
  inc1 = incs[1];
  inc2 = incs[2];
  inc3 = incs[3];
  inc4 = incs[4];
  inc5 = incs[5];
  inc6 = incs[6];
  inc7 = incs[7];
  inc8 = incs[8];
  inc9 = incs[9];
  inc10 = incs[10];
  inc11 = incs[11];
  inc12 = incs[12];
  inc13 = incs[13];
  inc14 = incs[14];
  inc15 = incs[15];
  inc16 = incs[16];
  inc17 = incs[17];
  inc18 = incs[18];
  inc19 = incs[19];
  ptr0 = ptrs[0];
  result0 = (float )0;
  ptr1 = ptrs[1];
  result1 = (float )0;
  ptr2 = ptrs[2];
  result2 = (float )0;
  ptr3 = ptrs[3];
  result3 = (float )0;
  ptr4 = ptrs[4];
  result4 = (float )0;
  ptr5 = ptrs[5];
  result5 = (float )0;
  ptr6 = ptrs[6];
  result6 = (float )0;
  ptr7 = ptrs[7];
  result7 = (float )0;
  ptr8 = ptrs[8];
  result8 = (float )0;
  ptr9 = ptrs[9];
  result9 = (float )0;
  ptr10 = ptrs[10];
  result10 = (float )0;
  ptr11 = ptrs[11];
  result11 = (float )0;
  ptr12 = ptrs[12];
  result12 = (float )0;
  ptr13 = ptrs[13];
  result13 = (float )0;
  ptr14 = ptrs[14];
  result14 = (float )0;
  ptr15 = ptrs[15];
  result15 = (float )0;
  ptr16 = ptrs[16];
  result16 = (float )0;
  ptr17 = ptrs[17];
  result17 = (float )0;
  ptr18 = ptrs[18];
  result18 = (float )0;
  ptr19 = ptrs[19];
  result19 = (float )0;
  while (1) {
    tmp = n;
    n --;
    if (! tmp) {
      break;
    }
    result0 += *ptr0;
    ptr0 += inc0;
    result1 += *ptr1;
    ptr1 += inc1;
    result2 += *ptr2;
    ptr2 += inc2;
    result3 += *ptr3;
    ptr3 += inc3;
    result4 += *ptr4;
    ptr4 += inc4;
    result5 += *ptr5;
    ptr5 += inc5;
    result6 += *ptr6;
    ptr6 += inc6;
    result7 += *ptr7;
    ptr7 += inc7;
    result8 += *ptr8;
    ptr8 += inc8;
    result9 += *ptr9;
    ptr9 += inc9;
    result10 += *ptr10;
    ptr10 += inc10;
    result11 += *ptr11;
    ptr11 += inc11;
    result12 += *ptr12;
    ptr12 += inc12;
    result13 += *ptr13;
    ptr13 += inc13;
    result14 += *ptr14;
    ptr14 += inc14;
    result15 += *ptr15;
    ptr15 += inc15;
    result16 += *ptr16;
    ptr16 += inc16;
    result17 += *ptr17;
    ptr17 += inc17;
    result18 += *ptr18;
    ptr18 += inc18;
    result19 += *ptr19;
    ptr19 += inc19;
  }
  results[0] = result0;
  results[1] = result1;
  results[2] = result2;
  results[3] = result3;
  results[4] = result4;
  results[5] = result5;
  results[6] = result6;
  results[7] = result7;
  results[8] = result8;
  results[9] = result9;
  results[10] = result10;
  results[11] = result11;
  results[12] = result12;
  results[13] = result13;
  results[14] = result14;
  results[15] = result15;
  results[16] = result16;
  results[17] = result17;
  results[18] = result18;
  results[19] = result19;
  return;
}
}
float input[80]  ;
int main(void) 
{ int i ;

  {
  i = 0;
  while (i < 20) {
    ptrs[i] = input + i;
    incs[i] = i;
    i ++;
  }
  i = 0;
  while (i < 80) {
    input[i] = (float )i;
    i ++;
  }
  foo(4);
  i = 0;
  while (i < 20) {
    if (results[i] != (float )(((i * 4) * 5) / 2)) {
      return (1);
    }
    i ++;
  }
  return (0);
}
}
