/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "pr29797-1.c"
unsigned int bar(void) 
{ 

  {
#line 4
  return (32768U);
}
}
#line 6 "pr29797-1.c"
int main(void) 
{ unsigned int nStyle ;
  unsigned int tmp ;

  {
#line 8
  tmp = bar();
#line 8
  nStyle = tmp;
#line 9
  if (nStyle & 32768U) {
#line 10
    nStyle |= 65536U;
  }
#line 11
  if (nStyle != 98304U) {
#line 12
    abort();
  }
#line 13
  return (0);
}
}
