/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
unsigned int bar(void) 
{ 

  {
  return (32768U);
}
}
int main(void) 
{ unsigned int nStyle ;
  unsigned int tmp ;

  {
  tmp = bar();
  nStyle = tmp;
  if (nStyle & 32768U) {
    nStyle |= 65536U;
  }
  if (nStyle != 98304U) {
    abort();
  }
  return (0);
}
}
