/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct s {
   char c ;
   unsigned long long x ;
} __attribute__((__packed__)) ;
void ( __attribute__((__noinline__)) foo)(struct s *s ) 
{ 

  {
  s->x = 0ULL;
  return;
}
}
int main(void) 
{ struct s s ;

  {
  s.c = (char)1;
  s.x = ~ 0ULL;
  foo(& s);
  return (s.x != 0ULL);
}
}
