/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 6 "pr29695-2.c"
int a  =    128;
#line 7 "pr29695-2.c"
unsigned char b  =    (unsigned char)128;
#line 8 "pr29695-2.c"
long long c  =    2147483648LL;
#line 9 "pr29695-2.c"
unsigned int d  =    2147483648U;
#line 11 "pr29695-2.c"
int f1(void) 
{ int tmp ;

  {
#line 14
  if (a & 128) {
#line 14
    tmp = 128;
  } else {
#line 14
    tmp = 0;
  }
#line 14
  return (tmp);
}
}
#line 17 "pr29695-2.c"
int f2(void) 
{ int tmp ;

  {
#line 20
  if ((int )b & 128) {
#line 20
    tmp = 128;
  } else {
#line 20
    tmp = 0;
  }
#line 20
  return (tmp);
}
}
#line 23 "pr29695-2.c"
int f3(void) 
{ int tmp ;

  {
#line 26
  if ((int )b & 128) {
#line 26
    tmp = 896;
  } else {
#line 26
    tmp = 0;
  }
#line 26
  return (tmp);
}
}
#line 29 "pr29695-2.c"
int f4(void) 
{ int tmp ;

  {
#line 32
  if ((int )b & 128) {
#line 32
    tmp = -128;
  } else {
#line 32
    tmp = 0;
  }
#line 32
  return (tmp);
}
}
#line 35 "pr29695-2.c"
long long f5(void) 
{ long long tmp ;

  {
#line 38
  if (c & 2147483648LL) {
#line 38
    tmp = 2147483648LL;
  } else {
#line 38
    tmp = 0LL;
  }
#line 38
  return (tmp);
}
}
#line 41 "pr29695-2.c"
long long f6(void) 
{ long long tmp ;

  {
#line 44
  if (d & 2147483648U) {
#line 44
    tmp = 2147483648LL;
  } else {
#line 44
    tmp = 0LL;
  }
#line 44
  return (tmp);
}
}
#line 47 "pr29695-2.c"
long long f7(void) 
{ long long tmp ;

  {
#line 50
  if (d & 2147483648U) {
#line 50
    tmp = 15032385536LL;
  } else {
#line 50
    tmp = 0LL;
  }
#line 50
  return (tmp);
}
}
#line 53 "pr29695-2.c"
long long f8(void) 
{ long long tmp ;

  {
#line 56
  if (d & 2147483648U) {
#line 56
    tmp = (-0x7FFFFFFF-1);
  } else {
#line 56
    tmp = 0LL;
  }
#line 56
  return (tmp);
}
}
#line 59 "pr29695-2.c"
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  long long tmp___3 ;
  long long tmp___4 ;
  long long tmp___5 ;
  long long tmp___6 ;

  {
#line 63
  tmp = f1();
#line 63
  if (tmp != 128) {
#line 64
    abort();
  }
#line 65
  tmp___0 = f2();
#line 65
  if (tmp___0 != 128) {
#line 66
    abort();
  }
#line 67
  tmp___1 = f3();
#line 67
  if (tmp___1 != 896) {
#line 68
    abort();
  }
#line 69
  tmp___2 = f4();
#line 69
  if (tmp___2 != -128) {
#line 70
    abort();
  }
#line 71
  tmp___3 = f5();
#line 71
  if (tmp___3 != 2147483648LL) {
#line 72
    abort();
  }
#line 73
  tmp___4 = f6();
#line 73
  if (tmp___4 != 2147483648LL) {
#line 74
    abort();
  }
#line 75
  tmp___5 = f7();
#line 75
  if (tmp___5 != 15032385536LL) {
#line 76
    abort();
  }
#line 77
  tmp___6 = f8();
#line 77
  if (tmp___6 != (-0x7FFFFFFF-1)) {
#line 78
    abort();
  }
#line 79
  return (0);
}
}
