/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 6 "pr29695-1.c"
int f1(void) 
{ int a ;
  int tmp ;

  {
#line 9
  a = 128;
#line 10
  if (a & 128) {
#line 10
    tmp = 128;
  } else {
#line 10
    tmp = 0;
  }
#line 10
  return (tmp);
}
}
#line 13 "pr29695-1.c"
int f2(void) 
{ unsigned char a ;
  int tmp ;

  {
#line 16
  a = (unsigned char)128;
#line 17
  if ((int )a & 128) {
#line 17
    tmp = 128;
  } else {
#line 17
    tmp = 0;
  }
#line 17
  return (tmp);
}
}
#line 20 "pr29695-1.c"
int f3(void) 
{ unsigned char a ;
  int tmp ;

  {
#line 23
  a = (unsigned char)128;
#line 24
  if ((int )a & 128) {
#line 24
    tmp = 896;
  } else {
#line 24
    tmp = 0;
  }
#line 24
  return (tmp);
}
}
#line 27 "pr29695-1.c"
int f4(void) 
{ unsigned char a ;
  int tmp ;

  {
#line 30
  a = (unsigned char)128;
#line 31
  if ((int )a & 128) {
#line 31
    tmp = -128;
  } else {
#line 31
    tmp = 0;
  }
#line 31
  return (tmp);
}
}
#line 34 "pr29695-1.c"
long long f5(void) 
{ long long a ;
  long long tmp ;

  {
#line 37
  a = 2147483648LL;
#line 38
  if (a & 2147483648LL) {
#line 38
    tmp = 2147483648LL;
  } else {
#line 38
    tmp = 0LL;
  }
#line 38
  return (tmp);
}
}
#line 41 "pr29695-1.c"
long long f6(void) 
{ unsigned int a ;
  long long tmp ;

  {
#line 44
  a = 2147483648U;
#line 45
  if (a & 2147483648U) {
#line 45
    tmp = 2147483648LL;
  } else {
#line 45
    tmp = 0LL;
  }
#line 45
  return (tmp);
}
}
#line 48 "pr29695-1.c"
long long f7(void) 
{ unsigned int a ;
  long long tmp ;

  {
#line 51
  a = 2147483648U;
#line 52
  if (a & 2147483648U) {
#line 52
    tmp = 15032385536LL;
  } else {
#line 52
    tmp = 0LL;
  }
#line 52
  return (tmp);
}
}
#line 55 "pr29695-1.c"
long long f8(void) 
{ unsigned int a ;
  long long tmp ;

  {
#line 58
  a = 2147483648U;
#line 59
  if (a & 2147483648U) {
#line 59
    tmp = (-0x7FFFFFFF-1);
  } else {
#line 59
    tmp = 0LL;
  }
#line 59
  return (tmp);
}
}
#line 62 "pr29695-1.c"
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  long long tmp___3 ;
  long long tmp___4 ;
  long long tmp___5 ;
  long long tmp___6 ;

  {
#line 66
  tmp = f1();
#line 66
  if (tmp != 128) {
#line 67
    abort();
  }
#line 68
  tmp___0 = f2();
#line 68
  if (tmp___0 != 128) {
#line 69
    abort();
  }
#line 70
  tmp___1 = f3();
#line 70
  if (tmp___1 != 896) {
#line 71
    abort();
  }
#line 72
  tmp___2 = f4();
#line 72
  if (tmp___2 != -128) {
#line 73
    abort();
  }
#line 74
  tmp___3 = f5();
#line 74
  if (tmp___3 != 2147483648LL) {
#line 75
    abort();
  }
#line 76
  tmp___4 = f6();
#line 76
  if (tmp___4 != 2147483648LL) {
#line 77
    abort();
  }
#line 78
  tmp___5 = f7();
#line 78
  if (tmp___5 != 15032385536LL) {
#line 79
    abort();
  }
#line 80
  tmp___6 = f8();
#line 80
  if (tmp___6 != (-0x7FFFFFFF-1)) {
#line 81
    abort();
  }
#line 82
  return (0);
}
}
