/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int a  =    128;
unsigned char b  =    (unsigned char)128;
long long c  =    2147483648LL;
unsigned int d  =    2147483648U;
int f1(void) 
{ int tmp ;

  {
  if (a & 128) {
    tmp = 128;
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int f2(void) 
{ int tmp ;

  {
  if ((int )b & 128) {
    tmp = 128;
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int f3(void) 
{ int tmp ;

  {
  if ((int )b & 128) {
    tmp = 896;
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
int f4(void) 
{ int tmp ;

  {
  if ((int )b & 128) {
    tmp = -128;
  } else {
    tmp = 0;
  }
  return (tmp);
}
}
long long f5(void) 
{ long long tmp ;

  {
  if (c & 2147483648LL) {
    tmp = 2147483648LL;
  } else {
    tmp = 0LL;
  }
  return (tmp);
}
}
long long f6(void) 
{ long long tmp ;

  {
  if (d & 2147483648U) {
    tmp = 2147483648LL;
  } else {
    tmp = 0LL;
  }
  return (tmp);
}
}
long long f7(void) 
{ long long tmp ;

  {
  if (d & 2147483648U) {
    tmp = 15032385536LL;
  } else {
    tmp = 0LL;
  }
  return (tmp);
}
}
long long f8(void) 
{ long long tmp ;

  {
  if (d & 2147483648U) {
    tmp = (-0x7FFFFFFF-1);
  } else {
    tmp = 0LL;
  }
  return (tmp);
}
}
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  long long tmp___3 ;
  long long tmp___4 ;
  long long tmp___5 ;
  long long tmp___6 ;

  {
  tmp = f1();
  if (tmp != 128) {
    abort();
  }
  tmp___0 = f2();
  if (tmp___0 != 128) {
    abort();
  }
  tmp___1 = f3();
  if (tmp___1 != 896) {
    abort();
  }
  tmp___2 = f4();
  if (tmp___2 != -128) {
    abort();
  }
  tmp___3 = f5();
  if (tmp___3 != 2147483648LL) {
    abort();
  }
  tmp___4 = f6();
  if (tmp___4 != 2147483648LL) {
    abort();
  }
  tmp___5 = f7();
  if (tmp___5 != 15032385536LL) {
    abort();
  }
  tmp___6 = f8();
  if (tmp___6 != (-0x7FFFFFFF-1)) {
    abort();
  }
  return (0);
}
}
