/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int volatile   ReadyFlag_NotProperlyInitialized ;
int volatile   ReadyFlag_NotProperlyInitialized  =    (int volatile   )1;
int main(void) 
{ 

  {
  if (ReadyFlag_NotProperlyInitialized != (int volatile   )1) {
    abort();
  }
  return (0);
}
}
