/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 4 "pr31136.c"
struct S {
   unsigned int b4 : 4 ;
   unsigned int b6 : 6 ;
};
#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "pr31136.c"
struct S s  ;
#line 9 "pr31136.c"
int main(void) 
{ 

  {
#line 11
  s.b6 = 31U;
#line 12
  s.b4 = s.b6;
#line 13
  s.b6 = s.b4;
#line 14
  if (s.b6 != 15U) {
#line 15
    abort();
  }
#line 16
  return (0);
}
}
