/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__)) int abs(int j )  __attribute__((__leaf__, __const__)) ;
int ( __attribute__((__noinline__)) lisp_atan2)(long dy , long dx ) 
{ int tmp ;
  int tmp___0 ;

  {
  if (dx <= 0L) {
    if (dy > 0L) {
      tmp = abs((int )dx);
      tmp___0 = abs((int )dy);
      return (tmp <= tmp___0);
    }
  }
  return (0);
}
}
int main(void) 
{ long volatile   dy ;
  long volatile   dx ;
  int tmp ;

  {
  dy = (long volatile   )63;
  dx = (long volatile   )-77;
  tmp = lisp_atan2((long )dy, (long )dx);
  if (tmp) {
    abort();
  }
  return (0);
}
}
