/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int f(unsigned int x , int n ) 
{ 

  {
  return ((int )x / (1 << n));
}
}
int main(void) 
{ int tmp ;

  {
  tmp = f(4294967295U, 1);
  if (tmp != 0) {
    abort();
  }
  return (0);
}
}
