/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
static void something(int i ) ;
int main(void) 
{ 

  {
  something(-1);
  return (0);
}
}
static void something(int i ) 
{ 

  {
  if (i != -1) {
    abort();
  }
  return;
}
}
