/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int x  ;
void ( __attribute__((__noinline__)) foo)(void) 
{ 

  {
  x = - x;
  return;
}
}
void ( __attribute__((__noinline__)) bar)(void)  __attribute__((__const__)) ;
void ( __attribute__((__noinline__)) bar)(void) 
{ 

  {
  return;
}
}
int ( __attribute__((__noinline__)) test)(int c ) 
{ int tmp ;
  void ( __attribute__((__noinline__)) (*tmp___0))(void) ;

  {
  tmp = x;
  if (c) {
    tmp___0 = & foo;
  } else {
    tmp___0 = & bar;
  }
  (*tmp___0)();
  return (tmp + x);
}
}
int main(void) 
{ int tmp ;

  {
  x = 1;
  tmp = test(1);
  if (tmp != 0) {
    abort();
  }
  return (0);
}
}
