/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int f(unsigned int x ) 
{ 

  {
  return ((int )x % 4);
}
}
int main(void) 
{ int tmp ;

  {
  tmp = f(4294967295U);
  if (tmp != -1) {
    abort();
  }
  return (0);
}
}
