/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

char const   *( __attribute__((__noinline__)) foo)(char const   *p ) 
{ char const   *end ;
  int len ;
  int c ;

  {
  len = 1;
  while (1) {
    c = (int )*p;
    if (c >= 97) {
      if (c <= 122) {
        c = (c - 97) + 65;
      } else {
        c = c;
      }
    } else {
      c = c;
    }
    if (c == 66) {
      end = p;
    } else {
      if (c == 65) {
        end = p;
        while (1) {
          p ++;
          if (! ((int const   )*p == 43)) {
            break;
          }
        }
      } else {
        break;
      }
    }
    p ++;
    len ++;
  }
  if (len > 2) {
    if ((int const   )*p == 58) {
      p = end;
    }
  }
  return (p);
}
}
int main(void) 
{ char const   *input ;
  char const   *tmp ;

  {
  input = "Bbb:";
  tmp = foo(input);
  return ((unsigned long )tmp != (unsigned long )(input + 2));
}
}
