/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int ( __attribute__((__noinline__)) foo)(int bits_per_pixel , int depth ) 
{ 

  {
  if ((bits_per_pixel | depth) == 1) {
    abort();
  }
  return (bits_per_pixel);
}
}
int main(void) 
{ int tmp ;

  {
  tmp = foo(2, 0);
  if (tmp != 2) {
    abort();
  }
  return (0);
}
}
