/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "pr35163.c"
int main(void) 
{ signed char a ;
  signed char b ;

  {
#line 6
  a = (signed char)-30;
#line 7
  b = (signed char)-31;
#line 9
  if ((int )a > (int )((unsigned short )b)) {
#line 13
    abort();
  }
#line 14
  return (0);
}
}
