/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "pr36077.c"
unsigned int test(unsigned int x ) 
{ 

  {
#line 6
  return ((x / 2147483649U) / 2U);
}
}
#line 9 "pr36077.c"
int main(void) 
{ unsigned int tmp ;

  {
#line 11
  tmp = test(2U);
#line 11
  if (tmp != 0U) {
#line 12
    abort();
  }
#line 13
  return (0);
}
}
