/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 6 "pr37924.c"
signed char a  ;
#line 7 "pr37924.c"
unsigned char b  ;
#line 9 "pr37924.c"
int test1(void) 
{ int c ;

  {
#line 12
  c = -1;
#line 13
  return ((int )((unsigned int )((int )a ^ c) >> 9));
}
}
#line 16 "pr37924.c"
int test2(void) 
{ int c ;

  {
#line 19
  c = -1;
#line 20
  return ((int )((unsigned int )((int )b ^ c) >> 9));
}
}
#line 23 "pr37924.c"
int main(void) 
{ int tmp ;
  int tmp___0 ;
  unsigned int tmp___2 ;
  int tmp___3 ;
  unsigned int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;

  {
#line 25
  a = (signed char)0;
#line 26
  tmp = test1();
#line 26
  if ((unsigned int )tmp != 4294967295U >> 9) {
#line 27
    abort();
  }
#line 28
  a = (signed char)64;
#line 29
  tmp___0 = test1();
#line 29
  if ((unsigned int )tmp___0 != 4294967295U >> 9) {
#line 30
    abort();
  }
#line 31
  a = (signed char)-128;
#line 32
  tmp___3 = test1();
#line 32
  if (tmp___3 != ((int )a < 0)) {
#line 32
    tmp___2 = 0U;
  } else {
#line 32
    tmp___2 = 4294967295U >> 9;
  }
#line 32
  if (tmp___2) {
#line 33
    abort();
  }
#line 34
  a = (signed char)-1;
#line 35
  tmp___6 = test1();
#line 35
  if (tmp___6 != ((int )a < 0)) {
#line 35
    tmp___5 = 0U;
  } else {
#line 35
    tmp___5 = 4294967295U >> 9;
  }
#line 35
  if (tmp___5) {
#line 36
    abort();
  }
#line 37
  b = (unsigned char)0;
#line 38
  tmp___7 = test2();
#line 38
  if ((unsigned int )tmp___7 != 4294967295U >> 9) {
#line 39
    abort();
  }
#line 40
  b = (unsigned char)64;
#line 41
  tmp___8 = test2();
#line 41
  if ((unsigned int )tmp___8 != 4294967295U >> 9) {
#line 42
    abort();
  }
#line 43
  b = (unsigned char)128;
#line 44
  tmp___9 = test2();
#line 44
  if ((unsigned int )tmp___9 != 4294967295U >> 9) {
#line 45
    abort();
  }
#line 46
  b = (unsigned char)255;
#line 47
  tmp___10 = test2();
#line 47
  if ((unsigned int )tmp___10 != 4294967295U >> 9) {
#line 48
    abort();
  }
#line 49
  return (0);
}
}
