/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 4 "pr38048-2.c"
static int inv_J(int (*a)[2] ) 
{ int j ;
  int det ;

  {
#line 7
  det = (int )0.0;
#line 8
  j = 0;
#line 8
  while (j < 2) {
#line 9
    det += (*(a + j))[0] + (*(a + j))[1];
#line 8
    j ++;
  }
#line 10
  return (det);
}
}
#line 13 "pr38048-2.c"
int foo(void) 
{ int mat[2][2] ;
  int tmp ;

  {
#line 16
  mat[0][0] = 1;
#line 17
  mat[0][1] = 2;
#line 18
  mat[1][0] = 4;
#line 19
  mat[1][1] = 8;
#line 20
  tmp = inv_J(mat);
#line 20
  return (tmp);
}
}
#line 23 "pr38048-2.c"
int main(void) 
{ int tmp ;

  {
#line 25
  tmp = foo();
#line 25
  if (tmp != 15) {
#line 26
    abort();
  }
#line 27
  return (0);
}
}
