/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
static int ( __attribute__((__noinline__)) foo1)(int x ) 
{ 

  {
  return (x);
}
}
unsigned int ( __attribute__((__noinline__)) bar1)(int x ) 
{ int tmp ;

  {
  tmp = foo1(x + 6);
  return ((unsigned int )tmp);
}
}
unsigned long volatile   l1  =    (unsigned long volatile   )4294967292U;
static short ( __attribute__((__noinline__)) foo2)(int x ) 
{ 

  {
  return ((short )x);
}
}
unsigned short ( __attribute__((__noinline__)) bar2)(int x ) 
{ short tmp ;

  {
  tmp = foo2(x + 6);
  return ((unsigned short )tmp);
}
}
unsigned long volatile   l2  =    (unsigned long volatile   )(unsigned short)65532;
static signed char ( __attribute__((__noinline__)) foo3)(int x ) 
{ 

  {
  return ((signed char )x);
}
}
unsigned char ( __attribute__((__noinline__)) bar3)(int x ) 
{ signed char tmp ;

  {
  tmp = foo3(x + 6);
  return ((unsigned char )tmp);
}
}
unsigned long volatile   l3  =    (unsigned long volatile   )(unsigned char)252;
static unsigned int ( __attribute__((__noinline__)) foo4)(int x ) 
{ 

  {
  return ((unsigned int )x);
}
}
int ( __attribute__((__noinline__)) bar4)(int x ) 
{ unsigned int tmp ;

  {
  tmp = foo4(x + 6);
  return ((int )tmp);
}
}
unsigned long volatile   l4  =    (unsigned long volatile   )-4;
static unsigned short ( __attribute__((__noinline__)) foo5)(int x ) 
{ 

  {
  return ((unsigned short )x);
}
}
short ( __attribute__((__noinline__)) bar5)(int x ) 
{ unsigned short tmp ;

  {
  tmp = foo5(x + 6);
  return ((short )tmp);
}
}
unsigned long volatile   l5  =    (unsigned long volatile   )(short)-4;
static unsigned char ( __attribute__((__noinline__)) foo6)(int x ) 
{ 

  {
  return ((unsigned char )x);
}
}
signed char ( __attribute__((__noinline__)) bar6)(int x ) 
{ unsigned char tmp ;

  {
  tmp = foo6(x + 6);
  return ((signed char )tmp);
}
}
unsigned long volatile   l6  =    (unsigned long volatile   )(signed char)-4;
int main(void) 
{ unsigned int tmp ;
  unsigned short tmp___0 ;
  unsigned char tmp___1 ;
  int tmp___2 ;
  short tmp___3 ;
  signed char tmp___4 ;

  {
  tmp = bar1(-10);
  if ((unsigned long volatile   )tmp != l1) {
    abort();
  }
  tmp___0 = bar2(-10);
  if ((unsigned long volatile   )tmp___0 != l2) {
    abort();
  }
  tmp___1 = bar3(-10);
  if ((unsigned long volatile   )tmp___1 != l3) {
    abort();
  }
  tmp___2 = bar4(-10);
  if ((unsigned long volatile   )tmp___2 != l4) {
    abort();
  }
  tmp___3 = bar5(-10);
  if ((unsigned long volatile   )tmp___3 != l5) {
    abort();
  }
  tmp___4 = bar6(-10);
  if ((unsigned long volatile   )tmp___4 != l6) {
    abort();
  }
  return (0);
}
}
