/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
float ( __attribute__((__noinline__)) float_min1)(float a , float b ) 
{ float tmp ;

  {
  if (a < b) {
    tmp = a;
  } else {
    tmp = b;
  }
  return (tmp);
}
}
float ( __attribute__((__noinline__)) float_min2)(float a , float b ) 
{ float tmp ;

  {
  if (a <= b) {
    tmp = a;
  } else {
    tmp = b;
  }
  return (tmp);
}
}
float ( __attribute__((__noinline__)) float_max1)(float a , float b ) 
{ float tmp ;

  {
  if (a > b) {
    tmp = a;
  } else {
    tmp = b;
  }
  return (tmp);
}
}
float ( __attribute__((__noinline__)) float_max2)(float a , float b ) 
{ float tmp ;

  {
  if (a >= b) {
    tmp = a;
  } else {
    tmp = b;
  }
  return (tmp);
}
}
double ( __attribute__((__noinline__)) double_min1)(double a , double b ) 
{ double tmp ;

  {
  if (a < b) {
    tmp = a;
  } else {
    tmp = b;
  }
  return (tmp);
}
}
double ( __attribute__((__noinline__)) double_min2)(double a , double b ) 
{ double tmp ;

  {
  if (a <= b) {
    tmp = a;
  } else {
    tmp = b;
  }
  return (tmp);
}
}
double ( __attribute__((__noinline__)) double_max1)(double a , double b ) 
{ double tmp ;

  {
  if (a > b) {
    tmp = a;
  } else {
    tmp = b;
  }
  return (tmp);
}
}
double ( __attribute__((__noinline__)) double_max2)(double a , double b ) 
{ double tmp ;

  {
  if (a >= b) {
    tmp = a;
  } else {
    tmp = b;
  }
  return (tmp);
}
}
int main(void) 
{ float tmp ;
  float tmp___0 ;
  float tmp___1 ;
  float tmp___2 ;
  float tmp___3 ;
  float tmp___4 ;
  float tmp___5 ;
  float tmp___6 ;
  float tmp___7 ;
  float tmp___8 ;
  float tmp___9 ;
  float tmp___10 ;
  float tmp___11 ;
  float tmp___12 ;
  float tmp___13 ;
  float tmp___14 ;
  float tmp___15 ;
  float tmp___16 ;
  float tmp___17 ;
  float tmp___18 ;
  float tmp___19 ;
  float tmp___20 ;
  float tmp___21 ;
  float tmp___22 ;
  double tmp___23 ;
  double tmp___24 ;
  double tmp___25 ;
  double tmp___26 ;
  double tmp___27 ;
  double tmp___28 ;
  double tmp___29 ;
  double tmp___30 ;
  double tmp___31 ;
  double tmp___32 ;
  double tmp___33 ;
  double tmp___34 ;
  double tmp___35 ;
  double tmp___36 ;
  double tmp___37 ;
  double tmp___38 ;
  double tmp___39 ;
  double tmp___40 ;
  double tmp___41 ;
  double tmp___42 ;
  double tmp___43 ;
  double tmp___44 ;
  double tmp___45 ;
  double tmp___46 ;

  {
  tmp = float_min1(0.f, - 1.f);
  if (tmp != - 1.f) {
    abort();
  }
  tmp___0 = float_min1(- 1.f, 0.f);
  if (tmp___0 != - 1.f) {
    abort();
  }
  tmp___1 = float_min1(0.f, 1.f);
  if (tmp___1 != 0.f) {
    abort();
  }
  tmp___2 = float_min1(1.f, 0.f);
  if (tmp___2 != 0.f) {
    abort();
  }
  tmp___3 = float_min1(- 1.f, 1.f);
  if (tmp___3 != - 1.f) {
    abort();
  }
  tmp___4 = float_min1(1.f, - 1.f);
  if (tmp___4 != - 1.f) {
    abort();
  }
  tmp___5 = float_max1(0.f, - 1.f);
  if (tmp___5 != 0.f) {
    abort();
  }
  tmp___6 = float_max1(- 1.f, 0.f);
  if (tmp___6 != 0.f) {
    abort();
  }
  tmp___7 = float_max1(0.f, 1.f);
  if (tmp___7 != 1.f) {
    abort();
  }
  tmp___8 = float_max1(1.f, 0.f);
  if (tmp___8 != 1.f) {
    abort();
  }
  tmp___9 = float_max1(- 1.f, 1.f);
  if (tmp___9 != 1.f) {
    abort();
  }
  tmp___10 = float_max1(1.f, - 1.f);
  if (tmp___10 != 1.f) {
    abort();
  }
  tmp___11 = float_min2(0.f, - 1.f);
  if (tmp___11 != - 1.f) {
    abort();
  }
  tmp___12 = float_min2(- 1.f, 0.f);
  if (tmp___12 != - 1.f) {
    abort();
  }
  tmp___13 = float_min2(0.f, 1.f);
  if (tmp___13 != 0.f) {
    abort();
  }
  tmp___14 = float_min2(1.f, 0.f);
  if (tmp___14 != 0.f) {
    abort();
  }
  tmp___15 = float_min2(- 1.f, 1.f);
  if (tmp___15 != - 1.f) {
    abort();
  }
  tmp___16 = float_min2(1.f, - 1.f);
  if (tmp___16 != - 1.f) {
    abort();
  }
  tmp___17 = float_max2(0.f, - 1.f);
  if (tmp___17 != 0.f) {
    abort();
  }
  tmp___18 = float_max2(- 1.f, 0.f);
  if (tmp___18 != 0.f) {
    abort();
  }
  tmp___19 = float_max2(0.f, 1.f);
  if (tmp___19 != 1.f) {
    abort();
  }
  tmp___20 = float_max2(1.f, 0.f);
  if (tmp___20 != 1.f) {
    abort();
  }
  tmp___21 = float_max2(- 1.f, 1.f);
  if (tmp___21 != 1.f) {
    abort();
  }
  tmp___22 = float_max2(1.f, - 1.f);
  if (tmp___22 != 1.f) {
    abort();
  }
  tmp___23 = double_min1(0., - 1.);
  if (tmp___23 != - 1.) {
    abort();
  }
  tmp___24 = double_min1(- 1., 0.);
  if (tmp___24 != - 1.) {
    abort();
  }
  tmp___25 = double_min1(0., 1.);
  if (tmp___25 != 0.) {
    abort();
  }
  tmp___26 = double_min1(1., 0.);
  if (tmp___26 != 0.) {
    abort();
  }
  tmp___27 = double_min1(- 1., 1.);
  if (tmp___27 != - 1.) {
    abort();
  }
  tmp___28 = double_min1(1., - 1.);
  if (tmp___28 != - 1.) {
    abort();
  }
  tmp___29 = double_max1(0., - 1.);
  if (tmp___29 != 0.) {
    abort();
  }
  tmp___30 = double_max1(- 1., 0.);
  if (tmp___30 != 0.) {
    abort();
  }
  tmp___31 = double_max1(0., 1.);
  if (tmp___31 != 1.) {
    abort();
  }
  tmp___32 = double_max1(1., 0.);
  if (tmp___32 != 1.) {
    abort();
  }
  tmp___33 = double_max1(- 1., 1.);
  if (tmp___33 != 1.) {
    abort();
  }
  tmp___34 = double_max1(1., - 1.);
  if (tmp___34 != 1.) {
    abort();
  }
  tmp___35 = double_min2(0., - 1.);
  if (tmp___35 != - 1.) {
    abort();
  }
  tmp___36 = double_min2(- 1., 0.);
  if (tmp___36 != - 1.) {
    abort();
  }
  tmp___37 = double_min2(0., 1.);
  if (tmp___37 != 0.) {
    abort();
  }
  tmp___38 = double_min2(1., 0.);
  if (tmp___38 != 0.) {
    abort();
  }
  tmp___39 = double_min2(- 1., 1.);
  if (tmp___39 != - 1.) {
    abort();
  }
  tmp___40 = double_min2(1., - 1.);
  if (tmp___40 != - 1.) {
    abort();
  }
  tmp___41 = double_max2(0., - 1.);
  if (tmp___41 != 0.) {
    abort();
  }
  tmp___42 = double_max2(- 1., 0.);
  if (tmp___42 != 0.) {
    abort();
  }
  tmp___43 = double_max2(0., 1.);
  if (tmp___43 != 1.) {
    abort();
  }
  tmp___44 = double_max2(1., 0.);
  if (tmp___44 != 1.) {
    abort();
  }
  tmp___45 = double_max2(- 1., 1.);
  if (tmp___45 != 1.) {
    abort();
  }
  tmp___46 = double_max2(1., - 1.);
  if (tmp___46 != 1.) {
    abort();
  }
  exit(0);
}
}
