/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
static unsigned long long foo(unsigned long long x , unsigned long long y ) 
{ 

  {
  return (x / y);
}
}
static int a  ;
static int b  ;
int main(void) 
{ unsigned long long c ;
  unsigned long long tmp ;
  int tmp___0 ;

  {
  c = 1ULL;
  if (c) {
    tmp = foo((unsigned long long )a, 0xffffffffffffffffULL);
    if (tmp != 1ULL) {
      tmp___0 = 1;
    } else {
      tmp___0 = 0;
    }
  } else {
    tmp___0 = 0;
  }
  b ^= tmp___0;
  if (b != 1) {
    abort();
  }
  return (0);
}
}
