/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
static unsigned int my_add(unsigned int si1 , unsigned int si2 ) 
{ unsigned int tmp ;

  {
  if (si1 > 50U - si2) {
    tmp = si1;
  } else {
    tmp = si1 + si2;
  }
  return (tmp);
}
}
static unsigned int my_shift(unsigned int left , unsigned int right ) 
{ unsigned int tmp ;

  {
  if (right > 100U) {
    tmp = left;
  } else {
    tmp = left >> right;
  }
  return (tmp);
}
}
static int func_4(unsigned int p_6 ) 
{ int count ;
  int tmp ;
  unsigned int tmp___0 ;

  {
  count = 0;
  p_6 = 1U;
  while (p_6 < 3U) {
    tmp = count;
    count ++;
    if (tmp > 1) {
      abort();
    }
    tmp___0 = my_shift(p_6, p_6);
    if (tmp___0) {
      return (0);
    }
    p_6 = my_add(p_6, 1U);
  }
  return (0);
}
}
int main(void) 
{ 

  {
  func_4(0U);
  return (0);
}
}
