/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct A {
   char x[1] ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
void __attribute__((__noclone__))  ( __attribute__((__noinline__)) foo)(struct A a ) 
{ 

  {
  if ((int )a.x[0] != 97) {
    abort();
  }
  return;
}
}
int main(void) 
{ struct A a ;
  int i ;

  {
  i = 0;
  while (i < 1) {
    a.x[i] = (char )'a';
    i ++;
  }
  foo(a);
  return (0);
}
}
