/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
static unsigned char g_2  =    (unsigned char)1;
static int g_9  ;
static int *l_8  =    & g_9;
static void func_12(int p_13 ) 
{ int *l_17 ;

  {
  l_17 = & g_9;
  *l_17 &= 0 < p_13;
  return;
}
}
int main(void) 
{ unsigned char l_11 ;

  {
  l_11 = (unsigned char)254;
  *l_8 |= (int )g_2;
  l_11 = (unsigned char )((int )l_11 | *l_8);
  func_12((int )l_11);
  if (g_9 != 1) {
    abort();
  }
  return (0);
}
}
