/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 8 "fsl-header.h"
extern void abort(void) ;
#line 4 "pr44828.c"
static signed char foo(signed char si1 , signed char si2 ) 
{ 

  {
#line 7
  return ((signed char )((int )si1 * (int )si2));
}
}
#line 10 "pr44828.c"
int a  =    274686410;
#line 12 "pr44828.c"
int main(void) 
{ int b ;
  signed char tmp ;

  {
#line 15
  b = 53671368;
#line 16
  tmp = foo((signed char )b, (signed char )a);
#line 16
  if ((int )tmp > 0) {
#line 17
    abort();
  }
#line 18
  return (0);
}
}
