/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 2 "pr44164.c"
struct Z {
   int i ;
};
#line 2 "pr44164.c"
struct YY {
   struct Z c ;
};
#line 2 "pr44164.c"
struct Y {
   struct YY bb ;
};
#line 2 "pr44164.c"
struct X {
   struct Y b ;
};
#line 8 "fsl-header.h"
extern void abort(void) ;
#line 2 "pr44164.c"
struct X a  ;
#line 11 "pr44164.c"
int __attribute__((__noclone__))  ( __attribute__((__noinline__)) foo)(struct Z *p ) 
{ int i ;
  struct Y __constr_expr_0 ;

  {
#line 14
  i = p->i;
#line 15
  __constr_expr_0.bb.c.i = 0;
#line 15
  a.b = __constr_expr_0;
#line 16
  return ((int __attribute__((__noclone__))  )(p->i + i));
}
}
#line 19 "pr44164.c"
int main(void) 
{ int __attribute__((__noclone__))  tmp ;

  {
#line 21
  a.b.bb.c.i = 1;
#line 22
  tmp = foo(& a.b.bb.c);
#line 22
  if (tmp != (int __attribute__((__noclone__))  )1) {
#line 23
    abort();
  }
#line 24
  return (0);
}
}
