/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__noreturn__)) void exit(int  ) ;
extern  __attribute__((__noreturn__)) void abort(void) ;
int ( __attribute__((__noinline__)) add512)(int a , int *b ) 
{ int c ;

  {
  c = a + 512;
  if (c != 0) {
    *b = a;
  }
  return (c);
}
}
int ( __attribute__((__noinline__)) add513)(int a , int *b ) 
{ int c ;

  {
  c = a + 513;
  if (c == 0) {
    *b = a;
  }
  return (c);
}
}
int main(void) 
{ int b0 ;
  int b1 ;
  int tmp ;
  int tmp___0 ;

  {
  b0 = -1;
  b1 = -1;
  tmp = add512(-512, & b0);
  if (tmp != 0) {
    abort();
  } else {
    if (b0 != -1) {
      abort();
    } else {
      tmp___0 = add513(-513, & b1);
      if (tmp___0 != 0) {
        abort();
      } else {
        if (b1 != -513) {
          abort();
        }
      }
    }
  }
  exit(0);
}
}
