/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 6 "pr45262.c"
int foo(unsigned int x ) 
{ int tmp ;

  {
#line 9
  if ((int )x < 0) {
#line 9
    tmp = 1;
  } else {
#line 9
    if ((int )(- x) < 0) {
#line 9
      tmp = 1;
    } else {
#line 9
      tmp = 0;
    }
  }
#line 9
  return (tmp);
}
}
#line 12 "pr45262.c"
int bar(unsigned int x ) 
{ int tmp ;

  {
#line 15
  if (x >> 31) {
#line 15
    tmp = 1;
  } else {
#line 15
    if (- x >> 31) {
#line 15
      tmp = 1;
    } else {
#line 15
      tmp = 0;
    }
  }
#line 15
  return (tmp);
}
}
#line 18 "pr45262.c"
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;

  {
#line 20
  tmp = foo(1U);
#line 20
  if (tmp != 1) {
#line 21
    abort();
  }
#line 22
  tmp___0 = foo(0U);
#line 22
  if (tmp___0 != 0) {
#line 23
    abort();
  }
#line 24
  tmp___1 = foo(4294967295U);
#line 24
  if (tmp___1 != 1) {
#line 25
    abort();
  }
#line 26
  tmp___2 = bar(1U);
#line 26
  if (tmp___2 != 1) {
#line 27
    abort();
  }
#line 28
  tmp___3 = bar(0U);
#line 28
  if (tmp___3 != 0) {
#line 29
    abort();
  }
#line 30
  tmp___4 = bar(4294967295U);
#line 30
  if (tmp___4 != 1) {
#line 31
    abort();
  }
#line 32
  return (0);
}
}
