/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
int foo(unsigned int x ) 
{ int tmp ;

  {
  if ((int )x < 0) {
    tmp = 1;
  } else {
    if ((int )(- x) < 0) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  }
  return (tmp);
}
}
int bar(unsigned int x ) 
{ int tmp ;

  {
  if (x >> 31) {
    tmp = 1;
  } else {
    if (- x >> 31) {
      tmp = 1;
    } else {
      tmp = 0;
    }
  }
  return (tmp);
}
}
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;

  {
  tmp = foo(1U);
  if (tmp != 1) {
    abort();
  }
  tmp___0 = foo(0U);
  if (tmp___0 != 0) {
    abort();
  }
  tmp___1 = foo(4294967295U);
  if (tmp___1 != 1) {
    abort();
  }
  tmp___2 = bar(1U);
  if (tmp___2 != 1) {
    abort();
  }
  tmp___3 = bar(0U);
  if (tmp___3 != 0) {
    abort();
  }
  tmp___4 = bar(4294967295U);
  if (tmp___4 != 1) {
    abort();
  }
  return (0);
}
}
