/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct packed_ushort {
   unsigned short ucs ;
} __attribute__((__packed__)) ;
struct source {
   int pos ;
   int length ;
   int flag ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
static void ( __attribute__((__noinline__)) fetch)(struct source *p ) 
{ 

  {
  p->length = 128;
  return;
}
}
static struct packed_ushort ( __attribute__((__noinline__)) next)(struct source *p ) 
{ struct packed_ushort rv ;
  struct packed_ushort tmp ;

  {
  if (p->pos >= p->length) {
    if (p->flag) {
      p->flag = 0;
      fetch(p);
      tmp = next(p);
      return (tmp);
    }
    p->flag = 1;
    rv.ucs = (unsigned short)65535;
    return (rv);
  }
  rv.ucs = (unsigned short)0;
  return (rv);
}
}
int main(void) 
{ struct source s ;
  int i ;
  struct packed_ushort rv ;
  struct packed_ushort tmp ;

  {
  s.pos = 0;
  s.length = 0;
  s.flag = 0;
  i = 0;
  while (i < 16) {
    tmp = next(& s);
    rv = tmp;
    if (i == 0) {
      if ((int )rv.ucs != 65535) {
        abort();
      } else {
        goto _L;
      }
    } else {
      _L: /* CIL Label */ 
      if (i > 0) {
        if ((int )rv.ucs != 0) {
          abort();
        }
      }
    }
    i ++;
  }
  return (0);
}
}
