/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 6 "pr46019.c"
int main(void) 
{ unsigned long long l ;
  int n ;

  {
#line 8
  l = 4398046511104ULL;
#line 10
  n = 0;
#line 10
  while (n < 8) {
#line 11
    if (l / (8589934592ULL << n) != (unsigned long long )(512 >> n)) {
#line 12
      abort();
    }
#line 10
    n ++;
  }
#line 13
  return (0);
}
}
