/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef __builtin_va_list __gnuc_va_list;
typedef __gnuc_va_list va_list;
struct tiny {
   char c ;
   char d ;
   char e ;
   char f ;
   char g ;
};
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
void f(int n  , ...) 
{ struct tiny x ;
  int i ;
  va_list ap ;
  long x___0 ;
  long tmp ;

  {
  __builtin_va_start(ap, n);
  i = 0;
  while (i < n) {
    x = __builtin_va_arg(ap, struct tiny );
    if ((int )x.c != i + 10) {
      abort();
    }
    if ((int )x.d != i + 20) {
      abort();
    }
    if ((int )x.e != i + 30) {
      abort();
    }
    if ((int )x.f != i + 40) {
      abort();
    }
    if ((int )x.g != i + 50) {
      abort();
    }
    i ++;
  }
  tmp = __builtin_va_arg(ap, long );
  x___0 = tmp;
  if (x___0 != 123L) {
    abort();
  }
  __builtin_va_end(ap);
  return;
}
}
int main(void) 
{ struct tiny x[3] ;

  {
  x[0].c = (char)10;
  x[1].c = (char)11;
  x[2].c = (char)12;
  x[0].d = (char)20;
  x[1].d = (char)21;
  x[2].d = (char)22;
  x[0].e = (char)30;
  x[1].e = (char)31;
  x[2].e = (char)32;
  x[0].f = (char)40;
  x[1].f = (char)41;
  x[2].f = (char)42;
  x[0].g = (char)50;
  x[1].g = (char)51;
  x[2].g = (char)52;
  f(3, x[0], x[1], x[2], 123L);
  exit(0);
}
}
