/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct termios {
   unsigned int a ;
   unsigned int b ;
   unsigned int c ;
   unsigned int d ;
   unsigned char pad[28] ;
};
struct tty_driver {
   unsigned char pad1[38] ;
   struct termios t  __attribute__((__aligned__(8))) ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
static struct termios zero_t  ;
static struct tty_driver pty  ;
void ini(void) 
{ 

  {
  pty.t = zero_t;
  pty.t.a = 1U;
  pty.t.b = 2U;
  pty.t.c = 3U;
  pty.t.d = 4U;
  return;
}
}
int main(void) 
{ 

  {
  ini();
  if (pty.t.a != 1U) {
    abort();
  } else {
    if (pty.t.b != 2U) {
      abort();
    } else {
      if (pty.t.c != 3U) {
        abort();
      } else {
        if (pty.t.d != 4U) {
          abort();
        }
      }
    }
  }
  return (0);
}
}
