/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

struct S {
   char f1 ;
   int f2[2] ;
};
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
struct S object  =    {(char )'X', {8, 9}};
int main(void) 
{ 

  {
  if ((int )object.f1 != 88) {
    abort();
  } else {
    if (object.f2[0] != 8) {
      abort();
    } else {
      if (object.f2[1] != 9) {
        abort();
      }
    }
  }
  exit(0);
}
}
