/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
int ( __attribute__((__noinline__)) foo)(short x , unsigned short y ) 
{ 

  {
  return ((int )x * (int )y);
}
}
int ( __attribute__((__noinline__)) bar)(unsigned short x , short y ) 
{ 

  {
  return ((int )x * (int )y);
}
}
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;

  {
  tmp = foo((short)-2, (unsigned short)65535);
  if (tmp != -131070) {
    abort();
  }
  tmp___0 = foo((short)2, (unsigned short)65535);
  if (tmp___0 != 131070) {
    abort();
  }
  tmp___1 = foo((short)-32768, (unsigned short)32768);
  if (tmp___1 != -1073741824) {
    abort();
  }
  tmp___2 = foo((short)32767, (unsigned short)32768);
  if (tmp___2 != 1073709056) {
    abort();
  }
  tmp___3 = bar((unsigned short)65535, (short)-2);
  if (tmp___3 != -131070) {
    abort();
  }
  tmp___4 = bar((unsigned short)65535, (short)2);
  if (tmp___4 != 131070) {
    abort();
  }
  tmp___5 = bar((unsigned short)32768, (short)-32768);
  if (tmp___5 != -1073741824) {
    abort();
  }
  tmp___6 = bar((unsigned short)32768, (short)32767);
  if (tmp___6 != 1073709056) {
    abort();
  }
  exit(0);
}
}
