/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 2 "usmul.c"
int ( __attribute__((__noinline__)) foo)(short x , unsigned short y ) 
{ 

  {
#line 4
  return ((int )x * (int )y);
}
}
#line 7 "usmul.c"
int ( __attribute__((__noinline__)) bar)(unsigned short x , short y ) 
{ 

  {
#line 9
  return ((int )x * (int )y);
}
}
#line 12 "usmul.c"
int main(void) 
{ int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;

  {
#line 14
  tmp = foo((short)-2, (unsigned short)65535);
#line 14
  if (tmp != -131070) {
#line 15
    abort();
  }
#line 16
  tmp___0 = foo((short)2, (unsigned short)65535);
#line 16
  if (tmp___0 != 131070) {
#line 17
    abort();
  }
#line 18
  tmp___1 = foo((short)-32768, (unsigned short)32768);
#line 18
  if (tmp___1 != -1073741824) {
#line 19
    abort();
  }
#line 20
  tmp___2 = foo((short)32767, (unsigned short)32768);
#line 20
  if (tmp___2 != 1073709056) {
#line 21
    abort();
  }
#line 23
  tmp___3 = bar((unsigned short)65535, (short)-2);
#line 23
  if (tmp___3 != -131070) {
#line 24
    abort();
  }
#line 25
  tmp___4 = bar((unsigned short)65535, (short)2);
#line 25
  if (tmp___4 != 131070) {
#line 26
    abort();
  }
#line 27
  tmp___5 = bar((unsigned short)32768, (short)-32768);
#line 27
  if (tmp___5 != -1073741824) {
#line 28
    abort();
  }
#line 29
  tmp___6 = bar((unsigned short)32768, (short)32767);
#line 29
  if (tmp___6 != 1073709056) {
#line 30
    abort();
  }
#line 32
  exit(0);
}
}
