/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef __builtin_va_list __gnuc_va_list;
typedef __gnuc_va_list va_list;
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
extern int printf(char const   * __restrict  __format  , ...) ;
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
static int errors  =    0;
static void verify(char const   *tcase , int *n ) 
{ int i ;

  {
  i = 0;
  while (i <= 10) {
    if (*(n + i) != i) {
      printf((char const   * __restrict  )" %s: n[%d] = %d expected %d\n", tcase,
             i, *(n + i), i);
      errors ++;
    }
    i ++;
  }
  return;
}
}
static void varargs0(int q0  , ...) 
{ va_list ap ;
  int n[11] ;
  int i ;

  {
  __builtin_va_start(ap, q0);
  n[0] = q0;
  i = 1;
  while (i <= 10) {
    n[i] = __builtin_va_arg(ap, int );
    i ++;
  }
  __builtin_va_end(ap);
  verify("varargs0", (int *)(n));
  return;
}
}
static void varargs1(int q0 , int q1  , ...) 
{ va_list ap ;
  int n[11] ;
  int i ;

  {
  __builtin_va_start(ap, q1);
  n[0] = q0;
  n[1] = q1;
  i = 2;
  while (i <= 10) {
    n[i] = __builtin_va_arg(ap, int );
    i ++;
  }
  __builtin_va_end(ap);
  verify("varargs1", (int *)(n));
  return;
}
}
static void varargs2(int q0 , int q1 , int q2  , ...) 
{ va_list ap ;
  int n[11] ;
  int i ;

  {
  __builtin_va_start(ap, q2);
  n[0] = q0;
  n[1] = q1;
  n[2] = q2;
  i = 3;
  while (i <= 10) {
    n[i] = __builtin_va_arg(ap, int );
    i ++;
  }
  __builtin_va_end(ap);
  verify("varargs2", (int *)(n));
  return;
}
}
static void varargs3(int q0 , int q1 , int q2 , int q3  , ...) 
{ va_list ap ;
  int n[11] ;
  int i ;

  {
  __builtin_va_start(ap, q3);
  n[0] = q0;
  n[1] = q1;
  n[2] = q2;
  n[3] = q3;
  i = 4;
  while (i <= 10) {
    n[i] = __builtin_va_arg(ap, int );
    i ++;
  }
  __builtin_va_end(ap);
  verify("varargs3", (int *)(n));
  return;
}
}
static void varargs4(int q0 , int q1 , int q2 , int q3 , int q4  , ...) 
{ va_list ap ;
  int n[11] ;
  int i ;

  {
  __builtin_va_start(ap, q4);
  n[0] = q0;
  n[1] = q1;
  n[2] = q2;
  n[3] = q3;
  n[4] = q4;
  i = 5;
  while (i <= 10) {
    n[i] = __builtin_va_arg(ap, int );
    i ++;
  }
  __builtin_va_end(ap);
  verify("varargs4", (int *)(n));
  return;
}
}
static void varargs5(int q0 , int q1 , int q2 , int q3 , int q4 , int q5  , ...) 
{ va_list ap ;
  int n[11] ;
  int i ;

  {
  __builtin_va_start(ap, q5);
  n[0] = q0;
  n[1] = q1;
  n[2] = q2;
  n[3] = q3;
  n[4] = q4;
  n[5] = q5;
  i = 6;
  while (i <= 10) {
    n[i] = __builtin_va_arg(ap, int );
    i ++;
  }
  __builtin_va_end(ap);
  verify("varargs5", (int *)(n));
  return;
}
}
static void varargs6(int q0 , int q1 , int q2 , int q3 , int q4 , int q5 , int q6 
                     , ...) 
{ va_list ap ;
  int n[11] ;
  int i ;

  {
  __builtin_va_start(ap, q6);
  n[0] = q0;
  n[1] = q1;
  n[2] = q2;
  n[3] = q3;
  n[4] = q4;
  n[5] = q5;
  n[6] = q6;
  i = 7;
  while (i <= 10) {
    n[i] = __builtin_va_arg(ap, int );
    i ++;
  }
  __builtin_va_end(ap);
  verify("varargs6", (int *)(n));
  return;
}
}
static void varargs7(int q0 , int q1 , int q2 , int q3 , int q4 , int q5 , int q6 ,
                     int q7  , ...) 
{ va_list ap ;
  int n[11] ;
  int i ;

  {
  __builtin_va_start(ap, q7);
  n[0] = q0;
  n[1] = q1;
  n[2] = q2;
  n[3] = q3;
  n[4] = q4;
  n[5] = q5;
  n[6] = q6;
  n[7] = q7;
  i = 8;
  while (i <= 10) {
    n[i] = __builtin_va_arg(ap, int );
    i ++;
  }
  __builtin_va_end(ap);
  verify("varargs7", (int *)(n));
  return;
}
}
static void varargs8(int q0 , int q1 , int q2 , int q3 , int q4 , int q5 , int q6 ,
                     int q7 , int q8  , ...) 
{ va_list ap ;
  int n[11] ;
  int i ;

  {
  __builtin_va_start(ap, q8);
  n[0] = q0;
  n[1] = q1;
  n[2] = q2;
  n[3] = q3;
  n[4] = q4;
  n[5] = q5;
  n[6] = q6;
  n[7] = q7;
  n[8] = q8;
  i = 9;
  while (i <= 10) {
    n[i] = __builtin_va_arg(ap, int );
    i ++;
  }
  __builtin_va_end(ap);
  verify("varargs8", (int *)(n));
  return;
}
}
static void varargs9(int q0 , int q1 , int q2 , int q3 , int q4 , int q5 , int q6 ,
                     int q7 , int q8 , int q9  , ...) 
{ va_list ap ;
  int n[11] ;
  int i ;

  {
  __builtin_va_start(ap, q9);
  n[0] = q0;
  n[1] = q1;
  n[2] = q2;
  n[3] = q3;
  n[4] = q4;
  n[5] = q5;
  n[6] = q6;
  n[7] = q7;
  n[8] = q8;
  n[9] = q9;
  i = 10;
  while (i <= 10) {
    n[i] = __builtin_va_arg(ap, int );
    i ++;
  }
  __builtin_va_end(ap);
  verify("varargs9", (int *)(n));
  return;
}
}
int main(void) 
{ 

  {
  varargs0(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
  varargs1(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
  varargs2(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
  varargs3(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
  varargs4(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
  varargs5(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
  varargs6(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
  varargs7(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
  varargs8(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
  varargs9(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
  if (errors) {
    abort();
  }
  exit(0);
}
}
