/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 9 "../../lib/includes/stdlib.h"
typedef unsigned int size_t;
#line 6 "../../lib/includes/stdarg.h"
typedef void *va_list;
#line 9 "va-arg-8.c"
typedef long long INT64;
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 27 "../../lib/includes/stdarg.h"
extern va_list __va_inc(va_list *ap , size_t size ) ;
#line 32
extern void __va_start(va_list *ap , void *pN ) ;
#line 37
extern void __va_end(va_list *ap ) ;
#line 11 "va-arg-8.c"
__inline void debug(int i1 , int i2 , int i3 , int i4 , int i5 , int i6 , int i7 ,
                    int i8 , int i9  , ...) 
{ va_list ap ;
  va_list tmp ;
  va_list tmp___0 ;

  {
#line 17
  __va_start(& ap, (void *)(& i9));
#line 19
  tmp = __va_inc(& ap, (unsigned int )sizeof(int ));
#line 19
  if (*((int *)tmp) != 10) {
#line 20
    abort();
  }
#line 21
  tmp___0 = __va_inc(& ap, (unsigned int )sizeof(INT64 ));
#line 21
  if (*((INT64 *)tmp___0) != 20014547621496LL) {
#line 22
    abort();
  }
#line 24
  __va_end(& ap);
#line 25
  return;
}
}
#line 27 "va-arg-8.c"
int main(void) 
{ 

  {
#line 29
  debug(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20014547621496LL);
#line 30
  exit(0);
}
}
