/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef __builtin_va_list __gnuc_va_list;
typedef __gnuc_va_list va_list;
struct __anonstruct_big_21 {
   char a[32] ;
};
typedef struct __anonstruct_big_21 big;
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
void f(big x , char *s  , ...) 
{ va_list ap ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;

  {
  if ((int )x.a[0] != 97) {
    abort();
  } else {
    if ((int )x.a[1] != 98) {
      abort();
    } else {
      if ((int )x.a[2] != 99) {
        abort();
      }
    }
  }
  __builtin_va_start(ap, s);
  tmp = __builtin_va_arg(ap, int );
  if (tmp != 42) {
    abort();
  }
  tmp___0 = __builtin_va_arg(ap, int );
  if (tmp___0 != 120) {
    abort();
  }
  tmp___1 = __builtin_va_arg(ap, int );
  if (tmp___1 != 0) {
    abort();
  }
  __builtin_va_end(ap);
  return;
}
}
int main(void) ;
static big x  =    {{(char )'a', (char )'b', (char )'c', (char )'\000'}};
int main(void) 
{ 

  {
  f(x, (char *)"", 42, 'x', 0);
  exit(0);
}
}
