/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef __builtin_va_list __gnuc_va_list;
typedef __gnuc_va_list va_list;
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_copy(__builtin_va_list  , __builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
extern void exit(int status ) ;
extern void abort(void) ;
extern unsigned long strlen(char const   * ) ;
int to_hex(unsigned int a ) ;
static char hex[17]  = 
  {      (char )'0',      (char )'1',      (char )'2',      (char )'3', 
        (char )'4',      (char )'5',      (char )'6',      (char )'7', 
        (char )'8',      (char )'9',      (char )'a',      (char )'b', 
        (char )'c',      (char )'d',      (char )'e',      (char )'f', 
        (char )'\000'};
int to_hex(unsigned int a ) 
{ 

  {
  if (a > 15U) {
    abort();
  }
  return ((int )hex[a]);
}
}
void fap(int i , char *format , va_list ap ) 
{ va_list apc ;
  char *formatc ;
  unsigned long tmp ;
  char *tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  char *tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;

  {
  __builtin_va_copy(apc, ap);
  formatc = format;
  tmp = strlen((char const   *)format);
  if (tmp != (unsigned long )(16 - i)) {
    abort();
  }
  while (*format) {
    tmp___0 = format;
    format ++;
    tmp___1 = __builtin_va_arg(ap, int );
    tmp___2 = to_hex((unsigned int )tmp___1);
    if ((int )*tmp___0 != tmp___2) {
      abort();
    }
  }
  while (*formatc) {
    tmp___3 = formatc;
    formatc ++;
    tmp___4 = __builtin_va_arg(apc, int );
    tmp___5 = to_hex((unsigned int )tmp___4);
    if ((int )*tmp___3 != tmp___5) {
      abort();
    }
  }
  return;
}
}
void f0(char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(0, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f1(int a1 , char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(1, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f2(int a1 , int a2 , char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(2, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f3(int a1 , int a2 , int a3 , char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(3, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f4(int a1 , int a2 , int a3 , int a4 , char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(4, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f5(int a1 , int a2 , int a3 , int a4 , int a5 , char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(5, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f6(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(6, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f7(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , char *format 
        , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(7, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f8(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , char *format 
        , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(8, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f9(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
        char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(9, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f10(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
         int a10 , char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(10, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f11(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
         int a10 , int a11 , char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(11, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f12(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
         int a10 , int a11 , int a12 , char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(12, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f13(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
         int a10 , int a11 , int a12 , int a13 , char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(13, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f14(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
         int a10 , int a11 , int a12 , int a13 , int a14 , char *format  , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(14, format, ap);
  __builtin_va_end(ap);
  return;
}
}
void f15(int a1 , int a2 , int a3 , int a4 , int a5 , int a6 , int a7 , int a8 , int a9 ,
         int a10 , int a11 , int a12 , int a13 , int a14 , int a15 , char *format 
         , ...) 
{ va_list ap ;

  {
  __builtin_va_start(ap, format);
  fap(15, format, ap);
  __builtin_va_end(ap);
  return;
}
}
int main(void) 
{ char *f ;

  {
  f = (char *)"0123456789abcdef";
  f0(f + 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
  f1(0, f + 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
  f2(0, 1, f + 2, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
  f3(0, 1, 2, f + 3, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
  f4(0, 1, 2, 3, f + 4, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
  f5(0, 1, 2, 3, 4, f + 5, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
  f6(0, 1, 2, 3, 4, 5, f + 6, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15);
  f7(0, 1, 2, 3, 4, 5, 6, f + 7, 7, 8, 9, 10, 11, 12, 13, 14, 15);
  f8(0, 1, 2, 3, 4, 5, 6, 7, f + 8, 8, 9, 10, 11, 12, 13, 14, 15);
  f9(0, 1, 2, 3, 4, 5, 6, 7, 8, f + 9, 9, 10, 11, 12, 13, 14, 15);
  f10(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, f + 10, 10, 11, 12, 13, 14, 15);
  f11(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, f + 11, 11, 12, 13, 14, 15);
  f12(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, f + 12, 12, 13, 14, 15);
  f13(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, f + 13, 13, 14, 15);
  f14(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, f + 14, 14, 15);
  f15(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, f + 15, 15);
  exit(0);
}
}
