/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef __builtin_va_list __gnuc_va_list;
typedef __gnuc_va_list va_list;
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
extern void exit(int  ) ;
extern void abort(void) ;
va_list ap  ;
float f  ;
va_list *foo(void) 
{ 

  {
  exit(0);
  return (& ap);
}
}
void bar(int i  , ...) 
{ va_list *tmp ;

  {
  __builtin_va_start(ap, i);
  tmp = foo();
  f = __builtin_va_arg(*tmp, float );
  __builtin_va_end(ap);
  return;
}
}
int main(void) 
{ 

  {
  bar(1, 0);
  abort();
  return (0);
}
}
