/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 6 "../../lib/includes/stdarg.h"
typedef __builtin_va_list va_list;
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 25 "../../lib/includes/stdarg.h"
extern void *__va_arg(va_list *ap ) ;
#line 30
extern void __va_start(va_list *ap , void *pN ) ;
#line 35
extern void __va_end(va_list *ap ) ;
#line 13 "va-arg-trap-1.c"
va_list ap  ;
#line 14 "va-arg-trap-1.c"
float f  ;
#line 16 "va-arg-trap-1.c"
va_list *foo(void) 
{ 

  {
#line 19
  exit(0);
#line 20
  return (& ap);
}
}
#line 23 "va-arg-trap-1.c"
void bar(int i  , ...) 
{ va_list *tmp ;
  void *tmp___0 ;

  {
#line 26
  __va_start(& ap, (void *)(& i));
#line 27
  tmp = foo();
#line 27
  tmp___0 = __va_arg(tmp);
#line 27
  f = *((float *)tmp___0);
#line 28
  __va_end(& ap);
#line 29
  return;
}
}
#line 31 "va-arg-trap-1.c"
int main(void) 
{ 

  {
#line 33
  bar(1, 0);
#line 34
  abort();
#line 35
  return (0);
}
}
