/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 6 "../../lib/includes/stdarg.h"
typedef __builtin_va_list va_list;
#line 9 "va-arg-23.c"
struct two {
   long x ;
   long y ;
};
#line 21 "../../lib/includes/stdlib.h"
extern void abort(void) ;
#line 25 "../../lib/includes/stdarg.h"
extern void *__va_arg(va_list *ap ) ;
#line 30
extern void __va_start(va_list *ap , void *pN ) ;
#line 11 "va-arg-23.c"
void foo(int a , int b , int c , int d , int e , struct two f , int g  , ...) 
{ va_list args ;
  int h ;
  void *tmp ;

  {
#line 16
  __va_start(& args, (void *)(& g));
#line 17
  tmp = __va_arg(& args);
#line 17
  h = *((int *)tmp);
#line 18
  if (g != 1) {
#line 19
    abort();
  } else {
#line 18
    if (h != 2) {
#line 19
      abort();
    }
  }
#line 20
  return;
}
}
#line 22 "va-arg-23.c"
int main(void) 
{ struct two t ;

  {
#line 24
  t.x = 0L;
#line 24
  t.y = 0L;
#line 25
  foo(0, 0, 0, 0, 0, t, 1, 2);
#line 26
  return (0);
}
}
