/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

typedef __builtin_va_list __gnuc_va_list;
typedef __gnuc_va_list va_list;
struct __anonstruct_ScanfState_21 {
   void *stream ;
   va_list ap ;
   int nChar ;
};
typedef struct __anonstruct_ScanfState_21 ScanfState;
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
extern  __attribute__((__nothrow__, __noreturn__)) void abort(void)  __attribute__((__leaf__)) ;
extern  __attribute__((__nothrow__, __noreturn__)) void exit(int __status )  __attribute__((__leaf__)) ;
void dummy(va_list vap ) 
{ int tmp ;

  {
  tmp = __builtin_va_arg(vap, int );
  if (tmp != 1234) {
    abort();
  }
  return;
}
}
void test(int fmt  , ...) 
{ ScanfState state ;
  ScanfState *statep ;

  {
  statep = & state;
  __builtin_va_start(statep->ap, fmt);
  dummy(statep->ap);
  __builtin_va_end(statep->ap);
  __builtin_va_start(state.ap, fmt);
  dummy(state.ap);
  __builtin_va_end(state.ap);
  return;
}
}
int main(void) 
{ 

  {
  test(456, 1234);
  exit(0);
}
}
