/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 9 "../../lib/includes/stdlib.h"
typedef unsigned int size_t;
#line 6 "../../lib/includes/stdarg.h"
typedef void *va_list;
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 27 "../../lib/includes/stdarg.h"
extern va_list __va_inc(va_list *ap , size_t size ) ;
#line 32
extern void __va_start(va_list *ap , void *pN ) ;
#line 37
extern void __va_end(va_list *ap ) ;
#line 4 "va-arg-15.c"
void vafunction(char *dummy  , ...) 
{ double darg ;
  int iarg ;
  int flag ;
  int i ;
  va_list ap ;
  va_list tmp ;
  va_list tmp___0 ;

  {
#line 8
  flag = 0;
#line 12
  __va_start(& ap, (void *)(& dummy));
#line 13
  i = 1;
#line 13
  while (i <= 18) {
#line 15
    if (flag & 1) {
#line 17
      tmp = __va_inc(& ap, (unsigned int )sizeof(double ));
#line 17
      darg = *((double *)tmp);
#line 18
      if (darg != (double )i) {
#line 19
        abort();
      }
    } else {
#line 23
      tmp___0 = __va_inc(& ap, (unsigned int )sizeof(int ));
#line 23
      iarg = *((int *)tmp___0);
#line 24
      if (iarg != i) {
#line 25
        abort();
      }
    }
#line 13
    i ++;
#line 13
    flag ++;
  }
#line 28
  __va_end(& ap);
#line 29
  return;
}
}
#line 31 "va-arg-15.c"
int main(void) 
{ 

  {
#line 33
  vafunction((char *)"", 1, 2., 3, 4., 5, 6., 7, 8., 9, 10., 11, 12., 13, 14., 15,
             16., 17, 18.);
#line 43
  exit(0);
#line 44
  return (0);
}
}
