/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 6 "../../lib/includes/stdarg.h"
typedef __builtin_va_list va_list;
#line 4 "va-arg-1.c"
typedef unsigned long L;
#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 21
extern void abort(void) ;
#line 25 "../../lib/includes/stdarg.h"
extern void *__va_arg(va_list *ap ) ;
#line 30
extern void __va_start(va_list *ap , void *pN ) ;
#line 35
extern void __va_end(va_list *ap ) ;
#line 5 "va-arg-1.c"
void f(L p0 , L p1 , L p2 , L p3 , L p4 , L p5 , L p6 , L p7 , L p8  , ...) 
{ va_list select ;
  void *tmp ;
  void *tmp___0 ;
  void *tmp___1 ;

  {
#line 9
  __va_start(& select, (void *)(& p8));
#line 11
  tmp = __va_arg(& select);
#line 11
  if (*((L *)tmp) != 10UL) {
#line 12
    abort();
  }
#line 13
  tmp___0 = __va_arg(& select);
#line 13
  if (*((L *)tmp___0) != 11UL) {
#line 14
    abort();
  }
#line 15
  tmp___1 = __va_arg(& select);
#line 15
  if (*((L *)tmp___1) != 0UL) {
#line 16
    abort();
  }
#line 18
  __va_end(& select);
#line 19
  return;
}
}
#line 21 "va-arg-1.c"
int main(void) 
{ 

  {
#line 23
  f(1UL, 2UL, 3UL, 4UL, 5UL, 6UL, 7UL, 8UL, 9UL, 10L, 11L, 0L);
#line 24
  exit(0);
}
}
