/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 1 "vrp-5.c"
extern void exit(int  ) ;
#line 2
extern void abort() ;
#line 4 "vrp-5.c"
void test(unsigned int a , unsigned int b ) 
{ 

  {
#line 6
  if (a < 5U) {
#line 7
    abort();
  }
#line 8
  if (b < 5U) {
#line 9
    abort();
  }
#line 10
  if (a + b != 0U) {
#line 11
    abort();
  }
#line 12
  return;
}
}
#line 14 "vrp-5.c"
int main(int argc , char **argv ) 
{ unsigned int x ;

  {
#line 16
  x = 2147483648U;
#line 17
  test(x, x);
#line 18
  exit(0);
}
}
