/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 17 "../../lib/includes/stdlib.h"
extern void exit(int status ) ;
#line 10 "widechar-1.c"
int main(void) 
{ 

  {
#line 14
  exit(0);
}
}
