#!/bin/bash
docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -t old-c-semantics .
#docker create --name my-c-semantics c-semantics
docker run --rm --mount src=$(pwd),target=/home/user/c-semantics,type=bind --workdir=/home/user/c-semantics old-c-semantics make
