#!/usr/bin/env perl
use strict;
use warnings;

use File::Basename;
use File::Spec::Functions qw(rel2abs catfile);

my $distDirectory = dirname(rel2abs($0));
opendir (my $DIR, $distDirectory);
my @profiles = ();
while ( my $entry = readdir $DIR) {
  next unless -d $distDirectory . '/' . $entry;
  next if $entry eq '.' or $entry eq '..';
  push(@profiles, $entry);
}

my $profile = "default-profile";
if(-e "$distDirectory/current-profile")
{
  local $/=undef;
  open FILE, "$distDirectory/current-profile";
  $profile = <FILE>;
  close FILE;
}

if ($ARGV[0]) {
  open(my $file, '>', "$distDirectory/current-profile") or die "Could not open profile file. Check OS permissions.";
  print $file $ARGV[0];
  close $file;
} else {
  print STDOUT "Installed Profiles:\n";
  for (my $i = 0; $i < scalar @profiles; $i++) {
    if ($profile eq $profiles[$i]) {
      print STDOUT "* ";
    } else {
      print STDOUT "  ";
    }
    print STDOUT $profiles[$i];
    print STDOUT "\n";
  }
  print STDOUT "Use kcc-switch \$PROFILE to select a profile\n";
}
