require "declaration/binding.k"
require "declaration/enum.k"
require "declaration/general.k"
require "declaration/initialization.k"
require "declaration/resolution.k"
require "declaration/zero.k"

module C-DECLARATION-SYNTAX

endmodule

module C-DECLARATION
     imports C-DECLARATION-BINDING
     imports C-DECLARATION-ENUM
     imports C-DECLARATION-GENERAL
     imports C-DECLARATION-INITIALIZATION
     imports C-DECLARATION-RESOLUTION
     imports C-DECLARATION-ZERO
endmodule
